### ISSUE TITLE
[Dark theme] Pause on Exceptions button

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1086]
The button's colors seem slightly off. Also the button seems too thick when active. Thoughts @helenvholmes?

![](http://g.recordit.co/bGHTuBHDo4.gif)

**Comment by jasonLaster** [comment]
@binarybaba @nt1m think you could help here? Sorry I think you two are my SVG people :)

**Comment by nt1m** [comment]
@jasonLaster I remember @gabrielluong and I had a conversation about this feature when it was implemented in the old debugger. The first implementation used red for pause on all, yellow for uncaught. We both agreed the tri-state button was confusing, and that it would be better to have some kind of dropdown menu for this purpose.

Something like:
<> ▾  (<> is the icon)
-------------------
Pause on all
Pause on uncaught
Don't pause
-------------------

The icon would still be colored in the state it's currently in, but it would be more obvious more it does.

As for why is the icon currently thicker when checked, that's because the CSS is faulty here: https://github.com/devtools-html/debugger.html/blob/master/src/components/CommandBar.css#L45

In the 3 rules, it should be fill: instead of stroke:. Using stroke: adds a stroke over the existing black fill, which makes the icon thicker.

**Comment by binarybaba** [comment]
I blame the timezone for being late to the party.
