### ISSUE TITLE
Add Flow support for L10N

### ISSUE THREAD

**Issue by Zacqary** [devtools-html/debugger.html#1122]
For https://github.com/devtools-html/debugger.html/pull/1121, I had to add this line to the top of `Frames.js`:
```javascript
const L10N: Object = window.L10N;
```

Without that, flow would complain like this:
```
public/js/components/Frames.js:79
 79:       ? L10N.getStr("callStack.collapse") : L10N.getStr("callStack.expand");
             ^^^^ identifier `L10N`. Could not resolve name

public/js/components/Frames.js:79
 79:       ? L10N.getStr("callStack.collapse") : L10N.getStr("callStack.expand");
                                                 ^^^^ identifier `L10N`. Could not resolve name

public/js/components/Frames.js:99
 99:           L10N.getStr("callStack.notPaused")
               ^^^^ identifier `L10N`. Could not resolve name
```

There are a lot of reasons why I'm against adding stuff as globals and insist that every variable used in a file that's not part of the standard library be imported/required, but I think the fact that it conflicts with Flow is a pretty big concrete reason to avoid it.

**Comment by jasonLaster** [comment]
Hmm.

**Comment by jasonLaster** [comment]
Sorry, clicked the wrong button.

Unfortunately, L10N, will probably have to be a global because of how it works on m-c. Here's the [panel](https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/new/panel.js#10). Feel free to grep for L10N in the devtools dir, it's everywhere.


I bet we can teach flow to understand L10N... We do something similar for eslint.
Here's a [link](https://flowtype.org/docs/declarations.html#declaring-definitions-that-should-exist-at-run-time), which i think is a good way to handle globals...

I'm renaming the issue to be a little more action oriented :)

**Comment by Zacqary** [comment]
Would it work to just have a module that does `export window.L10N as default ` and then remove L10N from eslint's acceptable globals?

**Comment by jasonLaster** [comment]
Perhaps. I wouldn't be opposed to that, but it would be different from how
other tools do it.

**Comment by jasonLaster** [comment]
After thinking about it a bit more, we probably should be consistent and stick with the global. Sorry for being ambivalent

**Comment by jasonLaster** [comment]
This is now supported
