### ISSUE TITLE
Fix font sizes and default sidebar sizes for low-resolution screens

### ISSUE THREAD

**Issue by Zacqary** [devtools-html/debugger.html#1128]
This is what the devtools look like when your window takes up half of the screen on a 13-inch MacBook Pro set to the "Default" screen resolution:
<img width="792" alt="screen shot 2016-11-06 at 2 40 00 pm" src="https://cloud.githubusercontent.com/assets/1445834/20040959/2d105c96-a42f-11e6-85fd-db601fbf91fc.png">

A lot of people turn their screen resolutions up, but quite a few people don't. It also looks okay if you maximize the browser window, but a lot of people don't do that either.

Resizing the sidebars helps, but the font sizes are still an issue:
<img width="824" alt="screen shot 2016-11-06 at 2 44 13 pm" src="https://cloud.githubusercontent.com/assets/1445834/20040978/8eb1f9b4-a42f-11e6-9412-c06456598104.png">

Maybe we should think about media queries, and/or sizing some things by `vw`/`vh`.

**Comment by jasonLaster** [comment]
@helenvholmes @clarkbw @jlongster  curious to see what you think?

**Comment by jlongster** [comment]
I don't understand the font sizing issues, are you saying they should be even smaller? The fonts are locked in as they are though because they match the devtools defaults and changing them requires you to convince the rest of the team to change our default font size (and we aren't going to have a different one only locally).

The real solution is media queries, as you mentioned, and I think there is some work being done on a vertical layout?

**Comment by jasonLaster** [comment]
ahh - I think this is two things:

1. narrow widths, which vertical layout will help with
2. zoom'd in screens which are likely out of scope

**Comment by wldcordeiro** [comment]
@Zacqary I think the vertical layout will help a lot with this.
