### ISSUE TITLE
MouseEvent properties are not displayed

### ISSUE THREAD

**Issue by jsnajdr** [devtools-html/debugger.html#1299]
Execute this in console:
```
window.addEventListener("mousedown", (e) => { debugger; });
```
Then click in the window. The debugger will pause. Inspect the `e` variable.

Expected: As the `e` is a `MouseEvent`, it should have properties like `button`, `clientX`, `pageX` etc.
Actual: Only the object prototype is displayed.

Other 'native' object probably have the same issue. Is it a missing functionality in reps?

**Comment by jasonLaster** [comment]
@nchevobbe is this covered?

By the way, we're pulling in the latest Reps early next week.

**Comment by nchevobbe** [comment]
it should be handled by the reps just fine.
if I take Jarda function and add logging to it, I get the following in today's Nightly : 
![capture du 2016-11-24 15-55-24](https://cloud.githubusercontent.com/assets/578107/20602638/7f9200e0-b25e-11e6-9032-ef04ef81aade.png)

So the rep does handle it like it should in the console.
In the debugger, it does show the correct type, but not much else.
The thing @jsnajdr  was pointing at, I think, is that even when you expand `e` in the scope panel in the debugger, there isn't any of the properties of the `MouseEvent` object, and, from what I understand, the part where you get the properties of an expanded object does not deal with the Reps, right ?

The only thing that could be a problem for Reps is if you were passing a `mode` props to it (last time I checked, you were not), since https://bugzilla.mozilla.org/show_bug.cgi?id=1312178 changed how we handle modes in Reps.

**Comment by clarkbw** [comment]
Yeah, looks like we need to start using the constants file or `Symbol("TINY")` instead of what we are using in the ObjectInspector.

Though this doesn't solve the expansion, it does show those props in the TINY view.

**Comment by nchevobbe** [comment]
> Yeah, looks like we need to start using the constants file or Symbol("TINY") instead of what we are using in the ObjectInspector.

I don't think that the constant file has been copied here yet, since `mode: "tiny" ` is still working.
Yet, using the tiny mode would display the same thing as we already have (i.e. `MouseEvent`)
If you'd want to have at least some properties displayed, you could either use the constants.SHORT mode, or omitting it (which defaults to short mode), like we do in the DomPanel. This would show the first three items of the event.

![screenshot at dec 18 21-56-31](https://cloud.githubusercontent.com/assets/578107/21296473/e8668138-c56c-11e6-8e3e-d34ce322b835.png)

Or maybe this is too long, and that we should modify how object are displayed in TINY mode.

**Comment by clarkbw** [comment]
> I don't think that the constant file has been copied here yet, since mode: "tiny" is still working.

Oh right.  When I change the mode I can see the values we want.

<img width="295" alt="screen shot 2016-12-18 at 3 54 21 pm" src="https://cloud.githubusercontent.com/assets/2134/21297756/53fa4840-c53a-11e6-81ab-f95cb6a523ce.png">

But they still don't appear in the scope view when we request properties because that isn't handled by the Reps, like you said before.  I get it now.

**Comment by clarkbw** [comment]
Ok, looked into this a bunch more.  I tracked it down to the ObjectInspector.

Right here:
https://github.com/devtools-html/debugger.html/blob/master/src/components/ObjectInspector.js#L90-L92

```js
    const nodes = Object.keys(ownProperties).sort().filter(name => {
      // Ignore non-concrete values like getters and setters
      // for now by making sure we have a value.
      return "value" in ownProperties[name];
    }).map(name => {
      return createNode(name, `${parentPath}/${name}`, ownProperties[name]);
    });
```

We only take the objects which have `value` properties.  And the `clientX` etc are all getters so they are skipped by the filter.  The getters need to be handled such that they are no longer filtered from the list and can be represented with their values.

**Comment by jasonLaster** [comment]
cool, so it looks like we're pulling properties  with the new reps

![](http://g.recordit.co/CUiqsMR3NA.gif)

**Comment by clarkbw** [comment]
Thanks Reps!
