### ISSUE TITLE
Adopt chrome-remote-interface

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1310]
We are currently using [chrome remote debugging protocol](https://github.com/jasonLaster/chrome-remote-debugging-protocol), but we'd like to switch to [chrome remote interface](https://github.com/cyrus-and/chrome-remote-interface).

**reasons**
* it's used by vscode, lighthouse, many others
* it has full HTTP support for version, new, list, ... etc
* it has protocol detection support across targets
* we can share adapters for firefox, ios webkit, and other targets in the future

**blockers**
* it relies on an HTTP transport layer that we can not use from the debugger client. We'd like to be able to set our own fetcher.

CC @auchenberg, @cyrus-and, @juliandescottes

**Comment by auchenberg** [comment]
Do you plan on using the CDP directly from the front-end or have a server-side layer in between to enable CORS, etc?

**Comment by jasonLaster** [comment]
We plan on using it in the front end with a simple HTTP proxy for cors.

**Comment by cyrus-and** [comment]
@jasonLaster 

So, let's *defrag* the discussion about this feature and use this thread as a common point. For completeness, here are the previous threads:
- devtools-html/debugger.html#1279
- cyrus-and/chrome-remote-interface#63

Despite what I said, that CRI is meant to run in a Node.js context and so on, I'm interested to fully understand your requirements and to help you in this adoption, if possible.

---

Let's forget for a moment about the CORS issues. I haven't much experience about *browserifying* modules but I see at least these problems:

1. the well-known use of `http/s` modules;

2. the dependency on [ws][1] for WebSockets (possibly related to 1. as the browser has its own API for this too);

3. the fact that CRI comes with a bundled command line utility which is useless in this case.

It seems that all the above can be addressed at bundling/packing time, so I was wondering if we couldn't inject the custom fetcher in the same way. I'd be happy to add a `rollup.config.js` or a`webpack.config.js` to CRI so that you can add the custom fetcher to it.

Of course, I'd love to hear thought from @auchenberg and @juliandescottes too.

[1]: https://github.com/websockets/ws

**Comment by jasonLaster** [comment]
haha - yeah we're down from three threads to one. 

Yeah, webpack could do the trick

1. webpack handles browserifying `http`, `https`, and `event-emitter` out of the box
2. I mapped `ws` to the browser global `WebSocket` in my config
3. if we moved `fetchObject` to its own module, then it would be fairly easy to swap that module out at build time.

I'll take a look early next week. That *does* sound better than forking :)

**Comment by cyrus-and** [comment]
> I mapped ws to the browser global WebSocket in my config

But does it actually work? I'm trying the same but the API is different (constructor, `.on()`, etc.), it would need a wrapper I think.

**Comment by jasonLaster** [comment]
Oy. Perhaps I just didn't run into it yet :)

**Comment by cyrus-and** [comment]
I come up with a possible solution in a [new branch][1]; [here][2] is the documentation.

Now `chrome-remote-interface` should run mostly out-of-the box into a browser context: the user must provide a global `criRequest` function in order to implement a custom HTTP fetcher.

Let me know what you think.

[1]: https://github.com/cyrus-and/chrome-remote-interface/tree/webpack
[2]: https://github.com/cyrus-and/chrome-remote-interface/tree/webpack#browser-usage

**Comment by jasonLaster** [comment]
This looks good! I like `externalRequest`

My one concern is in requiring CRI in the webpack bundle. 

I'd like to be able to `require("chrome-remote-interface")` and have it work. I'm not sure what the best way is to set this up, so l'll explore some options and get back to you. 

Thanks for putting the time in to help so far!

**Comment by cyrus-and** [comment]
> I'd like to be able to require("chrome-remote-interface") and have it work. I'm not sure what the best way is to set this up, so l'll explore some options and get back to you.

So I guess you'll have to include that config into yours, I'm pretty newbie when it comes to webpack though. But at least we should have all the ingredients now.

**Comment by jasonLaster** [comment]
yeah, definitely. perhaps the first step is to expose the webpack in the list of package.json files

then we might be good...

**Comment by cyrus-and** [comment]
You should be able to manually simulate it, I'd happily add it the next time I npm-publish, if it turns out that's enough. Let me know...

**Comment by cyrus-and** [comment]
@jasonLaster FYI I'm using a wrapper now (cyrus-and/chrome-remote-interface@b046e46155508778f19f1cbccabeb38f411815aa), should not impact your work though as you're not using my `webpack.config.js`.

**Comment by jasonLaster** [comment]
thanks for the heads up. 

that's an improvement over this: https://github.com/devtools-html/debugger.html/pull/1320/files#diff-e90849efb3b26f4c34edad35df5d77efR66

going to come back to this soon and sort out the WS things. 

I'd like to use your webpack.config, but i'm not sure how to compose them...

**Comment by jasonLaster** [comment]
landed!
