### ISSUE TITLE
avoid auto-expand of the Window scope

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1492]
The new #1270 is really nice but I'm finding the `Window` scope is being expanded by default and that tends to really slow things down.  For other scopes this is a great feature but I want the larger ones to wait until I open them.

**Comment by jasonLaster** [comment]
That's a good find!

Ahh, i see. Does this happen if you pause in the global scope?

**Comment by jasonLaster** [comment]
@binarybaba interested in this one?

**Comment by binarybaba** [comment]
I'll try :)

**Comment by amitzur** [comment]
Hey, this is still up for grabs. Is it cool to take it?

**Comment by binarybaba** [comment]
I didn't grab it. Go for it! :D

**Comment by amitzur** [comment]
Thank you!

**Comment by jasonLaster** [comment]
sure @amitzur, this is a fun one!

**Comment by jasonLaster** [comment]
Hmm, i couldn't reproduce this.

**Comment by GoldenPenguin** [comment]
Hello, this issue is affecting me currently. I'm working on a project written in GWT that generates a lot of code (with sourcemap) and the window object can take up to 10-15 seconds to expand at each debug step-in/out/over (it re-expands every time). There is around 20000 members in the window object at the moment.

I'll try using the old UI for now (seems much better in that regard). It collapses the window object by default and contains its members within reasonable ranges to prevent heavy processing. Expanding the range 0... 1311 takes less than half a second.

**Comment by jasonLaster** [comment]
Thanks for filing. We'd love to fix this. I created an issue in our Reps project where we create previews.

I think a good next step is to find a small MVP test case
