### ISSUE TITLE
`d` key not working in source search box in Chrome

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#1501]
This is the weirdest thing, and I'm probably crazy, but if I try to type "index" in the sources search box in Chrome, the "d" never shows up.  I tried in Firefox and the "d" key works, but Chrome is bricking the "d" key for some reason.

**Comment by jasonLaster** [comment]
Yeah, this happened to me too and I thought it was me.

You keep filing the issues that confuse me.

**Comment by jasonLaster** [comment]
I looked quickly into this and it turns out that for some reason F8 maps to the `keyD` keydown event in chrome, but not firefox...


```js
shortcuts.on("F8", () => alert("why"))
```

**Comment by clarkbw** [comment]
> F8 maps to the keyD keydown event in chrome, but not firefox...

I assume our library for shortcuts has been tested in Firefox but actually has little or no testing in Chrome.  Overtime this might be a reason to look at something else like [mousetrap](https://craig.is/killing/mice) which has much broader test coverage.

**Comment by jasonLaster** [comment]
> mousetrap

Yeah - that could definitely work

> our library for shortcuts

Here's our [library](https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-sham-modules/client/shared/key-shortcuts.js#L19
) for shortcuts and here's where the F8 mapping comes in...

Lots of browny points to the person who figures this out :)

**Comment by Dalimil** [comment]
Here to collect brownie points...
https://github.com/devtools-html/devtools-core/pull/79

There is nothing specific about F8, but like any other functional key it has a digit in its mapped string name: `DOM_VK_F8`, and then I saw this azerty keyboard fix: `(shortcut.key.match(/[0-9]/) && event.keyCode == shortcut.key.charCodeAt(0));` and yeah, keycode of letter `d` matches the first letter of `DOM_VK_F8` so we emit an F8 keypress instead of typing `d`. 

I fixed this by changing the regex to `/^[0-9]$/` - although this might need to be tweaked further as I wasn't 100% sure what kind of shortcut needs the azerty code in the first place.

**Comment by jasonLaster** [comment]
🍺  Thanks @Dalimil!
