### ISSUE TITLE
MVP of Blackbox sources

### ISSUE THREAD

**Issue by nt1m** [devtools-html/debugger.html#1535]
We're planning on implementing blackboxing in Q1. 

Currently this ticket hasn't been broken down.

**Comment by clarkbw** [comment]
The old system was under a feature flag previously #437 but this work is scheduled for Q1.

**Comment by clarkbw** [comment]
Here are some notes on the existing design.

## Firefox

Main interface for toggling is located at the bottom of the sources list.

<img width="156" alt="black box toggle button" src="https://cloud.githubusercontent.com/assets/2134/23834747/ce7d7fa4-0718-11e7-9ea1-5a43159e9aad.png">

View when a source file is blackboxed

<img width="909" alt="screen shot 2017-03-12 at 11 39 57 am" src="https://cloud.githubusercontent.com/assets/2134/23834756/f2a01928-0718-11e7-83b1-d7ab51004d38.png">

Auto-blackbox minified sources preference, which defaulted to **on**.

<img width="360" alt="screen shot 2017-03-12 at 11 43 09 am" src="https://cloud.githubusercontent.com/assets/2134/23834770/18b2adec-0719-11e7-9d37-0aba0f3adf14.png">

**Comment by clarkbw** [comment]
Here's what I'd recommend as an MVP of this feature.  I think we can go well beyond this recommendation later but here's the starting point.

The main interaction point is a context menu in the Sources Tree.  This menu item allows to turn on and off the black boxing of a single script.  Sources which are currently black boxed should probably have some indicator such as the eye icon instead of the normal file icon... not sure.

The editor will indicate when the current script is black boxed.  The current system hides the entire editor area, this might be a nice solution as it would prevent users from adding breakpoints which will be ignored.  I'm offering a small indicator at the bottom of the editor as a starting point.

### Blackbox Script

For a script which isn't already blackboxed there should be an option to turn on blackboxing for it.

This text should read `Blackbox Script` which turns on blackboxing for this script.

<img width="279" alt="screen shot 2017-03-29 at 11 43 34 am" src="https://cloud.githubusercontent.com/assets/2134/24466354/339eef2a-1476-11e7-9586-dee259fa3185.png">

### Un-Blackbox Script

For a script which is already blackboxed there should exist a menu item for turning blackboxing off for it.

<img width="347" alt="screen shot 2017-03-29 at 11 51 54 am" src="https://cloud.githubusercontent.com/assets/2134/24466399/5ff6c782-1476-11e7-80a4-48e9dccd7497.png">

### Is Blackboxed

For a script which is blackboxed there should be an indicator in the Editor.  This indicator could also act as a button to "Un-Blackbox Script".  Colors here should not be continued, only used as an example.

<img width="923" alt="screen shot 2017-03-29 at 11 48 08 am" src="https://cloud.githubusercontent.com/assets/2134/24466478/a1220546-1476-11e7-9fb1-04800f08eff6.png">

**Comment by nt1m** [comment]
It would be nice to have some kind of indicator in the file tree.

**Comment by nt1m** [comment]
Also, next to "Black Boxed", I would add "Un-black box ?" as a blue link

**Comment by clarkbw** [comment]
We could simply strike through the text in the source tree.

**Comment by wldcordeiro** [comment]
> Auto-blackbox minified sources preference, which defaulted to on.

In more modern development systems we have source-mapped files, what if we had the preference auto-blackbox `node_modules` in the source mapped files? Might be out of scope for MVP, just thought of it when I read the line.

**Comment by clarkbw** [comment]
> Might be out of scope for MVP, just thought of it when I read the line.

Great idea!  Similarly @jasonLaster mentioned that it would be great to be able to "blackbox a directory" such that you could right click on `node_modules` and blackbox everything within it.  But I like the idea that we might auto-blackbox this directory by default, I think most people would like that.

**Comment by clarkbw** [comment]
Here's what I'd call out for priorities / goals.

1. Context menu for adding / removing
2. Indicator in Source Tree and Editor of `isBlackboxed` (Editor could be hidden like the old debugger)
3. (Stretch Goal) Better Editor integration by showing the editor but preventing users from creating breakpoints

**Comment by clarkbw** [comment]
And we should open up a separate issue for discussing what we'd really like to see in the full version of Blackboxing.

**Comment by jasonLaster** [comment]
We did that in #2523
