### ISSUE TITLE
Fix React.render and React.findDOMNode warnings

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1640]
We've been getting these ReactDOM.render warnings for awhile, but haven't had time to trace it down. It would be really appreciated if someone could find where we're doing this.

The best way to approach this would probably be to grep for `findDomNode` and `render` and see if you can find it that way. 

The other way would be to put breakpoints in these functions

![screen shot 2017-01-06 at 11 07 43 am](https://cloud.githubusercontent.com/assets/254562/21723957/68be691c-d400-11e6-9ff8-4c835b0d2eb5.png)

**Comment by clarkbw** [comment]
Here's a quick video on how to break on these errors and find the root cause... 
![use-callstack](https://cloud.githubusercontent.com/assets/2134/21728620/110f0310-d3fc-11e6-970c-7ffcff5adfcf.gif)

* Click location in the console
* Break on that error
* Use the call stack to go up the stack until you find code that looks like the problem

**Comment by liorpr** [comment]
started to look into this, here's what I got so far:

1. the deprecation mechanism works per function for the whole app, so it's not about where its happening, but why(tried to remove the mentioned render call and got this warning from somewhere else)
2. don't know why but it seems like the app does not require the correct react-dom package, but the react one, that's why the render method is considered deprecated. can't figure out how to correct this, maybe someone have an idea? didn't see explicit definition of react-dom package in package.json

**Comment by wldcordeiro** [comment]
@liorpr could it be because of us doing this in a lot of our components?

```js
const React = require("react");
const { DOM: dom, PropTypes } = React;
```

Shouldn't `dom` come from the `react-dom` lib and not `react`?

**Comment by jasonLaster** [comment]
nice idea @wldcordeiro we should definitely fix these!

**Comment by liorpr** [comment]
yeah that's definitely shouldn't be there, but even when I break on EditorBreakpoint.js(like in the image above) it happens, and it requires("react-dom")

**Comment by clarkbw** [comment]
> Shouldn't dom come from the react-dom lib and not react?

I don't think [ReactDOM](https://facebook.github.io/react/docs/react-dom.html) provides a `DOM` object.  I believe that is supposed to come from React itself, though it is somewhat undocumented, you'll find it in their [examples](https://github.com/facebook/react/blob/master/examples/basic/index.html#L36)

**Comment by irfanhudda** [comment]
> I don't think ReactDOM provides a DOM object. I believe that is supposed to come from React itself, though it is somewhat undocumented, you'll find it in their examples

I agree with this. There is some documentation [here](https://facebook.github.io/react/docs/react-api.html#createelement).

**Comment by clarkbw** [comment]
My next guess is that webpack is possibly doing something strange given the https://github.com/devtools-html/debugger.html/issues/1640#issuecomment-271255082 from @liorpr

**Comment by MattCain** [comment]
Webpack is definitely doing something strange, `require("react-dom");` is returning react rather than react-dom.

**Comment by liorpr** [comment]
can someone please explain what this means? couldn't find the devtools/client/shared......

<img width="610" alt="screen shot 2017-01-11 at 1 34 42 pm" src="https://cloud.githubusercontent.com/assets/6891569/21847154/fda29d36-d802-11e6-8022-075e7f297d5f.png">

**Comment by jasonLaster** [comment]
@liorpr this is coming from when we make a build for firefox. not relevant here.

@MattCain Have you looked in the`node_modules/react-dom` it could be that they reference react...

**Comment by liorpr** [comment]
@jasonLaster checked the react-dom package, it references to react.DOM but that's ok because the react team switched to an actually separate package only in 15.x. it looks like a webpack related problem
