### ISSUE TITLE
Command Bar redesign

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1665]
I'm adding this issue to track a discussion that @Garbee and I had this morning.

It would be nice to think through how we present the pause actions / message in the command bar.

**Goals:**
* make the ux more clear
* easier for new comers
* improve accessibility

**Insights:**
* we can move the *other* breakpoints "pause on next execution" "pause on exceptions" to the breakpoints pane. Infact VS Code beat us to it.
* we can hide the "paused" actions and only show them when we're paused.

Here's one UI that takes advantage of this. I think @Garbee will likely have an alternative that avoids the dropdown and is more clear.

![command bar redesign](https://cloud.githubusercontent.com/assets/254562/21817246/401606ee-d731-11e6-8e2b-cecb29d3f1dd.jpg)

**Comment by krishnagopinath** [comment]
I like how the "Paused at a Breakpoint" section is placed. Looks clean, doesn't waste real estate and just does one thing - conveys the message loud and clear :) 

This gives way for using other color tones for the text, like when there's an error, etc.

**Comment by jasonLaster** [comment]
Yea, it's worth noting that if we're paused at a breakpoint, then the breakpoint also gets styled.

> color tones for the text, like when there's an error

👍

**Comment by clarkbw** [comment]
👍 

Only thing I'd like to iterate on is the button that brings up the "Pause On" dialog.  The plus button doesn't convey enough information.  Perhaps just creating a button with the text "Pause On..."?

**Comment by nt1m** [comment]
@jasonLaster I'd prefer making "Pause on next execution" a label of the toolbar button that brings up the dialog, it saves some space, and makes sense in this context.

Something like:
```
_______________________________________________________
- [x]                                  ||  on next execution ▾  | + |
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
```

**Comment by Garbee** [comment]
In my initial design these exception triggers are all radios in the main breakpoint list. The idea being dropdowns/dialogs/etc. all obscure the functionality away. Some developers may not realize this functionality exists except by accident if it is tucked away behind a dropdown/dialog/multi-trigger button.

I'll share the look I am going for tomorrow when I have a bit more of the functionality moved around so the fuller idea is there. Once the main move is done changing the design from there to whatever is desired will be fairly seamless.

**Comment by jasonLaster** [comment]
Thanks @nt1m. That's a nice idea - i'll draw it up.

Thanks @Garbee. Don't put too much time into wiring it all up, i'm not sure if we'll be ready to act on this now with the release coming up soon.

**Comment by Garbee** [comment]
The wiring is easy and the bulk is done now. The only two things I have left to move is the pause on next execution and adding back the toggle all. Then adding a remove all button. All very easy and non time consuming. At that point I make the UX clearer to start showing off for further discussion. Should be ready in time for tomorrow's community call.

**Comment by Garbee** [comment]
Oh, and "Pause on next execution" for the top label if we do have a dialog is a bad label. It in no way reflects the other two options underneath about exceptions, or that the actual toggle is a dialog and not that action. That is a dark UX pattern and should be avoided.

**Comment by nt1m** [comment]
@Garbee I'm afraid having radio buttons will take up too much vertical space, especially in the devtools toolbox where the default tool height is (250 - 24)px. While it helps for the discoverability, I'd really want to avoid the sidebar turning into a giant form.

**Comment by jasonLaster** [comment]
Here are two more designs based on @Garbee's list and @janodvarko's command bar idea.

![design - honza](https://cloud.githubusercontent.com/assets/254562/21895534/1b942496-d8b1-11e6-9d58-904953805fd8.jpg)

![breakpoints - garbee](https://cloud.githubusercontent.com/assets/254562/21895533/1b87b7ba-d8b1-11e6-9798-daaa4f1ed092.jpg)

**Comment by Garbee** [comment]
Here is a gif of what I have running right now:

![test](https://cloud.githubusercontent.com/assets/868301/21898124/c9ba71b2-d8b9-11e6-9b70-19c0b806d4e4.gif)

1. Exception radios are underneath a collapse pane. The summary of which updates to detail in text what mode it is in.
2. CommandBar only renders when paused at the top of the secondary panel.
3. Pause on next execution is a button to trigger under breakpoints.

The design side is not put together fully. This is more of a hacked up demo to have a functional idea to play with. This mode however puts the toggles inline with the existing breakpoint flow, which makes it clearer to developers what they will cause and why. It also allows for a concise area of space to relay all the information a developer needs about the breakpoint state without having to know colors or symbols. As everything is explained in clear text. The colors and symbols are an added bonus to the interface.

My current idea for the global toggle and removal actions is to have those in a command bar sitting on top of the user breakpoints once they exist. That way the correlation is direct as to what it is affecting since any of those actions wouldn't affect the global breakpoint toggles. I'll have that working momentarily.

**Comment by Garbee** [comment]
One thing we just discussed to try is moving the "Why paused" message into the right of the command bar as well. Flex display the bar, move the reason to the end of the flex flow. Then the message can be left-aligned within that and overflow onto other lines just fine while staying legible. That would also save a little bit more screen real estate instead of having the message with so much extra padding.

**Comment by Garbee** [comment]
PR #1712 is open with the actual code to look at. So anyone can pull that down and play around. This certainly needs a lot of discussion since the UX changes are quite major. As a side I also tested with JSX for the components I modified heavily. This is very easy to rollback if we don't want to go down that path though.

**Comment by jasonLaster** [comment]
@Garbee mind sharing some screens from #1712 so that we can see what the UX was like?

**Comment by Garbee** [comment]
The initial view with a few breakpoints provides:

1. A trigger button with good text to pause on the next execution.
2. A collapse area that contains the exception pausing state radios to switch between them.
3. The list of breakpoints with the toggle all and a new remove all button at the top of the list.
    * Note: The UX for removing all needs to be worked on. Currently it is hacked up with a `confirm` dialog. This is due to hearing complaints in the past with Chrome DevTools where some people have lost "hundreds" of breakpoints for one reason or another. We need either a guard to prevent one-click deletion or a short-term recovery method to get breakpoints back.

This provides direct actions to have the DevTools carry out different tasks without being obscured by buttons with only icons and hover text to know what they do.

<figure>

![initial-view](https://cloud.githubusercontent.com/assets/868301/22150941/d70f8baa-dee9-11e6-8836-e42691c58ff7.png)

<figcaption>
  Initial view of the breakpoints area.
</figcaption>
</figure>

If you expand the Exceptions section then you'll be provided the radios to toggle the various break-on states. This also will update the heading of the section with the current pausing mode. So even when collapsed, the developer is provided clear indication of what mode the tools are in.

<figure>

![exception-mode-expanded](https://cloud.githubusercontent.com/assets/868301/22151113/98aff4de-deea-11e6-8b35-99a106266ad0.png)

<figcaption>

</figcaption>
</figure>

The trigger for pausing on next execution is a button at the top of the breakpoint area. Upon activating, the button becomes disabled and the text is updated to inform the developer of what will happen.

<figure>

![pause-inactive](https://cloud.githubusercontent.com/assets/868301/22151200/094d8eea-deeb-11e6-9997-b5072053035e.png)

<figcaption>
  Pause on next execution when inactive
</figcaption>
</figure>

<figure>

![pause-active](https://cloud.githubusercontent.com/assets/868301/22151207/10aaf5e2-deeb-11e6-838f-84aaf8f5e17d.png)

<figcaption>
  Pause on next execution when active
</figcaption>
</figure>

**Comment by jasonLaster** [comment]
This was an awesome discussion about our directon. I'm closing this now and we can open small more focused issues around pause on exceptions and other UI elements.
