### ISSUE TITLE
[Editor] update selection UI

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1671]
I find the styling of the outlined element a bit strange, it looks like it cuts-off a bit of them

![capture du 2017-01-10 08-41-07](https://cloud.githubusercontent.com/assets/578107/21797641/95e01cfc-d710-11e6-8738-58e6efc831cf.png)

And a bit weird on the selection too (looks like a double border) : 
![capture du 2017-01-10 08-42-39](https://cloud.githubusercontent.com/assets/578107/21797679/cf5a7108-d710-11e6-905e-971ba3b5a40c.png)

If we could have some padding on this outline it would be great

Another nit, out of scope here, is the selection color in dark mode, which isn't contrasted enough with the text's color (see http://leaverou.github.io/contrast-ratio/#%23E4EEFA-on-%23BDD5FD)

Here's where the CSS [is](https://github.com/devtools-html/debugger.html/blob/master/src/lib/codemirror-mozilla.css#L128-L161)

**Comment by jbhoosreddy** [comment]
Could I grab this one? I've already looked into it

**Comment by jasonLaster** [comment]
sure1

**Comment by jbhoosreddy** [comment]
So, the padding issues aside, I was dealing with the selection color. Since different tokens can have different text colors, having a fit-all selection color doesn't seem to work as well as I hoped. I'm trying to keep in mind what Nicholas mentioned about color contrasts.
I went back to sublime to see how they handle it. It seems it's a "light" muted color which might also have transparency. But I like how they handle it. What do you think @jasonLaster @nchevobbe?
