### ISSUE TITLE
add nvm to our development requirements

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1828]
Our project requires a [specific minimum version of node](https://github.com/devtools-html/devtools-core/blob/f0a17da28f2415fbd1526d71847100cc5d286a90/packages/devtools-launchpad/bin/development-server.js#L98) to run. If we are going to ask people to have a specific version of node we should probably recommend that they use [nvm](https://github.com/creationix/nvm) to help manage their node versions.

Lets add `nvm` to the getting started docs and start using it ourselves.  One issue is that `nvm` does not support Windows, for those users we'll need to ask that they use the node installation package.  

Though the `nvm` page says this is unsupported I think the best method is to install using homebrew.

```bash
brew install nvm
```

Sound good @devtools-html/debugger people?

This would also address #1814 where we found that people were having issues running the `prepush` script because `husky` was preferring to use `nvm` if it was available.  This happened to several people in a recent workshop.

**Comment by jasonLaster** [comment]
Hmm, I think I switched philosophically from having very detailed dependency instructions to more broad instructions with helpful links.

i.e. 
* instead of saying here's how to install `yarn` we point to the yarn instructions
* instead of saying how to install and use nvm, we say our requirement is `node 7` and we recommend using `nvm` to do it.
