### ISSUE TITLE
[SourceFooter] Polish Pretty Print button

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1837]
The pretty print button is currently pretty small. Also the CSS is pretty bad.

Goals:
* set the footer to a consistent height with the top bar  (30px i think)
* align the pretty print button with flex (align-items center i think)
* make the pretty print button the same height as the command bar items

UI:
![screen shot 2017-01-25 at 9 23 42 am](https://cloud.githubusercontent.com/assets/254562/22294110/09068a10-e2e0-11e6-8deb-fde1ad4f975b.png)

Thanks @juliandescottes for bringing this up

**Comment by Garbee** [comment]
> align the pretty print button with flex (align-items center i think)

It already is. The problem is the SVG creator we have rendering an `i` with the SVG element inside of that. It offsets the styling. We need to do more direct targeting of the SVG/i here to get it to look right. Ideally though, this shouldn't be necessary as the SVG node should return a plain SVG element non-wrapped. That way any styling outside is easy to touch it without knowing exactly what the internal markup structure is.

**Comment by jasonLaster** [comment]
@princiya is on it

**Comment by wldcordeiro** [comment]
![screenshot_20170203_163631](https://cloud.githubusercontent.com/assets/580982/22612603/f5b7f47a-ea2e-11e6-8a69-cfab72af5a7a.png)

Fixing the coverage button to be vertically aligned with pretty print would also be great here.

**Comment by jasonLaster** [comment]
@wldcordeiro we can do code coverage when we land the backend and polish
