### ISSUE TITLE
[EditorSearch] Add function search UI

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1845]
Function Search UI:

- [x] polish autocomplete summary
- [ ] add compact result list #2047
- [ ] add function search bottom bar button

----
We're working on a function search POC in #1995. When that lands, we'd like to add a proper UI for the feature.

I'd like to get some feedback on this UI I sketched. The main pieces are:

1. function search button is in the bottom left and is a label
2. search results are a compact list and follow the same hover/select/focus rules as the source tree.

![function-search](https://cloud.githubusercontent.com/assets/254562/22855693/3bc6fe24-f052-11e6-862d-922fa8183bb4.jpg)

**Comment by jasonLaster** [comment]
Including Helen's mock which has a label in the input, which could be helpful


![](https://cloud.githubusercontent.com/assets/254562/21696191/e4a17e30-d35a-11e6-8675-4bb7ff191ca7.png)

**Comment by wldcordeiro** [comment]
I like Helen's mock, it makes the function search stuff's design match the search modifiers in the editor searchbar more closely.

**Comment by jasonLaster** [comment]
Yea. I like that the magnifying glass titles the secondary bar.

**Comment by clarkbw** [comment]
Here's a list of things left to fix here:

- [ ] make the autocomplete CSS more generic instead of file search specific with function search CSS trying to turn off borders it doesn't want.
- [ ] fix the bug where you can arrow into an item that doesn't exist, this seems to be an issue with the `selectedIndex` though I haven't investigated yet
- [ ] somehow handle when the results are larger than the 300px we make available.  Either scroll the results or limit them and require more typing?

**Comment by clarkbw** [comment]
> fix the bug where you can arrow into an item that doesn't exist, this seems to be an issue with the selectedIndex though I haven't investigated yet

I think I just saw this in action and believe it has to do with multiple definitions.  If you have the multiple Backbone models in a file you could have several `initialize` functions.  It seems we aren't showing the different versions but still allow you to arrow through them and navigate to them.

**Comment by jasonLaster** [comment]
Oh nice. We should make the key name + line number
