### ISSUE TITLE
Command Bar should be fixed to the top

### ISSUE THREAD

**Issue by yurydelendik** [devtools-html/debugger.html#1918]
We currently scroll the entire secondary pane. We should try and *fix* the command bar to the top, so that it is always visible. [see gif]

@garbee suggested that we could make the command bar sticky.

```diff
diff --git a/src/components/SecondaryPanes/CommandBar.css b/src/components/SecondaryPanes/CommandBar.css
index e79dca3..2845e78 100644
--- a/src/components/SecondaryPanes/CommandBar.css
+++ b/src/components/SecondaryPanes/CommandBar.css
@@ -2,6 +2,7 @@
   flex: 0 0 30px;
   border-bottom: 1px solid var(--theme-splitter-color);
   display: flex;
+  position: sticky;
 }

 .command-bar > button {
 ```

![](http://g.recordit.co/SSspwofVJF.gif)

---

STR:
1. Open and start debugging a web page with debugger statement (e.g. https://devtools-html.github.io/debugger-examples/examples/localstorage-keys.html)
2. On first debugger statement, expand the "Window" scope at the bottom
3. Scroll the secondary panel all the way to the bottom

Actual result:
Debugger control toolbar/buttons are hidden

Expected result:
Debugger control toolbar/buttons are visible

It's a regression, bisect results:

```
0c5485c6d3db4e60acae756c33a8441206392052 is the first bad commit
commit 0c5485c6d3db4e60acae756c33a8441206392052
Author: Jonathan Garbee <jonathan@garbee.me>
Date:   Tue Jan 31 09:39:32 2017 -0500

    Fix SecondaryPanes contents to flex properly. (#1893)
```

/cc @Garbee #1893

**Comment by Garbee** [comment]
So, what exactly does this look like scrolled? Do we have the contents of each accordion with a set height and make them scrollable? Or just scroll the pane itself but keeping the commandbar and why paused pieces fixed to the top?

If it is about fixing those two pieces, then the fix is trivial by just applying `position:sticky` here. If we want to individually scroll each accordion's content without causing the headers to get lossed, then I'm going to need to investigate this more to find a decent solution.

**Comment by wldcordeiro** [comment]
I think the command bar isn't remaining fixed like it used to be @Garbee

**Comment by Garbee** [comment]
Discussing this in slack just now it looks like we only need to keep the CommandBar itself stickied and not the `WhyPaused` bit or anything else.

**Comment by clarkbw** [comment]
I was able to make this by adding this:

```css
.command-bar {
	position: fixed;
	width: 100%;
	background-color: white;
	z-index: 100;
}
.pane.why-paused {
	margin-top: 30px;
}
```

The tricky part are these:
* using `margin-top: 30px` is a little fragile, but no way to solve that without using variables
* you need a high z-index because a lot of the panels are running over the fixed position otherwise.

Might be better to look into an alternate layout approach.

**Comment by Garbee** [comment]
Oh did I not PR this already? ... oops.

Position sticky avoids the top margin since it is inline until scrolling happens. The fix should be this:

```css
.command-bar {
  position: sticky;
  top: 0;
  z-index: 2; // Not really sure why we'd need a higher z-index value unless something else is raised up.
 background-color: white;
}
```

At least for [browsers that support sticky](http://caniuse.com/#feat=css-sticky). IE/Edge will just have it not sticking to the top. Which seems like a fine graceful degredation in those engines.

**Comment by jasonLaster** [comment]
@Garbee pr it up

**Comment by clarkbw** [comment]
> Oh did I not PR this already? ... oops.

DO IT! 🎯

**Comment by Garbee** [comment]
Incoming once I test it again real fast just to verify it still works with the more recent work that's gone on...

**Comment by Garbee** [comment]
#2128 is up to address this. So sorry I didn't do that last week when I wrote the fix originally... I thought I had.

**Comment by clarkbw** [comment]
🔫

**Comment by princiya** [comment]
10 days back I had grabbed this issue, but I started working on this just today ;), my bad!!! Just when I was about to create a PR, it said I couldn't merge and the fix was already there :D Anyways, it was the same to same fix :)

**Comment by jasonLaster** [comment]
Haha. Glad it was similar. Sorry for the confusion

**Comment by princiya** [comment]
No problem, only surprised with the coincidence ;)
