### ISSUE TITLE
[CallStack] asynchronous stack traces

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1972]
__Migrating from [bug 1142571](https://bugzilla.mozilla.org/show_bug.cgi?id=1142571)__

We want to show async stack traces in the debugger.  There is a pref required for Firefox to turn on async stacks, `javascript.options.asyncstack`, this is done because there is a performance penalty associated with this option turned on.  To mitigate this we could offer the option in the stacks column for `Async [ ]` which would toggle this pref. (also likely turning the pref off when the debugger / toolbox is closed)  However we need the server to be updated to send the required frames information.

Load the following into your browser URL bar with the debugger open:

```html
data:text/html,<script>setTimeout(function foo() {setTimeout(function bar() {console.trace();debugger;}, 100);}, 100);</script>
```

You should see a trace with:

-   `bar();`
-   `foo();`

But currently the debugger only shows:

-   `bar();`

These traces are already available in the console via [bug 1200832](https://bugzilla.mozilla.org/show_bug.cgi?id=1200832).

**Comment by clarkbw** [comment]
@tromey you did the console work, do you think you could look at this debugger side of things?

**Comment by tromey** [comment]
I looked into it a bit today.  I want to do it, but I don't have time to implement it right now.

I think the basic issue is that the debugger server doesn't return async parent frames.  Looking into it a bit deeper, I see that `js/src/vm/Debugger.cpp` makes a frame iterator and uses that to implement `Debugger.getNewestFrame()` and `Debugger.Frame.older`.  However, this code instead has to notice when a frame has an async parent and switch to returning those, like `SavedStacks::insertFrames`.

Another option might be to compute the stack trace in two different ways in the debugger server, one using the Debugger API (as it is now) and the second time using `Component.stack`; then correlating the two.  This could be isolated in the debugger server so that it mostly keeps the same API -- just adding the async reason to some frames.

**Comment by clarkbw** [comment]
> I looked into it a bit today. I want to do it, but I don't have time to implement it right now.

Thanks for the investigation!

**Comment by jasonLaster** [comment]
Thanks @tromey.

**Comment by jasonLaster** [comment]
Closing as we will not get to this in Q2. It's in the enhancements board and we should revisit it in Q3.

**Comment by jimblandy** [comment]
I think this situation is actually easier to engineer than the old async stacks attached to promises.

The problem with the old approach of attaching stacks to promises&mdash;the approach that got turned off by default for performance reasons&mdash;is that it was only of interest to developers. When ordinary code is running in a page that isn't under inspection, collecting those stacks is pure overhead.

Async/await functions are different. They inherently must collect a stack, because they actually need to return to those frames. Since the data is necessary even when tools aren't looking at the page, there's no extra information to collect: the tools just need to display data that's already there.

The Debugger API cannot presently treat suspended generator frames (which is what async/await frames are under the hood) as referents of Debugger.Frame. It was always the plan that we would do this, but we didn't get around to it. Maybe now that generators are hooked up to promises nicely and they're getting some uptake on the web, the time has come.

The other step (maybe not so separate? I'm not sure) is being able to follow the chain of frames through the promises. Suppose an async function A awaits on a call to an async function B. Calling B produces a promise of B's return value. A's await registers A's generator as a handler expecting that promise's value.

So we have links from B's frame to its promise, and from the promise to A's frame.
This is the "stack" that developers expect to see. A Debugger.Frame referring to B's frame, whether suspended or live, when asked for the next older frame, should produce a Debugger.Frame referring A's suspended frame.

[bug 1343158]: https://bugzilla.mozilla.org/show_bug.cgi?id=1343158

**Comment by jasonLaster** [comment]
Thanks @jimblandy,  opening as we're planning on working on it in the next couple months

**Comment by digitarald** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Async Call Stack](https://trello.com/c/oYD570Mt/45-async-call-stack)

**Comment by digitarald** [comment]
@jimblandy this is something we want to prioritize for Q4. Further, is async stacks something we can solve in the long term without the performance penalties that are currently associated with the pref?

**Comment by jasonLaster** [comment]
Lets move the conversation back to bugzilla as the work will be done in platform / server
