### ISSUE TITLE
[Breakpoints] can't set breakpoint in prettified source

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#1989]
I tried the test case in [bug 1327713](https://bugzilla.mozilla.org/show_bug.cgi?id=1327713).  After prettifying the source, when I try to set a breakpoint, the breakpoint briefly appears, and then disappears.

I don't see an stack trace in the console, but enabling pause-on-exception shows an exception coming from `addBreakpoint` saying: "query object's 'line' property is neither undefined nor an integer".

[TEST PAGE](https://hex-lines.glitch.me/)

**Comment by jasonLaster** [comment]
**STR 1:**
1. Open attached "testcase 1"
2. Open debugger, prettify script containing word "click"
3. Set breaking on "click" event, click on the page
4. Keep clicking "Step in" button until line "console.log(123);" is executed

**AR:**
 When debugger steps into a function, then, if the first token in that function is "function",
 debugger jumps to line 1. That line becomes highlighted with green; caret is displayed in that line

**ER:**
 When debugger steps into a function, some sensible line inside that function should be selected.
 In other words, debugger should select lines in the very same sequence as in STR_2 (see below).


**STR_2:**
1. Open attached "testcase 1"
2. Set breaking on "wheel" event, hover mouse over the page, rotate mouse wheel down once
3. Keep clicking "Step in" button until line "console.log(123);" is executed

AR:  Everything's OK


Here's the testcase 1:

```html
<script src="data:text/javascript,
(function(){
  var A = {};
  window.A = A;
  A.F = function(){
    A.G();
  },
  A.G = function(){
    function _G(){};
    A.H();
  },
  A.H = function(){
    A.I()
  },
  A.I = function(){
    function _I(){};
    A.J();
  };
  A.J = function(){
    function _J(){};
    A.K();
  };
  A.K = function(){
    console.log(123);
  };
  
  addEventListener('click',A.F,false);
})()
//.js"></script>

<!-- a bit confusing -->

<script src="data:text/javascript,
(function () {
%0A  var A = {
%0A  };
%0A  window.A = A;
%0A  A.F = function () {
%0A    A.G();
%0A  },
%0A  A.G = function () {
%0A    function _G() {
%0A    };
%0A    A.H();
%0A  },
%0A  A.H = function () {
%0A    A.I()
%0A  },
%0A  A.I = function () {
%0A    function _I() {
%0A    };
%0A    A.J();
%0A  };
%0A  A.J = function () {
%0A    function _J() {
%0A    };
%0A    A.K();
%0A  };
%0A  A.K = function () {
%0A    console.log(123);
%0A  };
%0A  addEventListener('wheel', A.F, false);
%0A}) () //.js
%0A"></script>
```

**Comment by clarkbw** [comment]
Just tried this again and it still seems to be an issue.

**Comment by jasonLaster** [comment]
@NickMalt did some great research in #4902 and started a mochitest

I think we've narrowed the problem down to how we create the URLs

---

After some debugging I think that I caught this bug:

1) Here we send correct parameters but got `{ line: null, column: null }`.  Which is why breakpoint flashing.
https://github.com/devtools-html/debugger.html/blob/223d35a570d4762000c736e00e5a16b09c9ae8c6/src/utils/source-maps.js#L17-L20

2) [Here](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/source-map/worker.js?q=const+%7B+line%2C+column+%7D+%3D+map.generatedPositionFor%28%7B&redirect_type=single#674) we handle this request in source-map worker. But [_findSourceIndex](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/source-map/worker.js#2912) return `-1` as if this source did not exist.
￼
![image](https://user-images.githubusercontent.com/7029391/34024522-5911b1f2-e16c-11e7-9a2e-678619ad1ee8.png)
![image](https://user-images.githubusercontent.com/7029391/34024528-64e29dac-e16c-11e7-8225-c607a89879bb.png)


3) The problem is in property `sourceUrl` mismatch.
This one we send to worker:
![image](https://user-images.githubusercontent.com/7029391/34024537-7af15a0c-e16c-11e7-8cf5-b0db8e72b847.png)
This one we have in worker: 
![image](https://user-images.githubusercontent.com/7029391/34024538-7cdad5b4-e16c-11e7-8361-5dda6af17d53.png)
And we have this mismatch because of path [normalization](https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/new/parser-worker.js#28487) in [worker](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/source-map/worker.js#2474)
![image](https://user-images.githubusercontent.com/7029391/34024676-4f2780e4-e16d-11e7-8bb5-3252538efb29.png)

4) And if we add this patch to [normalize function](https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/new/parser-worker.js#28487), everything works ok.
![image](https://user-images.githubusercontent.com/7029391/34024772-e611983c-e16d-11e7-8d01-4a7b5eb04ec2.png)

### Before/After
![bp before](https://user-images.githubusercontent.com/7029391/34025511-0bfddf7a-e172-11e7-8332-ded29faf2789.gif)
![bp after](https://user-images.githubusercontent.com/7029391/34025518-11ad6490-e172-11e7-9e30-556aacb347e9.gif)



@jasonLaster The question is, how to properly change normalize function? I’m probably miss something, because do not see the whole picture.

And how should I continue this? I mean how to contibute to `mozila-central`?

**Comment by jasonLaster** [comment]
Hey @NickMalt how's your schedule these days?

**Comment by jasonLaster** [comment]
@NickMalt if you're free these days claim it. Otherwise, this is now open for anyone to claim

**Comment by jasonLaster** [comment]
I'm moving the issue to the icebox. We will re-prioritize the issues in the icebox at the beginning of the next release in 6 weeks.
