### ISSUE TITLE
[EditorSearch] cmd+f jumps files

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1993]
If you do a search in one file, and then select another file, it's possible that you'll start jumping between the two:

STR:
1. select `todo-view`
2. search app
3. select `app-view`
4. hit enter, repeatedly

ER: iterate through app-view `app` references
AR: alternate between`app-view` and `todo-view`

Here is a good **patch** to get you started:

```diff
diff --git a/src/components/Editor/SearchBar.js b/src/components/Editor/SearchBar.js
index d0ee139..56167df 100644
--- a/src/components/Editor/SearchBar.js
+++ b/src/components/Editor/SearchBar.js
@@ -169,6 +169,8 @@ const SearchBar = React.createClass({
       return;
     }

+    // look here
+
     const ctx = { ed, cm: ed.codeMirror };
     const { index, count } = this.state;
     const { query, modifiers } = this.props;
diff --git a/src/utils/editor/index.js b/src/utils/editor/index.js
index 41c9d14..f7879f4 100644
--- a/src/utils/editor/index.js
+++ b/src/utils/editor/index.js
@@ -107,6 +107,8 @@ function resizeBreakpointGutter(editor) {
 function traverseResults(e, ctx, query, dir, modifiers) {
   e.stopPropagation();
   e.preventDefault();
+
+  // look here...
   if (dir == "prev") {
     findPrev(ctx, query, true, modifiers);
   } else if (dir == "next") {
```

### Screenshot

![](http://g.recordit.co/h5UqzLWdFl.gif)

**Comment by ThomasCrevoisier** [comment]
@jasonLaster Hey ! It's been a while since I looked at the debugger but I get the motivation back to work on it :)
Can I take a look at it this week or is there anyone already working on this issue ?

**Comment by jasonLaster** [comment]
@ThomasCrevoisier welcome back! It's yours.

**Comment by ThomasCrevoisier** [comment]
@jasonLaster Pretty weird bug indeed 🤔 

I don't know if it's related but the bug doesn't occur when the highlight in the tree view doesn't need to update.
When the tree is completely expanded, if navigate to another tab I loose the focus on the search bar. 

I didn't quite get how everything is wired yet, maybe others have a more clearer idea of what's going on :)

**Comment by arthur801031** [comment]
Hi @ThomasCrevoisier  @jasonLaster 

I did some investigation. It seems when the target files in `Sources` are revealed and you switch between tabs and you hit enter, the focus would not be on the search bar.

Here is a GIF that shows the target files are **NOT** revealed in `Sources` and the search behavior is correct:
![normal](https://cloud.githubusercontent.com/assets/4562118/23055564/8052425a-f521-11e6-8b8e-501532a5470f.gif)

Here is a GIF that shows the target files **ARE** revealed in `Sources` and the search behavior is **INCORRECT** due to lost of focus on the search bar when you hit enter:
![error](https://cloud.githubusercontent.com/assets/4562118/23055589/a0c479cc-f521-11e6-9ec1-51889fd244c1.gif)

Here is a GIF that shows the target files **ARE** revealed in `Sources` and the search behavior is **CORRECT** because when I switch between tabs, I click on the search bar to regain focus.
![qxcyyebg6x](https://cloud.githubusercontent.com/assets/4562118/23055620/c6b14e76-f521-11e6-879a-51829b9a2409.gif)

**Comment by jasonLaster** [comment]
@ThomasCrevoisier i'm taking your name off it because it's been some time. Feel free to reclaim it if you can jump on this soon

**Comment by ThomasCrevoisier** [comment]
@jasonLaster Yes of course. I'm stuck and don't really know what causes the bug...

**Comment by jasonLaster** [comment]
@ThomasCrevoisier  pinged you on slack. happy to unstick you

**Comment by ThomasCrevoisier** [comment]
It seems that I can't reproduce it since I pulled `master`

**Comment by jasonLaster** [comment]
closing as it looks fixed on master.

@arthur801031 mind trying to reproduce it?

**Comment by wldcordeiro** [comment]
I guess this was fixed accidentally? 🤷‍♂️

**Comment by arthur801031** [comment]
@jasonLaster 

I couldn't reproduce it. It's fixed :)
