### ISSUE TITLE
Hot reloading does not work

### ISSUE THREAD

**Issue by irfanhudda** [devtools-html/debugger.html#2051]
Running `yarn start` with `"hotReloading": true` gives error

```
ERROR in ./~/devtools-launchpad/src/utils/assert.js
Module not found: Error: Cannot resolve module 'react/lib/ReactUMDEntry/lib/ReactMount' in /home/mycomp/Projects/debugger.html/node_modules/devtools-launchpad/src/utils
 @ ./~/devtools-launchpad/src/utils/assert.js 1:316-347
```

After setting `"hotReloading": false` it gives no errors.

**Comment by wldcordeiro** [comment]
Googling said error points to our version of `react-hot-loader` being too old.

https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-launchpad/package.json#L78

I think we need to use the latest 3.0.0 beta to get hot loading working with React 15+

Also since the work would be done in launchpad, reopening issue on devtools-core may be better @irfanhudda

**Comment by wldcordeiro** [comment]
Opened https://github.com/devtools-html/devtools-core/issues/195

**Comment by irfanhudda** [comment]
@wldcordeiro Thanks for opening that issue.
