### ISSUE TITLE
[tests] fix unit tests when workers are not pre-built

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2427]
When we switched to **jest** we stopped building our workers on the fly. This is actually a somewhat difficult problem to solve because jest's setup script is synchronous and I'm pretty sure webpack is async only. 

Either way, I think the better solution is to avoid building the workers and instead better leverage jest's awesome babel transform integration to instead point the require to the worker entry file. There are several benefits to this approach:

1. it is faster to not pre-build the files
2. it is easier to debug because you don't need to find the worker artifacts and the errors are not in a massive build

I've started this work and it is coming together nicely in this branch:
https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:jest-workers?expand=1

We should also make sure we really get an exit code 1 when it fails.

Lastly, using Jest has been great. One thing I underestimated was the value of unit testing our components. Previously we had ignored this because we didn't have jsdom integration, but now I think we'll see some really nice tests written in this style. Another great win is spying. Previously, we could have pulled in sinon, but I think jest takes that to the next level, so really happy to write some more unit tests.

**Comment by shlomif** [comment]
Hi!

I subscribed myself to this issue because I'm affected by it - in the closed-as-duplicate #2381 bug. Is there an easy workaround for now?

**Comment by wldcordeiro** [comment]
@shlomif there's a PR that should be merged soon that fixes the issue.

**Comment by shlomif** [comment]
Hi,

On Fri, 24 Mar 2017 03:06:13 -0700
Wellington Cordeiro <notifications@github.com> wrote:

> @shlomif there's a PR that should be merged soon that fixes the issue. 
> 

thanks for the update! Can you give me a link to that PR?

Regards,

	Shlomi Fish

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Emma Watson Factoids - http://shlom.in/emwatson-facts

I often wonder why I hang out with so many people who are so pedantic. And
then I remember — because they are so pedantic.
    — an Israeli Perl Monger

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by jasonLaster** [comment]
Fixed in #2431
