### ISSUE TITLE
Suggesting to collapse JavaScript functions while viewing code in Debugger

### ISSUE THREAD

**Issue by tommai78101** [devtools-html/debugger.html#2465]
Currently in the Debugger, there are no methods of collapsing JavaScript functions. Viewing the whole source code is somewhat useful, but it would be nice if we can view a subsection of the whole source code by hiding uninteresting codes and only focusing on certain codes.

I looked forward to see this staying persistent as we reload the add-ons while keeping some functions hidden away / collapsed when debugging code.

Thanks.

**Comment by wldcordeiro** [comment]
So if I'm not mistaken you're asking for code collapsing like in Sublime/Atom/etc where you can collapse blocks of code (usually by clicking on an indicator in the gutter.)

Like this?

![collapse-code](https://cloud.githubusercontent.com/assets/580982/24378934/097cb4ae-1302-11e7-8ed3-b4d2b45a25e4.gif)

**Comment by tommai78101** [comment]
Correct. The codes should be collapsable in the Debugger.

**Comment by jasonLaster** [comment]
Thanks @tommai78101, we can do code folding!

I think persisting the collapse state would be difficult at the moment, because we can't assume the code is the same... but soon, we'd like to to try to do more things around using the AST to persist breakpoint locations and folding would work too. So instead of saying fold line 12, you'd persist the "fold function foo" state.

**Comment by jasonLaster** [comment]
Closing this as we started work on code folding and will have some smaller issues to track the work
