### ISSUE TITLE
Use shared components from m-c

### ISSUE THREAD

**Issue by nt1m** [devtools-html/debugger.html#2559]
Some components to use:
- Tabbar and Tab component (devtools/client/shared/components/tabs) instead of Tabs.js
- Tree (devtools/client/shared/components/tree) instead of SourceTree.js
- HTMLTooltip (devtools/client/shared/widgets/tooltip/HTMLTooltip) instead of Popover.js
- Menu (devtools/client/framework/menu) instead of menu.js

This way, we can have more consistency across all devtools. debugger-html menus will be able to benefit from the native menu. By doing this work, the HTMLTooltip and Menu components will also become more suitable for web browser use.

**Comment by nt1m** [comment]
So, debugger-html does use the menu component in some places, but https://github.com/devtools-html/debugger.html/blob/master/src/components/shared/Dropdown.js still doesn't use the menu component.

**Comment by jasonLaster** [comment]
Thanks for filing @nt1m. 

This conversation would probably be better in IRC or [slack](https://devtools-html-slack.herokuapp.com) where we can discuss individual components: 

* Menu - is shared in [modules](https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-modules/client/framework/menu.js#L1). I think dropdown is a different enough UI that we would not want to use the context menu.
* Tree - is shared in [modules](https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-modules/client/shared/components/tree.js#L1) 
* HTMLTooltip is a component I'm not sure if we want to share at the moment. It is not React, which is important.
* Tabs - are now in [modules](https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-modules/client/shared/components/tabs/tabbar.js#L1) so that the netmonitor can use them. I'm not sure if we would want to use the Tab bar, but our UI for the editor is very complex so I would expect this to be a decent amount of work.

I'm interested in working on a set of shared components, but I think we should figure this out on a case by case basis.

One example of a component that we'd like to share is the Splitter, which is now in it's own package so it can be well maintained.

We are using storybook here to work on it in isolation and would like to have additional examples and testing as well.

https://github.com/devtools-html/devtools-core/tree/master/packages/devtools-splitter
