### ISSUE TITLE
[SearchBar] Polish search buttons

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2589]
@wldcordeiro and @nadavoran in #2463 helped land search navigation buttons behind a flag recently.

It'd be nice to be able to polish them and turn them.

Here are some todo items:

- [ ] use the cursor pointer
- [ ] add a hover tooltip 
- [ ] add a hover background similar to the command buttons like step in

### GIF search:
text search:
![](http://g.recordit.co/TxpEP2eZ8o.gif)

function  search:
![](http://g.recordit.co/aj7ISDGG7L.gif)

cc @bwinton

**Comment by adamki** [comment]
Would love to give this a go. I spent a bit playing around with the possibility of changing the `renderNav()` from returning  `dom.div`'s to `dom.button`'s so that I can follow the pattern set in the [commandBar component](https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/CommandBar.js#L84-L97)

This would set up the buttons for the mentioned requirements as well as up/down arrow scrolling.  I _just now_ started looking at this repo. So please correct me if this approach is not worth looking into.

**Comment by AnshulMalik** [comment]
Yes @adamki , you are going in right direction.
