### ISSUE TITLE
How can we make the debugger more obvious that it's paused, where it's paused?

### ISSUE THREAD

**Issue by helenvholmes** [devtools-html/debugger.html#261]
A meta discussion to capture some ideas for how we might help ground the user inside the debugger, where users are often concentrating on doing steps in a UI to trigger actions in a different one—inevitably creating need for some strong visual indicators as to where things are moving and changing in that second UI.

I have two ideas for how we might ground users when they switch attention back to the debugger:

1. **Copy the flashing pattern in the Inspector for changed elements.** We could flash a darker green of the current paused, background color.
![flash](https://cloud.githubusercontent.com/assets/1720093/16113366/d3dbb8be-33b3-11e6-8454-1ec624762c68.gif)

2. **We could scroll to line.** Paused line could move to be ~15, 20% from the top of the editor, or wherever we determine is a good comfortable point to be reading code in the editor.

3. **Some combination of both.** All the things~~ 💥

James, Jason, do either of you have thoughts about either of these as good/bad ideas?

**Comment by jasonLaster** [comment]
I like both. 

We've discussed a flash in the past and agreed it would help. 

Im not a big fan of green. Is it just me? It doesn't seem consistent with our colors. 

Could we also add a gutter marker like a triangle on the right?

**Comment by jasonLaster** [comment]
Meta but keep the design issues coming @helenvholmes!

**Comment by helenvholmes** [comment]
<img width="755" alt="screen shot 2016-06-17 at 8 39 51 am" src="https://cloud.githubusercontent.com/assets/1720093/16143815/1b662f1c-3467-11e6-8cfd-c9f8c39a90eb.png">

Current design, just to be able to talk about them

**Comment by jlongster** [comment]
I'm not in love with the green either. We need something to stand out, so that's probably why it's a different color.

I like the idea of flashing, but we also need to remember the use case of someone stepping through code quickly. I think the current design works well for that: it's quick and simple. Any flashing/scrolling would be jarring it stepping through code intentionally. And there's no clear disambiguation between stepping quickly through code and the "initial pause".

I think a simple improvement could just be better highlighting of the pause line. Maybe a better color, and make it stronger with a border or something. Is there any other part the UI we could say "paused" with a bright color or something? That would drive it home too.

**Comment by jasonLaster** [comment]
Yea, I agree that highlighting the pause line is the main thing. Would a badge on the right help?

**Comment by clarkbw** [comment]
I would separate out the initial pause and the paused / stepping through code as two different stories.

For the initial pause story I think we want to tell people the what, where, why story.  That might mean that we flash (though I think the inspector flash is a little too contrasty) the break point in the break point list and then the line in the code mirror page.  To me that would mean, "this breakpoint, at this line of code in this file".

Then for the paused state and stepping I think we want to make sure people know that they are paused and why (where the breakpoint is).  But because people are more closely watching the interface at this moment we don't want to be flashing the whole lines anymore.  More likely I think we want to subtly tell the story of the motion of the steps, i.e. when the pause state moves from one line or file to another it shouldn't feel jarring.  Also I think this story starts to expand when try to explain to people how the variables are changing as you step through; both in the variables view as well as something more inline like Chrome is doing.

**Comment by helenvholmes** [comment]
I think Bryan's put it well that there are two stories here.

Is it possible to separate out initial pause and subsequent pauses? If such, we might design differently for each use case.

**Comment by jasonLaster** [comment]
I believe we could do it. I'd like to see what you design in each scenario

**Comment by clarkbw** [comment]
I'm going to break this out into two different issues.
