### ISSUE TITLE
Test our Components! 🤡

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2630]
@AnshulMalik helped us add our first component test for the [CloseButton](https://github.com/devtools-html/debugger.html/pull/2628) recently. We'd love to add additional tests for some of our components

Component Checklist:

- [x] closeButton
- [x] ObjectInspector
- [x] previewFunction
- [ ] SecondaryPanes/Breakpoints
- [x] SecondaryPanes/Frames
- [ ] SourcesTree
- [x] ResultList
- [x] Outline

Chores:

- [x] Fix `InlineSvg` expected `string` warning

**Comment by mbarzeev** [comment]
I'm gonna give it a go - starting with the previewFunction

**Comment by AnshulMalik** [comment]
I'll do ResultList

**Comment by andreicristianpetcu** [comment]
I will do a test for Outline.

**Comment by jasonLaster** [comment]
Great!

**Comment by andreicristianpetcu** [comment]
I got stuck with [my unit test](https://github.com/andreicristianpetcu/debugger.html/blob/d982d2c3b2e6c8168815353a174f4290ea9229d0/src/components/tests/Outline.js#L37-L44) :( maybe somebody can help me out.
The Outline generates a list of functions and variables when the [symbolDeclarations](https://github.com/andreicristianpetcu/debugger.html/blob/d982d2c3b2e6c8168815353a174f4290ea9229d0/src/components/Outline.js#L23-L62) property changes. It basically ends up being a `<div class="outline"><ul><li>my_example_function</li></ul></div>` at least this is what happens in the browser when I dbeug.

The problem is that in my unit test it happens differently. When I call [component.html()](https://github.com/andreicristianpetcu/debugger.html/blob/d982d2c3b2e6c8168815353a174f4290ea9229d0/src/components/tests/Outline.js#L42) I only get `<div class="outline"><ul></ul></div>` without any `li` with my_example_function.

What am I doing wrong? The function ends up in [renderFunction](https://github.com/andreicristianpetcu/debugger.html/blob/d982d2c3b2e6c8168815353a174f4290ea9229d0/src/components/Outline.js#L41) but not in the final HTML.

**Comment by jasonLaster** [comment]
Hmm - I just made a branch which has a slightly different approach, but similar outcome (no symbols). It uses patterns found in other tests

https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:outline-test?expand=1

**Comment by andreicristianpetcu** [comment]
@jasonLaster I think your test has the same issue as mine: if I break the functionalitty, it still passes.

For example if I make [renderFunctions](https://github.com/jasonLaster/debugger.html/blob/ac8a938cbe54c95ffe3bee5fe89ed77be634f13e/src/components/Outline.js#L51-L53)  so that it returns null, the test still passes.

```javascript
  renderFunctions() {
    const { symbolDeclarations } = this.state;
    if (!symbolDeclarations) {
      return;
    }

    const { functions } = symbolDeclarations;

    // return functions
    // .filter(func => func.value != "anonymous")
    // .map(this.renderFunction);
    return null;
  }
```
A test that always passes is not usefull.

The code generates a [`li` inside the `ul`](https://github.com/jasonLaster/debugger.html/blob/ac8a938cbe54c95ffe3bee5fe89ed77be634f13e/src/components/Outline.js#L39-L41) but both my test and yours never check for the [`li`](https://github.com/jasonLaster/debugger.html/blob/ac8a938cbe54c95ffe3bee5fe89ed77be634f13e/src/components/tests/__snapshots__/Outline.js.snap#L11-L15). It seems like the [resultList test does a similar check](https://github.com/jasonLaster/debugger.html/blob/ac8a938cbe54c95ffe3bee5fe89ed77be634f13e/src/components/tests/__snapshots__/resultList.js.snap#L11-L46). I will try to see why it works and mine does not.

In my test I mocked the parser in order to force it to be sync and not async. I have an issue in my test and I wanted to rule out the async stuff. I will set it back as it was once I fix the issue.

**Comment by adamki** [comment]
I'm going to take a look at sourcesTree later today.

**Comment by jasonLaster** [comment]
Great!

**Comment by jasonLaster** [comment]
We now have a lot more tests and i feel like we have the patterns we need to move forward
