### ISSUE TITLE
[Console] Debugger fails to output error messages when referencing an undefined object from IDBRequest

### ISSUE THREAD

**Issue by tommai78101** [devtools-html/debugger.html#2711]
Here's a GIF of what's going on.

![gif](https://cloud.githubusercontent.com/assets/6444116/25295419/63cee22a-26b1-11e7-8d4d-8e86d4e9add3.gif)

```
console.log("(shoptoolbar.js) Executing a then().");
promise.then(function(retailer) {
	console.log("(shoptoolbar.js) Inside the then().  <------------");
	if (retailer instanceof IDBRequest) {
		console.log("(shoptoolbar.js) Swapping the result 1.");
		console.log(retailer.result);  //<--------   Just move this line up/down to trigger the error
		console.log(retailer);
		retailer = retailer.result;
		console.log(retailer);
		console.log("(shoptoolbar.js) Swapping the result 2.");
	}
	else {
		console.log("(shoptoolbar.js) EXCEPTION <------------------------.");
	}
});
```

Unfortunately, I am using a proprietary codebase, so I cannot share any codes. 

I should be expecting an error message, but I see nothing. And this is without any filters applied whatsoever.

**Comment by nchevobbe** [comment]
Hey @tommai78101 , first, I will close this here, since it's not an issue with the debugger, but with the console, which are not in github at the moment.

I have a hard time understanding what you want to do and what is wrong, please, be as specific and detailed as you can when filing bugs so we can fact on them faster.

Now, I think I get it, you think your code is supposed to throw an error, but you don't see it in the console.
Now, can you try this : 
```js
console.log("(shoptoolbar.js) Executing a then().");
promise.then(function(retailer) {
	console.log("(shoptoolbar.js) Inside the then().  <------------");
	if (retailer instanceof IDBRequest) {
		console.log("(shoptoolbar.js) Swapping the result 1.");
		console.log(retailer.result);  //<--------   Just move this line up/down to trigger the error
		console.log(retailer);
		retailer = retailer.result;
		console.log(retailer);
		console.log("(shoptoolbar.js) Swapping the result 2.");
	}
	else {
		console.log("(shoptoolbar.js) EXCEPTION <------------------------.");
	}
}).catch(e => console.warn(e));
```
I guess this should show you the error you expect.
See the warning in https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Promise#then() which explains what is going on.

You could use https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunhandledrejection to log all you unhandled rejection in Promise callback to prevent such things to happen.

**Comment by tommai78101** [comment]
Thanks, and sorry for being too hasty (train leaves a bit early due to rush hour).

I will take a look at it, and see what I can do with my local codebase.
