### ISSUE TITLE
Startup bad performance on pages with lots of scripts

### ISSUE THREAD

**Issue by fflorent** [devtools-html/debugger.html#2727]
Hi there,

I noticed a big performance degradation on the devtools when I have to debug the javascript of my application. After investigating a bit (using the Browser Devtools), it appears that the main point of that slowness comes from the fact there are lots of scripts that are fetched, and the `getSourceByUrl` is called several times. And indeed, my application in development mode runs lots of JS files.

You may reproduce the issue with the following steps:
1. Open the attached [index.html.zip](https://github.com/devtools-html/debugger.html/files/954912/index.html.zip) and unzip it
2. Open the devtools, switch to the Debugger tab
   → it takes a long time (~30sec) to display those simple (but numerous) scripts

Don't hesitate to ask me questions.

Cheers,
Florent

**Comment by asolove** [comment]
This is a pretty standard render/layout thrashing issue. `Editor` and all the other components are currently re-rendered every time any data changes in the store, even if it isn't data they rely on. `Editor` is particularly expensive because every time it updates, it calls methods on the underlying code editor, which does some DOM measurement and manipulation causing layout thrashing. Doing that 500 times in a row adds up to about 10s on my machine.

I can make that problem mostly better by just not calling the underlying editor if the source text hasn't changed. But there are lots of other components also being re-rendered that still leave this taking about 3s. I think the right solution is for all components that are wrapped in `Connect` calls to become `PureComponent`s so they don't update unless their props actually change.

**Comment by fflorent** [comment]
From what I investigated, that's not such an editor issue (which is not even rendered).
But while profiling the test case above at home, I couldn't get the same performance degradation (it takes "only" ~5 seconds) and the result of the profiling are not the same. 

The main difference between the two computers (the one at home and the one at work) is that I use a SSD at home. I need more investigation from my side I guess.

Florent

**Comment by asolove** [comment]
Yeah, the silly part is the editor component isn't even rendering anything interesting. But it is constantly sending the CodeMirror editor a command to show nothing, and CodeMirror is spending a lot of time recalculating some layout stuff about how it's showing nothing, and the whole thing is just ridiculous.

**Comment by fflorent** [comment]
Ouch. Do you want me to export the profiling for the example I produced in my first post?

Florent

**Comment by jasonLaster** [comment]
Thanks @florent. That would be great.

I just got off the phone with @asolve and we investigated adding `reselect`, which would help us avoid unnecessary component re-renders by memoizing selectors.

[here] is an incomplete POC.

We would like to address several of the components that currently have "ugly" `shouldComponentUpdate` calls:

- [ ] Frames
- [ ] Breakpoints
- [ ] Scopes
- [ ] Expressions 

As well as fix other components that are aggressively re-rendering:

- [ ] Editor
- [ ] Tabs
...


[here]: https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:reselect2?expand=1

**Comment by asolove** [comment]
As Jason said, [work has started](https://github.com/devtools-html/debugger.html/compare/master...asolove:reselect2?expand=1#diff) on using reselect to memoize the data needed by components and avoid re-rendering them when possible.

Unfortunately, that work is not going to totally fix this problem. Even after removing all the other component re-renders, I still end up with about three seconds where the browser is totally unresponsive to events. There are two culprits:

- Rendering the source list itself is expensive simply because of the number of renders and DOM changes needed for all 500 elements.
- If you're a developer, that rendering also causes the React DevTools to spin for quite a while to serialize/deserialize all the info about the 500 components to display them in DevTools. (This is why the interface is much slower when you go to profile it! That confused me for a while.)

The solution to both problems would be using an approach like a virtual tree where we only render the children that actually fit in the visible area of the screen. I tried tracking down the `Tree` component, but it's in a separate package so not sure if that's possible. Also not sure if this specific case is worth optimizing for. I think in _most_ real-life apps, you'd have fewer files in each folder, and more folders dividing them up, so it wouldn't be this big a problem. But there definitely will be cases where virtual tree will be much faster.

**Comment by jasonLaster** [comment]
- [ ] an additional component

* maybe some additional optimizations
* maybe some flow typing

**Comment by jasonLaster** [comment]
great work @asolove!
