### ISSUE TITLE
[Tabs] Flashing border

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2840]
I've notice a pretty weird phenomenon with our tabs recently. The selected tab border flashes on refresh. For what it's worth it looks like a lot of the UI is not styled when there is an error in the app.

Perhaps this is a development only issue with how react applies styles or loads styles?

![](http://g.recordit.co/pebBIbQCO1.gif)

**Comment by diessica** [comment]
It seems like this bug is Firefox-only.

**Comment by jasonLaster** [comment]
I see it in chrome too. For what it's worth, it is somewhat intermittent. Like sometimes it's too fast

**Comment by diessica** [comment]
Ok, I've looked into it.  In Chrome, it flashes really fast, as you said. In Firefox is more weird and evident, because it shows a black border until it gets `--theme-splitter-color` value, apparently.

Chrome (current, with bug):

![mgfj8b3kyfvrggi_qv2c0ct-vlm-8lq05yoyrlypdlnc4yzodlgikncsmbtqskr3qw8onupezh-c4qka3xfsolnlsmh0egfbdyhze6lvomai4av1wcwksmudutgzhrrg](https://cloud.githubusercontent.com/assets/5303585/25783917/95337ce6-333a-11e7-81f6-d6e085e74e37.gif)

It seems related to the fact that the `active` class takes a bit to apply, so it flashes when it does, which end up definitely not easy to the eyes. Even worse in Firefox, because of the black border.

In `renderTabs()`, we could prevent rendering of source tabs until we get `selectedSource`. If there isn't a `selectedSource` already, tabs won't render. What do you think? Does it make sense to you?

Chrome (result from solution above):
![u6odktgvg54e2mg6puo6ouf2mc1dhi8f0enkwtjxxs63vuippmlgkhhn7v8bv9qq6jib0i3xjxr1gp7kb-pxqvnlsmh0egfbdyhze6lvomai4av1wcwksmudutgzhrrg](https://cloud.githubusercontent.com/assets/5303585/25784624/fbe08694-3346-11e7-9c7a-0c84be0858ea.gif)

**Comment by diessica** [comment]
@jasonLaster Any thoughts?

Sorry for the ping, but I'm not sure if you've seen my comment. Waiting for your review to commit! :)

**Comment by jasonLaster** [comment]
@diessica thanks for the re-ping. I am hesitant to do that because sometimes we won't have a selected source, when the debugger reloads. Can we fix this with CSS?

**Comment by jasonLaster** [comment]
For fun, here's what it looks like when paused on the initial render :)

<img src='https://shipusercontent.com/77f21d4608e6583df724398b4775c662/Screen%20Shot%202017-05-10%20at%203.03.43%20PM.png' title='Screen Shot 2017-05-10 at 3.03.43 PM.png' width=1552>

**Comment by jasonLaster** [comment]
Hey @diessica re-pinging. Sorry for dropping the ball

**Comment by codehag** [comment]
I am doing some research -- it is strange that we are inheriting our styles from the editor.

**Comment by wldcordeiro** [comment]
Closing. This will be fixed fully once we bump launchpad.
