### ISSUE TITLE
[Preview] Can't preview variables from outer scope when hitting breakpoint a 2nd time

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#2956]
![debugger_bug](https://cloud.githubusercontent.com/assets/1141550/26221719/ca81aee6-3c17-11e7-92df-b913cd58e390.gif)

STRs: (see gif or read below)
1. Load the HTML page below
2. Add breakpoint on `arr.push(i++);`
3. When paused, hover on `var arr`, you should be able to preview the array correctly with a few numbers inside
4. Resume and wait for pause
5. When paused, hover on `var arr` again, the array preview has the correct length, but can no longer be expanded.

Note that you have the same behavior when using the scopes panel. Adding a watch expression on `arr` works fine though.
 
```html
<!DOCTYPE html>
<html>
<head>
  <title>test scopes</title>
</head>
<body>
<script type="text/javascript">
  (function () {
    var arr = [];
    var i = 0;
    (function () {
      window.setInterval(function () {
        arr.push(i++);
        // set a breakpoint here, wait for break
        // hover on arr in the upper scope (or check it in scopes pane)
        // => should see the content of the array
        // resume, wait for break
        // hover on arr in the upper scope (or check it in scopes pane)
        // shows the length but can't expand the values
      }, 1000);
    })();
  })();
</script>
</body>
</html>
```

**Comment by jasonLaster** [comment]
Thanks for the clear STR. 

This is actually a bug for the old debugger as well. It's less clear when you're testing because Preview works fine, but the scope tree does not.

**Comment by jasonLaster** [comment]
I just looked into it with the help of @bomsy and @Anshul and we found that binding variables from outer scopes are not re-created on subsequent steps. 

In terms of steps:
- script actor calls [`_paused`][pas] to create a pause packet
- script actor calls [`_createFrameActor`][fas], 
  - which subsequently creates an environment actor, 
  - which [creates actors][bis] for each binding
  - this calls [`objectGrip`][og] which has the bug.

The bug is that `objectGrip` believes that the actor is registered because `pool.objectActors` has the value. Unfortunately, for some reason the pool does not have the actor. 

The interesting thing is that `objectGrip` is a weak map so the actor must be retained somewhere. The next step is to find the retaining path and see if we can safely remove it.


[oas]:https://github.com/mozilla/gecko-dev/blob/master/devtools/server/actors/script.js#L1698-L1700
[pas]:https://github.com/mozilla/gecko-dev/blob/master/devtools/server/actors/script.js#L705-L706
[fas]:https://github.com/mozilla/gecko-dev/blob/master/devtools/server/actors/script.js#L1629-L1640
[bis]:https://github.com/mozilla/gecko-dev/blob/master/devtools/server/actors/environment.js#L145-L149
[og]:https://github.com/mozilla/gecko-dev/blob/master/devtools/server/actors/script.js#L1698-L1701

**Comment by jasonLaster** [comment]
Here's the bug in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1367052
