### ISSUE TITLE
If you’re paused at a breakpoint and try to declare something in the “Console” panel, it doesn’t work.

### ISSUE THREAD

**Issue by vladikoff** [devtools-html/debugger.html#3074]
If you’re paused at a breakpoint and try to declare something in the “Console” panel, it doesn’t work.

![image](https://cloud.githubusercontent.com/assets/128755/26747119/befc393c-47c1-11e7-99da-3104247500aa.png)

(This is from a series of bugs reported by Firefox teams, I'm making sure we file all of those. Please close if dup)

**Comment by jimblandy** [comment]
Curious: if you change the example to use `var` instead of `let`, does it work?

SpiderMonkey itself does have the ability to inject these declarations into the frame. The Debugger.Frame.prototype.eval function is specified to inject them in non-strict code:

> If <i>code</i> is not strict mode code, then variable declarations in <i>code</i> affect the environment of this frame. (In the terms used by the ECMAScript specification, the `VariableEnvironment` of the execution context for the eval code is the `VariableEnvironment` of the execution context that this frame represents.) If implementation restrictions prevent SpiderMonkey from extending this frame's environment as requested, this call throws an Error exception.

The reason strict mode code is treated differently is that `eval` was meant to behave like an actual `eval` call placed in the code. In strict mode, eval cannot affect its caller's environment. And in fact, a `let` in an eval (shown in the screen shot) never affects its caller's environment, strict mode or not.

However, it may be the case that, for developer tools, the old, non-strict, invasive behavior is what's always wanted, even in strict mode code, and even for `let`. I *think* this can be implemented.

**Comment by jasonLaster** [comment]
Thanks for the overview. Out of curiosity, what do you think it would take?

**Comment by jimblandy** [comment]
Probably changes to [DebuggerGenericEval].

[DebuggerGenericEval]: http://searchfox.org/mozilla-central/rev/d441cb24482c2e5448accaf07379445059937080/js/src/vm/Debugger.cpp#8176-8264

**Comment by jasonLaster** [comment]
reposting in the console component: https://bugzilla.mozilla.org/show_bug.cgi?id=1375300
