### ISSUE TITLE
[flow] switch action types to exact object types

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3080]
We currently type our actions, but it would be nice to use exact object types as it will catch additional cases especially when we use the PROMISE middleware.

Here's a rough [sketch](https://gist.github.com/7530eb2fed2d67ccadce4e6d3979faf9) of what the diff would look like. After this, it's just a question of making flow happy :)

[types]:https://flow.org/en/docs/types/objects/#toc-exact-object-types

**Comment by sejoker** [comment]
@jasonLaster I think I can tackle it.

**Comment by jasonLaster** [comment]
@sejoker that'd be great. It might be nice to start slow. Like convert once action at a time or an action type like source actions

**Comment by jasonLaster** [comment]
@sejoker are you available to take a stab at breaking this down into smaller pieces?

**Comment by wldcordeiro** [comment]
I think exact types with covariant properties will be even better.

```js
type MyAction = {|
  +id: string,
  +value: number,
|}
```

This will reflect that our Redux states are immutable. https://flow.org/en/docs/react/redux/#toc-typing-redux-state-immutability

**Comment by jasonLaster** [comment]
Yeah

**Comment by jasonLaster** [comment]
Hey @sejoker, @wldcordeiro  any interest in picking this up and landing a couple of these refactors? It'd be nice land a couple to get a precedent in here.

**Comment by ryanjduffy** [comment]
I took a cut at this and wanted to get some feedback before pursuing further. Specifically, I added a generic type for the promise middleware to attempt to handle the various structs that are valid for each action state (new, start, error, and done).

Here's the generic:

https://github.com/ryanjduffy/debugger.html/blob/f271f4eb667d52a8fae6594c06d6b33debd0030a/src/actions/utils/middleware/promise.js#L12-L41

And an example of usage:

https://github.com/ryanjduffy/debugger.html/blob/f271f4eb667d52a8fae6594c06d6b33debd0030a/src/actions/types.js#L93-L100

One disadvantage is that you have to guard access to some members because Flow can't seem to sort out that they are valid. For example, any time you need to get at the `value` of an action, you either have to check for existence (`if (action.value)`) or forcibly cast it.

https://github.com/ryanjduffy/debugger.html/blob/f271f4eb667d52a8fae6594c06d6b33debd0030a/src/reducers/pending-breakpoints.js#L94

I haven't mark the props as covariant yet so that still outstanding work.

Thoughts?

**Comment by jasonLaster** [comment]
Oh interesting, i didn't realize we could use splatting like this. 

This looks good

**Comment by ryanjduffy** [comment]
Attaching a PR ^^^ with the proposed changes for breakpoint and ast actions to get the ball rolling.

**Comment by ryanjduffy** [comment]
Part 2 ^^^ with the remaining actions + some refactoring to fix timeout issues
