### ISSUE TITLE
[flow] Reduce the number of ANYs

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3156]
We've allowed the number of ANYs to grow fairly large and that reduces our coverage considerably.

There are some easy places to remove ANYs:
1. replace ANY return types with `void` when we know it's the case
2. add flow types that we already have. We now have lots of types we didn't have before...
3. add some easy types :)

We currently have 281 **any** types in **10** files. You can get this count by searching for `any` in the project or `: any`

**Comment by zaggy** [comment]
Hi, I can take this. It will also help me figure out the code base more.

**Comment by jasonLaster** [comment]
That'd be great. Thanks for the flow bump!

**Comment by zacck** [comment]
How's this going any extra hands needed here?

**Comment by jasonLaster** [comment]
@zacck would love the help!

**Comment by zacck** [comment]
Hey guys! So trying to work on this, But I am currently running into a small problem. 
I am currently having such a difficulty setting the types for the `any`s due to lack of information of what they are intended to be, What would be the best solution for this? Would it be to track down authors and ask them?

I am currently working on the `any` declarations in the actions folder. And for the ones that I have tried in  

 - ast.js 
 - event-listeners.js
 - pause.js 

I can't seem to find information on what the anys are supposed to be.

**Comment by maniator** [comment]
Related to #3172

**Comment by jasonLaster** [comment]
closing as it's not focused
