### ISSUE TITLE
[CallStack] [Breakpoints]  Handling long script names in the callstack panels

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#3259]
Some small UI nits.

In the call stack component, it would be nice to give more weight to the function name than to the script name. In the case highlighted in the screenshot, the script name is pretty long, forcing the function name to be almost totally hidden. 

<img width="315" alt="image" src="https://user-images.githubusercontent.com/1141550/27833520-7aa67628-60d3-11e7-89ce-c1f492020697.png">

Maybe use a more generous minimum width for the function name.

Probably unrelated, but in the breakpoints section, the script name shows an ellipsis even though there is enough space available to display it entirely.

**Comment by bomsy** [comment]
We could do a couple of things that might help
1) I think we should remove everything after the script extension i.e `piskel-animated-preview.js` rather than `piskel-animated-preview.js?20170502`

2) Also we could break the scriptname and line number to a new line as chrome does

![image](https://user-images.githubusercontent.com/792924/27839310-2e446dfc-60e8-11e7-8e47-0d5ce862cada.png)

**Comment by codehag** [comment]
we now only show the script name in the breakpoints, so this only applies to the callstack

**Comment by codehag** [comment]
this is related to https://github.com/devtools-html/debugger.html/issues/3215 so i am closing this one
