### ISSUE TITLE
[Parser] Parse Failed on "application/ld+json" SCRIPT

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3307]
Many WordPress sites (mine included) will have script tags that look like this:

```
<script type='application/ld+json'>{"@context":"http:\/\/schema.org","@type":"Person","url":"https:\/\/davidwalsh.name\/","sameAs":["https:\/\/www.facebook.com\/davidwalshblog","https:\/\/plus.google.com\/114538814489633467974?rel=author","https:\/\/twitter.com\/davidwalshblog"],"@id":"#person","name":"David Walsh"}</script>
```

Essentially a `script` tag with JSON.  Debugger.html throws the following:

```
ast.js:33 parse failed 
```

I know this type of script is an outlier but I figured it was worth reporting.  Also somewhat curious why a script tag containing only JSON would bomb during parsing.

**Comment by jasonLaster** [comment]
nice find.

@ryanjduffy do you think this is related to `parse-script-tags`?

**Comment by ryanjduffy** [comment]
Likely. I'll look into it

**Comment by ryanjduffy** [comment]
The issue here is that JSON isn't itself valid, stand-alone JavaScript. So when the string is passed to the [debugger.html parser](https://github.com/devtools-html/debugger.html/blob/master/src/utils/parser/utils/ast.js#L23), it fails. It shouldn't inhibit the debugger since the failure only means that particular script will be omitted from the AST for the HTML page.

@darkwing Are you able to debug other scripts on the page?

I could build in more intelligence into `parse-script-tags` to respect the `type` attribute and thereby not try to parse non-JS code but it wouldn't prevent that error from printing when a script tag contained otherwise invalid JS. Provided debugging works well otherwise, a simpler solution might be to either make the warning more descriptive or suppress the warning altogether in this scenario.

**Comment by codehag** [comment]
@ryanjduffy are you still looking into this?

**Comment by jasonLaster** [comment]
:wave: @ryanjduffy, just checking in cause it looks like this issue might have fallen off the radar. If you're busy w/ the parser work, we can take your head off this.

**Comment by jasonLaster** [comment]
Also, you should have an invitation to the community team in your inbox
![screen shot 2017-11-04 at 6 10 26 pm](https://user-images.githubusercontent.com/254562/32409883-821440b6-c18b-11e7-9b0c-b984280b0dd7.png)

**Comment by ryanjduffy** [comment]
I haven't looked at this but I will next week

**Comment by ryanjduffy** [comment]
Published `parse-script-tags@0.1.4` with a fix for ignoring `<script>`s with non-JS types. Need to test with devtools and put together a PR to bump the dependency.

**Comment by ryanjduffy** [comment]
I could repro the warning. It must have been removed somewhere along the way but I didn't look for when. However, the fix does prevent lines within non-JS `<script>`s from showing as breakpoint targets.

<img width="341" alt="image" src="https://user-images.githubusercontent.com/788456/32754780-248c912a-c887-11e7-9604-0c20971db5c5.png">

**Comment by ryanjduffy** [comment]
Fix submitted: https://github.com/devtools-html/debugger.html/pull/4684

**Comment by codehag** [comment]
this change had to be backed out due to a memory leak on linux builds. looks like it is related to a dependancy (didn't see anything that would cause it in the update patch ryanjduffy created for the parse library) https://github.com/devtools-html/debugger.html/pull/4840

**Comment by wldcordeiro** [comment]
@codehag @jasonLaster from the looks of it the changes are gone? Should this remain open or closed?

**Comment by jasonLaster** [comment]
we should keep it open because we had to revert :/

**Comment by darkwing** [comment]
Due to a change that @jasonLaster made to ease up on strictness of non-JS files, this error no longer occurs.  It doesn't, however, break on the JSON.
