### ISSUE TITLE
Move selectors to the reducer modules

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#339]
The reducers should export the relevant selectors.

The rationale is that the selectors know the shape of the store.

https://github.com/jlongster/debugger.html/commit/ccb58b91c31f83cd8a6ae12c873a30e93a36047f#commitcomment-18251196

**Comment by jlongster** [comment]
https://egghead.io/lessons/javascript-redux-colocating-selectors-with-reducers?course=building-react-applications-with-idiomatic-redux

The only slight annoyance is that we don't use ES6 modules so it's a little harder to export the reducer as the "default" import, but we'll just need to tweak what was pass into `combineReducers`. I played with doing this already (because it was easier to make Flow type a few things) but it got a little awkward with how we import/export stuff.

It's no rush to do this, but reducer tests might encourage us to do this because we can import a reducer module and directly get all the selectors as well. I may look at this next week.

**Comment by jasonLaster** [comment]
that's true. 

I'd be happy to codemod our modules to [es6](https://github.com/nolanlawson/cjs-to-es6). I've been thinking about default exports for some time.

**Comment by jlongster** [comment]
Since I want to write more reducer tests I'm going to look into this.

**Comment by clarkbw** [comment]
Do this as we work on each
