### ISSUE TITLE
[CommandBar] stops being sticky

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3426]
It looks like the command bar can scroll out of view when the debugger is in vertical layout.

We should fix this by making sure the command bar is sticky

```diff
diff --git a/src/components/SecondaryPanes/CommandBar.css b/src/components/SecondaryPanes/CommandBar.css
index bb80587..336c4a8 100644
--- a/src/components/SecondaryPanes/CommandBar.css
+++ b/src/components/SecondaryPanes/CommandBar.css
@@ -4,6 +4,7 @@
   display: flex;
   height: 30px;
   overflow: hidden;
+  /* this should do it...*/
   position: sticky;
   top: 0;
   z-index: 1;
diff --git a/src/components/SecondaryPanes/index.js b/src/components/SecondaryPanes/index.js
index ed7d5a8..956c010 100644
--- a/src/components/SecondaryPanes/index.js
+++ b/src/components/SecondaryPanes/index.js
@@ -219,6 +219,7 @@ class SecondaryPanes extends Component {
       {
         className: "secondary-panes"
       },
+      // we might need to fix something here...
       CommandBar(),
       this.props.horizontal
         ? this.renderHorizontalLayout()
```

![](http://g.recordit.co/GXGY2plgiL.gif)

**Comment by jasonLaster** [comment]
![](http://g.recordit.co/gRe69H1SxU.gif)

**Comment by jasonLaster** [comment]
this is a bad fix https://gist.github.com/97dcee6db4dae1daa098ba5bd24cc466

but demonstrates the problem is w/ long content

**Comment by jasonLaster** [comment]
ah, `height: fit-content` where supported fixes the problem with commandbar. :wink:
http://caniuse.com/#feat=intrinsic-width
`.secondary-panes { height: fit-content; overflow-y: scroll; }`

**Comment by Garbee** [comment]
So, that "patch" I thought over... Leads to broken output. Also, since Sticky is still "in development" as a spec, this particular case *seems* to not be specified. If you check Note 3 in [the sticky spec](https://www.w3.org/TR/css-position-3/#sticky-pos) it reads:

> Say what happens if it already overflows the containing block

I think this is the case we're hitting. Since the height is already "overflowing" the boundary, the engines aren't sure what to do with a sticky node. Gecko is choosing to stick it, what I'd say is correct since that provides the functionality we want. While Blink is choosing to keep the sticky node as a relative item constantly.

So, that work-around is not going to work until we have it specified who is at fault and the other engine fixes it. Still working on another patch though.

However as a note for future reference as well, this can only accurately be tested with a full page refresh cycle. Live editing is triggering different interactions compared to a fresh load in different cases. In both Chrome and FF. It's quirky for sure.

**Comment by codehag** [comment]
i will close this for now as we have a fix. we can revisit if there are issues
