### ISSUE TITLE
[CallStack] Frames filenames include `?:`

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3583]
It would be nice to exclude the special characters like `?` or `:` that generally have special meaning after the file extension.

![redux.png](https://shipusercontent.com/842f560066233ba62dcb98751b0b4a7f/redux.png)

```diff
diff --git a/src/components/SecondaryPanes/Frames/Frame.js b/src/components/SecondaryPanes/Frames/Frame.js
index cf03086..598f08e 100644
--- a/src/components/SecondaryPanes/Frames/Frame.js
+++ b/src/components/SecondaryPanes/Frames/Frame.js
@@ -4,6 +4,8 @@ import classNames from "classnames";
 import Svg from "../../shared/Svg";

 import { formatDisplayName } from "../../../utils/frame";
+
+// => here
 import { getFilename } from "../../../utils/source";
 import FrameMenu from "./FrameMenu";

diff --git a/src/utils/tests/source.js b/src/utils/tests/source.js
index e68bef0..59c1de1 100644
--- a/src/utils/tests/source.js
+++ b/src/utils/tests/source.js
@@ -1,6 +1,7 @@
 import { getFilename, getMode, getSourceLineCount } from "../source.js";

 describe("sources", () => {
+  // we've got tests
   describe("getFilename", () => {
     it("should give us a default of (index)", () => {
       expect(
       ```

**Comment by sharathnarayanph** [comment]
I'd like to take this up.

**Comment by jasonLaster** [comment]
Sorry, I believe Anna is on it

**Comment by jasonLaster** [comment]
we can't reproduce it

**Comment by jasonLaster** [comment]
Here's an STR:

1. go to https://www.piskelapp.com/
2. navigate to `piskel-animated-preview.js`
3. add a breakpoint on line 39 in `startAnimationTimer`

**Comment by Fischer-L** [comment]
Saw the issue. Would like to take this bug.

**Comment by jasonLaster** [comment]
@Fischer-L it's yours!

**Comment by Fischer-L** [comment]
For the "?" found in https://github.com/devtools-html/debugger.html/issues/3583#issuecomment-332556608, it turns out that that is what exactly the source map provides. Log the returned sources for search by `searchResult` in SourceSearch.js [1], could get the source item of "piskel-animated-preview.js?20170502"[2]. In fact, that filename is given by the website on purpose (seems that is timestamp) [3]. However, in the left source list, it seems stripping out the "?20170502" [4].

@jasonLaster 
For developers of that website, seeing "?20170502" in the search results or breakpoint probably would make more sense to them. As for the source list case, not really a problem, maybe acceptable (Chrome respects the website, displaying "?20170502" in all cases).
I would suggest this is not really an issue. How do you think?

[1] https://github.com/devtools-html/debugger.html/blob/b581b67336508b80a0af75eea8f2fc0503c84a4c/src/components/ProjectSearch/SourceSearch.js#L23

[2] { value: "/static/js/piskel-animated-preview.js?20170502", title: "piskel-animated-preview.js?20170502", subtitle: "/static/js/piskel-animated-preview.js?20170502", id: "server1.conn12.child2/source29" }

[3] 
![screen shot 2017-09-28 at 10 10 15 pm](https://user-images.githubusercontent.com/5627487/30971204-dd720916-a499-11e7-94d6-a53ac1ee4e09.png)

[4] 
![screen shot 2017-09-28 at 10 12 21 pm](https://user-images.githubusercontent.com/5627487/30971479-94a9dbae-a49a-11e7-8632-c408463b53fc.png)

**Comment by jasonLaster** [comment]
Thanks @Fischer-L. Lets see how the Tree strips away the `?....` and apply that to Tabs, search results, and the call stack.

My guess is that it's in here: 

https://github.com/abhinav-koppula/debugger.html/blob/issue-4043/src/utils/sources-tree/getURL.js#L27-L31

we'll likely want to re-use the same helper function in all the places...

**Comment by jasonLaster** [comment]
@Fischer-L that's a good point, in practice I've found that it is helpful to shorten the URL in horizontally limited areas and provide the context in other ways, like on hover w/ the tab. 

In this case, I think it would be nice to strip it out because for the most part, the important detail is the filename. We can then work on providing the information in other ways

**Comment by jasonLaster** [comment]
ping @Fischer-L interested?

**Comment by Fischer-L** [comment]
> in practice I've found that it is helpful to shorten the URL in horizontally limited areas  and provide the context in other ways, like on hover w/ the tab.

@jasonLaster right, in the call stack panel the space is limited and function name probably is the main focus during stepping between codes. Will update.

**Comment by Fischer-L** [comment]
@jasonLaster Please see PR #4535
