### ISSUE TITLE
[Breakpoint] UI fails when breakpoint is not found.

### ISSUE THREAD

**Issue by yurydelendik** [devtools-html/debugger.html#4087]
STR:
1. Open Firefox (Nightly) at about:blank
2. Open Debugger
3. Open https://mdn.github.io/webassembly-examples/js-api-examples/
4. Find wasm source and set breakpoint at "call $import0" line
5. Close Debugger/Devtools
6. Refresh the page
7. Open Debugger

Actual result:

No debugger UI
<img width="982" alt="screen shot 2017-09-19 at 8 05 13 am" src="https://user-images.githubusercontent.com/1523410/30593771-553fc59a-9d11-11e7-953f-8e636380cf88.png">

and `Object { from: "server1.conn1.child1/source30", error: "noCodeAtLineColumn", message: "Could not find any entry points to …" }` exception is in the console.

Expected result:

No exception and UI is visible

**Comment by jasonLaster** [comment]
@yurydelendik  is this true for non-wasm sources too, right?

**Comment by yurydelendik** [comment]
> is this true for non-wasm sources too, right?

yes, I think it's true for non-wasm, but it maybe harder to model a test case, e.g. it is a script that became smaller.

**Comment by jasonLaster** [comment]
i see, thanks.

**Comment by lukaszsobek** [comment]
@yurydelendik @jasonLaster 

The issue seems to have evolved:
- gutter loads
- breakpoint is missing in editor, but present in breakpoint panel
- source not selected (there a few issues for that bug already filed)
- interestingly the wasm source looks like it is active, as opposed to regular tabs - those appear inactive

Video:
![wasm-source](https://user-images.githubusercontent.com/23530054/33601414-6ef87324-d9ac-11e7-8351-417392c0b50e.gif)

**Comment by jasonLaster** [comment]
Can you clarify the STR?

**Comment by yurydelendik** [comment]
The issue can be counted as resolved due to "No exception and UI is visible". However now the breakpoint is gone (same STR) -- probable that's what fixed it.

I'll close to reopen different one issue using wasm test case.
