### ISSUE TITLE
Source Tree and Outline show have empty messages aligned

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#4185]
We currently show empty messages for both source tree and outline components, but they are not aligned and have slightly different styles. They should have the same style ( i would suggest using the styles from source tree)

Good beginner bug! I am happy to mentor; If i am not available @nyrosmith is around too, he has some experience with these two components

<img width="252" alt="screen shot 2017-09-27 at 5 38 19 pm" src="https://user-images.githubusercontent.com/26968615/30922961-f7812318-a3aa-11e7-9f10-b8860b762416.png">
<img width="252" alt="screen shot 2017-09-27 at 5 38 25 pm" src="https://user-images.githubusercontent.com/26968615/30922960-f78095a6-a3aa-11e7-8af4-1a768a04ab54.png">

**Comment by umedsondoniyor** [comment]
I would like to solve this issue @codehag

**Comment by codehag** [comment]
@umedsondoniyor all yours!

**Comment by gabrielluong** [comment]
I think it should actually be styled like the Outline panel for consistency with the rest of the developer tools. We currently follow how the Accordion style messages when there is no content in them. We should simply do the same for these sidebar components in the debugger because that is also how we style empty sidebar panels in the Inspector.
