### ISSUE TITLE
[Editor] Show a link to a generated file

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4242]
Follow up from #4192 , I did not see the webpacked files and assumed that source mapping failed.

The inconsistent behavior is that webpacked source are show in their own `Webpack` domain while rollupjs shows source mapped files correctly in the current domain (tested on [rollupjs.org](http://rollupjs.org/)).

The second path seems more obvious, especially as the extra domain can get lost within 3rd party scripts.

**Comment by codehag** [comment]
if i got this right, we should merge webpack scripts in with the main domain?

**Comment by tromey** [comment]
> The inconsistent behavior is that webpacked source are show in their own Webpack domain while rollupjs shows source mapped files correctly in the current domain (tested on rollupjs.org).

FWIW this happens because webpack generally puts all the source text into the source map, and then it uses `webpack://` URLs there.  So it's an explicit decision by webpack.

If you want to just display the webpack URLs somewhere associated with the corresponding generated source, then that's up to the debugger display (I don't know anything about that).  But if you want to change the displayed URL; first, you have to take care not to introduce clashes, which would be confusing in a different way; and second, you'd probably want to do it in devtools-source-map, because that way the console will continue to agree with the debugger about the names of sources (this is important so that clicking the links works).

**Comment by jasonLaster** [comment]
Thanks @tromey. I'm a bit concerned about changing the URLs too much in the source tree.

one thing chrome does is show a message in the footer when the source is original. We could also give a message in the bottom for generated with a link to the root original directory aka webpack.

![screen shot 2017-10-04 at 4 51 23 pm](https://user-images.githubusercontent.com/254562/31210085-54acff0a-a95d-11e7-8882-58df4ea8824a.png)

**Comment by jasonLaster** [comment]
here is a [gist][g] for doing the summary, which would be pretty cool.

[g]: https://gist.github.com/jasonLaster/2850b469c3cf819245750313115930e0

**Comment by jasonLaster** [comment]
@khal0988 is working on it
