### ISSUE TITLE
[Sources] style the debuggee domain

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4259]
It would be awesome if we could highlight the debuggee domain.

![](https://files.slack.com/files-tmb/T3V7H1198-F7DK9D8R4-7f39db2f6b/screen_shot_2017-10-03_at_11.39.22_am_480.png)

```diff
diff --git a/src/components/PrimaryPanes/SourcesTree.js b/src/components/PrimaryPanes/SourcesTree.js
index 151a774..1fb1f78 100644
--- a/src/components/PrimaryPanes/SourcesTree.js
+++ b/src/components/PrimaryPanes/SourcesTree.js
@@ -21,9 +21,11 @@ import {
   sortEntireTree,
   collapseTree,
   createTree,
-  getDirectories
+  getDirectories,
+  getUrl
 } from "../../utils/sources-tree";

+
 import ManagedTree from "../shared/ManagedTree";

 import actions from "../../actions";
@@ -230,9 +232,16 @@ class SourcesTree extends Component {
           : "paddingRight";
     }

+    const isDebuggeeDomain = getUrl(this.props.debuggeeUrl) ....
+    // we'll likely want to just look at the HOST because we only
+    // want to style the domain and not everything in the domain directory
+
     return (
       <div
-        className={classnames("node", { focused })}
+        className={classnames("node", {
+          focused,
+          debuggee: isDebuggee
+        })}
         style={{ [paddingDir]: `${depth * 15}px` }}
         key={item.path}
```

**Comment by jasonLaster** [comment]
Hey @svitlana-galianova how's it going?

**Comment by svitlana-galianova** [comment]
Hello @jasonLaster I am setting up a testing environment. Had some fun figuring how to make debugger run and make Firefox listen to the right port

**Comment by svitlana-galianova** [comment]
@jasonLaster The code has been modified a bit and it's different from the one in the issue description. I have tried different things, but I feel like without understanding which domain is debuggee, I will be stuck in the same place for a while. 

Is using "focusedItem" state property a good idea to determine which domain is debuggee or maybe "highlightItems"? From every property I saw in the code, I feel like those two are the most suitable.

**Comment by jasonLaster** [comment]
Hi @svitlana-galianova!

thanks for reaching out, the debuggee url is [here](https://github.com/devtools-html/debugger.html/blob/master/src/components/PrimaryPanes/SourcesTree.js#L363-L364)

so you should be able to get it w/ `this.props.debuggeeUrl` :)

**Comment by tohmjudson** [comment]
Hi @svitlana-galianova !

I like this change... it's a subtle way to see where you are in a larger project. If you don't mind, I think you could make a couple small changes to take advantage of the `getURL` utility already in the project.

The `getURL` utility would be added [here](https://github.com/devtools-html/debugger.html/blob/master/src/components/PrimaryPanes/SourcesTree.js#L27-L36). The function lives in the utils/sources-tree folder if you want to check it out, but you should only need to call it like the other utils.

By doing that, you should be able to to do something like `const isDebugeeDomain = getURL(this.props.debuggeeUrl)` [here](https://github.com/devtools-html/debugger.html/blob/master/src/components/PrimaryPanes/SourcesTree.js#L217), which will then make your comparison for the class to `item.name` much simpler.

For the CSS, I would recommend moving it to the Sources.css since this is really more about the tree than the svg. I did the exact same thing yesterday for PR I am working on :)

Does that make sense? Keep up the great work!

**Comment by svitlana-galianova** [comment]
@tohmjudson Thank you for your suggestion! I have used "debuggeeUrl contains name" logic, so it wasn't that hard and I wasn't parsing it by myself
