### ISSUE TITLE
Collapse/Expand sidebar UI

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#426]
We should have a button next to the sidebars for collapsing them. Clicking them should start a slidey animation of course.

NOTE: don't worry about getting the right icon. It could be anything, we can fix that later :)

![screen shot 2016-07-27 at 11 35 34 am](https://cloud.githubusercontent.com/assets/254562/17181437/237ebe0c-53ee-11e6-9205-e4aca9474040.png)

**Comment by jasonLaster** [comment]
This is a small enhancement that I think we can get to next sprint.

**Comment by jbhoosreddy** [comment]
@jasonLaster thanks! I'll work on it in the next sprint!

**Comment by clarkbw** [comment]
@helenvholmes has designs for sidebars across the toolboxes

**Comment by wldcordeiro** [comment]
I like the idea of taking on this task. 😄 I had an idea, rather than an icon in the right panel, how about changing the `Draggable` component? I'm thinking something like Illustrator/Lightroom so increase the width of the Draggable, put an arrow icon there and make a double click toggle the collapse. I'm willing to implement it however but figured a suggestion never hurts.

**Comment by helenvholmes** [comment]
@clarkbw I have sidebar designs for sidebars with additional tabs, but I think they're going to be different from the debugger, which instead is one tab, with an accordion.

Sidebar with panels: https://invis.io/F68A5KHKY#/179720580_Sidebar_Tabs 

Sidebar with one panel, accordion (ignore old icon cruft): https://cl.ly/3Y1j3G3F0s1r

@clarkbw: Do we want to split up the Debugger to have panels for some things instead of a monolithic accordion?

@wldcordeiro I'm intrigued by your suggestion, but I don't think I understand it yet + I want to make sure it works across all of the tools, not just the debugger. Could you post a ./mov file with what you're imagining? :)

**Comment by jasonLaster** [comment]
@helenvholmes I think the panel suggestion is a good one. I'd like to suggest that we schedule some time in October to kickoff some larger UX projects for the debugger. I'm worried that we don't have the bandwidth to do this work properly beforehand.

**Comment by jasonLaster** [comment]
Quick update:

* Here is the current [h-split-box](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/components/h-split-box.js) 
* the v-split-box is coming soon. couple test failures
* there's a toggle button in the tree [button](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/components/sidebar-toggle.js)
* here's where the inspector pane toggle logic is [defined](https://dxr.mozilla.org/mozilla-central/source/devtools/client/inspector/inspector-panel.js?q=path%3A%2Ainspector-panel.js&redirect_type=single#1253)
* here's the toggle animation [togglePane](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/widgets/view-helpers.js#243)

Take aways:
* we should upgrade the h-split-box
* we should probably use the togglePane animation, looks solid

**Comment by wldcordeiro** [comment]
@jasonLaster how does this apply to debugger.html? Do we port those into `js/lib/devtools` for development?

**Comment by jasonLaster** [comment]
talked offline.

* split-box goes in lib devtools unless we need to modify it
* other functions we can evaluate on a case-by-case basis

**Comment by helenvholmes** [comment]
Hey everyone! I see this is assigned to me. I no longer feel I understand what this issue is for, even going over the backscroll :(

What is the desired outcome to be able to close this issue?

**Comment by wldcordeiro** [comment]
@jasonLaster since we brought in the `SplitBox` from m-c and I had done this before, could I take another stab at it? Not sure what we decided as far as whether this is actionable or not. I'd really like to get collapsible sidebars in. 👍

**Comment by jasonLaster** [comment]
Hi Wellington, sure. We can likely use the toggle function in m-c. The
inspector does this, so we can likely do something similar.

**Comment by wldcordeiro** [comment]
@jasonLaster I'll take a look at how they're doing that. I want to avoid modifying splitbox if needs be. 👍

**Comment by jasonLaster** [comment]
The inspector link from above broke, here's a [new](https://dxr.mozilla.org/mozilla-central/source/devtools/client/inspector/inspector.js#1380-1411) one. The [togglePane](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/widgets/view-helpers.js#243) animation looks pretty good as well.

We'll likely want to use splitbox state to keep the width/height instead of setting dom attrs.

**Comment by jasonLaster** [comment]
closed in favor of a more actionable issue #1317
