### ISSUE TITLE
Taskcluster

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#429]
Created an issue to track our work w/ task cluster

- [ ] run unit tests
- [ ] run integration tests

Also, noticed positron is using it: https://github.com/mozilla/positron/pull/103/files

**Comment by jlongster** [comment]
Spent a lot of time on this today. I'm sort of getting the hang of it, but I don't feel close. Hopefully tomorrow I'll make some headway, but I wish we could get someone else to do this work... I was able to meet with someone from taskcluster today and it helped a lot but this still feels like a time sink since taskcluster is such a big project.

I'll work more with the taskcluster team tomorrow and see if I can get more help. At least now I know what questions to ask!

**Comment by jlongster** [comment]
Actually, I just realized something. I was about to write a taskcluster task that downloads the artifact build of Firefox and just runs tests like you would locally, and it would be based of a standard ubuntu image. At that point, there's no reason we can't just use CircleCI for that. I was thinking that taskcluster might have pre-built images that would make it easy to run mochitests, but if you are outside the tree, apparently not.

We still need to write taskcluster tasks for running the tests in the tree, and I pretty much know how to do that now. We will need to do that before we turn on the debugger, but the most important thing is getting integration tests against the Firefox panel itself, and doing that in CircleCI is fine for our github pr-style development.

**Comment by jasonLaster** [comment]
That's a great idea.

Thanks for doing this work. Looking forward to the braindump.

If I understand correctly, circle for GitHub CI, tadkcluster for MC patches?

**Comment by clarkbw** [comment]
Closing this for now.  We can open this up again later when we want to circle back to using taskcluster again.
