### ISSUE TITLE
[Breakpoints] Webpack inline source maps do not work

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4366]
When I'm using

```
devtool: 'inline-source-map',
```

it doesn't work. But switching to:

```
devtool: 'source-map',
```

and the breakpoints are working normally.

[video](https://devtools-html.slack.com/files/U7H3CJFR7/F7JFAQUKY/v.mp4)

**Comment by jahed** [comment]
Worth mentioning that this works fine in Chrome's dev tools.

I've tried reproducing this using a smaller code base with the same Webpack build and the following properties:

- inline-source-map
- Class components
- Functional components
- Dynamic imports
- Object destruction

All of which work normally. Might just have to strip my project bit by bit until the problem disappears to find the cause. There's a good chance it's one of the many dependencies in the entry chunk messing something up.

**Comment by jasonLaster** [comment]
yeah... i'd look at source map root and babel too

**Comment by jahed** [comment]
I can confirm that this issue seems to be fixed in Quantum's release build. That or my source maps changed enough for the problem to not occur.

Apologies for not getting back on this sooner. Ended up focusing on a different project and forgot until Quantum was released (this issue doesn't appear in my "Issues" page).

Feel free to close. Thanks for giving it attention!

**Comment by jasonLaster** [comment]
Great!
