### ISSUE TITLE
Replace `utils/path.js` with a proper path library

### ISSUE THREAD

**Issue by jlongster** [devtools-html/debugger.html#451]
We hacked together `path.js` as a temporary module, but we should use a library that provides real joining and other operations on URLs. I just added a few methods to resolve source map URLs, and it's getting hacky. Someone should find a nice (small) library for operating on URLs (basename, dirname, join, etc).

**Comment by hallvors** [comment]
Here's Node's Path documentation: https://nodejs.org/api/path.html
https://github.com/nodejs/node/blob/master/lib/path.js

Not sure if that's reusable. I haven't found anything else so far.

**Comment by jasonLaster** [comment]
@jlongster do you think we'll be able to take this on this sprint or next?

**Comment by wldcordeiro** [comment]
Someone has published the `Node` `path` lib to npm, but they haven't updated in some time (looks like the lib from 0.12.7 from the last commit) and some limited searching isn't giving me a ton of results either.

**Comment by jasonLaster** [comment]
Interesting. I wonder if the node library would work in the browser? Does
it have any dependencies?

**Comment by wldcordeiro** [comment]
@jasonLaster looks like it depends on `process` and `util` https://github.com/jinder/path/blob/master/package.json#L21

**Comment by jbhoosreddy** [comment]
maybe something like [path-browserify](https://www.npmjs.com/package/path-browserify) is useful.

**Comment by wldcordeiro** [comment]
Dependency tree of the path package I posted
- path
  - util
    - inherits
  - process

**Comment by wldcordeiro** [comment]
@jbhoosreddy looks like that is relatively similar to what I posted only further out of date.

**Comment by jbhoosreddy** [comment]
@wldcordeiro I posted it as a suggestion because it doesn't have any dependencies (except tape for tests) and seems to have methods which are talked about in the issue like (basename, dirname, join, etc.). I see it's not actively maintained, but I imagine we could make modifications as per our requirements if needed.

**Comment by jbhoosreddy** [comment]
Reading the code for all the libraries mentioned here and those I found on the internet, I think the way to do this would be to keep the existing `utils/path.js` which maps to particular methods in the node `path` library. We can further use `Services` to identify which operating system we are working on and separate exports for win32 and posix explicitly.
It seems they use `process` to do things like identify OS type and current working directory (if no arguments are given), and we can prevent using that code since we have that information.

**Comment by jbhoosreddy** [comment]
I can take this issue, if no one has. I'm interested to see if I get somewhere with this approach (in a usable way). 😅

**Comment by wldcordeiro** [comment]
All your @jbhoosreddy looks like you've got something in mind. 😄

**Comment by jasonLaster** [comment]
Thanks @jbhoosreddy - i like your approach. One thing to add though. If you have something pretty good, it might be nice to release your own NPM library :) 

You can always copy over the Services OS methods to the library and inline them.

**Comment by jlongster** [comment]
We haven't seen anything that properly handles URLs, so let's just use what we've got. We can always bank on forward slash being the separate across platform because it's a URL, which makes it very simple.
