### ISSUE TITLE
Reloading debuggee with breakpoint hangs

### ISSUE THREAD

**Issue by hallvors** [devtools-html/debugger.html#459]
1. Go to http://localhost:8000/increment example in debuggee browser
2. In debugger, open *increment / (index)* and set breakpoint on ``_value = 0`` line
3. Reload debuggee page

Bug: never finishes loading. In the debugger, the UI doesn't show it stopped at a breakpoint either.

**Comment by jasonLaster** [comment]
I believe i fixed this last week. If i remember correctly, the bug was related to source maps not updating: https://github.com/devtools-html/debugger.html/commit/b9d515a8ef44d3727bdee5e886068fd5ce8a0d16. 

Either way, i believe this is the case you were describing.

![screen shot 2016-08-09 at 10 56 29 am](https://cloud.githubusercontent.com/assets/254562/17521010/bb6fcb8a-5e1f-11e6-90ef-2065414cd6d1.png)
