### ISSUE TITLE
Conditional breakpoint overlay is cut off in vertical mode

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4703]
STR:

- Vertical mode in Debugger
- Make breakpoint conditional

ER: Correctly positioned conditional breakpoint form, responsively fitting into the space available.

AR: <img width="661" alt="image" src="https://user-images.githubusercontent.com/8599/32876270-ef4d12a2-ca50-11e7-95ba-34d857b8e596.png">

**Comment by borian** [comment]
Mhh, I was not able to reproduce the issue

![condition-breakpoint](https://user-images.githubusercontent.com/1525694/32994083-a83822de-cd62-11e7-9309-b48ae3cbf695.png)

**Comment by magicp-github** [comment]
Probably, CodeMirror was scrolled horizontally in AR image?

**Comment by Zacqary** [comment]
It looks like there's a responsiveness bug even outside of vertical mode. Notice how the close button is obscured because it's too far to the right:
![screen shot 2017-11-27 at 12 17 49 pm](https://user-images.githubusercontent.com/1445834/33282064-0a7e8ebe-d36d-11e7-9299-269017cf3410.png)

This is fixable in horizontal mode by setting the `CodeMirror-linewidget` to have `width: calc(100% - 30px)` but that doesn't work in vertical mode when the user can scroll horizontally. 

I think we need to clear up what the expected behavior is in vertical mode. Do we want something like this?
![screen shot 2017-11-27 at 12 21 50 pm](https://user-images.githubusercontent.com/1445834/33282244-b1409800-d36d-11e7-9636-388bfbea82a3.png)
and have it fixed in that position as the user scrolls to the right?
![screen shot 2017-11-27 at 12 23 38 pm](https://user-images.githubusercontent.com/1445834/33282309-dbb4acac-d36d-11e7-9583-d626e96a04c3.png)

(This is a mockup, I haven't yet figured out how to do that in proper CSS)

**Comment by jasonLaster** [comment]
👋 @Zacqary!

We have a UI redux field for the sidebar widths. Could help...

**Comment by Zacqary** [comment]
So here's what I was able to achieve by adding `padding-right: 16px` to `.conditional-breakpoint-panel` and then removing the `min-width` from `.CodeMirror-sizer` — the condition input field is now fully responsive, and the only thing that's still broken is horizontal scrolling:

![resize](https://user-images.githubusercontent.com/1445834/33288411-cf11872c-d381-11e7-9aed-c5d7e9d2be83.gif)

I haven't actually been able to figure out why `.CodeMirror-sizer` has a `min-width` property; it doesn't seem to break anything when I disable it, but it's got to be there for a reason, right?

**Comment by wldcordeiro** [comment]
The PR associated was merged a month ago so this looks like it should be closed.
