### ISSUE TITLE
Performance issue on angular2 site

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#4705]
STRs:
- go to https://jovandemo.modulentwicklung.de:8001/admin/
  User: anyone@mozilla.org
  PW: 123456789
- Navigate to Orders > Orders
- open devtools on a non-debugger panel (e.g. the Console cmd+alt+K)
- switch to the debugger

ER: Sources appear quickly
AR: Debugger remains blank for several dozen seconds, before showing sources (might crash your tab)

Note: if you directly open the toolbox on the debugger, the sources show up quickly.

Profiles are pretty hard to read. In order to get meaningful data, we had to reduce the sample size down, because with 1ms we were missing the GC/CC pauses that seem responsible for the slowdown.

https://perfht.ml/2A3hRR1

On this profile we can see around 10 seconds are lost in a CC pause in the parent process.

**Comment by juliandescottes** [comment]
Removing a few await/async seem to fix the issue for this test case:

https://github.com/devtools-html/debugger.html/blob/e12186b556563e67ee8c1dd37094a1c1be5042bb/src/actions/sources.js#L136-L138

removing the 2 await +  async on those 3 lines fixes the performance issue and doesn't seem to completely break the debugger (I don't know the implementation in details so I might be terribly wrong).

cc @codehag , I think you worked on similar topics, maybe that's one spot where we shouldn't wait on all the async work to be finished before displaying the UI.

**Comment by codehag** [comment]
moving around the awaits can be a bit dangerous, since some dispatches rely on other dispatches, and this isn't easy to see from the code. 

For example, checkPendingBreakpoints has a call to loadSourceText, and we are also loading the sourcetext here. if we load it twice, then the screen flashes (and we double the work)

**Comment by juliandescottes** [comment]
Thanks @codehag ! I intended this as a pointer to the bottleneck, I understand that this is too careless to be an actual fix. I will try to implement your suggestion of queuing for loadSourceText, thanks for having a look.

Alternatively, maybe we could stop loading the sourceText of all sources upfront - and do it lazily instead ? In this scenario no source tab is opened, we just want the tree. (again I don't know the implementation at all, so that might be a very bad idea)

**Comment by jasonLaster** [comment]
> stop loading the sourceText of all sources upfront

We're naive, but not that naive :) we load source text for cases where we need to source map, which are when we're re-syncing breakpoints. We can queue this work and do it in the background

I dug a bit more into this case today and found that this is an evil page w/ 400 sources, each of which have an inline source map.

Here are some screenshots of us struggling to keep up

<img src='https://shipusercontent.com/8409a9007f7a032c5eb6073f84dcdb36/Screen%20Shot%202017-11-18%20at%205.15.04%20PM.png' title='Screen Shot 2017-11-18 at 5.15.04 PM.png' width=1086>
<img src='https://shipusercontent.com/6bac47164c91a20c80f851e5143c4912/Screen%20Shot%202017-11-18%20at%205.14.58%20PM.png' title='Screen Shot 2017-11-18 at 5.14.58 PM.png' width=535>

But, there were really only a couple issues:

1. the Editor tried to re-render every time. This was a recent regression w/ `setSourceMetadata`
2. we still had a lot of dispatches - we probably need a bit of lodash throttling here:

#### fixes the editor updating

- we should have a unit test where we add 10 sources and make sure we do 0 Editor renders...

```diff
diff --git a/src/reducers/ast.js b/src/reducers/ast.js
index 29278c8..ba3df44 100644
--- a/src/reducers/ast.js
+++ b/src/reducers/ast.js
@@ -183,8 +183,9 @@ export function getPreview(state: OuterState) {
   return state.ast.get("preview");
 }

+const emptySourceMetaData = {};
 export function getSourceMetaData(state: OuterState, sourceId: string) {
-  return state.ast.getIn(["sourceMetaData", sourceId]) || {};
+  return state.ast.getIn(["sourceMetaData", sourceId]) || emptySourceMetaData;
 }
 ```

#### throttling sources

I added a new queuing mechanism in our events so that we can keep our redux system simple. And updated `newSources`

```js
let pendingSources = [];
const newSources = throttle(() => {
  actions.newSources(
    pendingSources.map(source => createSource(source, { supportsWasm }))
  );
  pendingSources = [];
}, 100);

function newSource(_: "newSource", { source }: SourcePacket) {
  pendingSources.push(source);
  newSources();

  if (isEnabled("eventListeners")) {
    actions.fetchEventListeners();
  }
}
```

```js
export function newSources(sources: Source[]) {
  return async ({ dispatch, getState }: ThunkArgs) => {
    const filteredSources = sources.filter(
      source => !getSource(getState(), source.id)
    );

    dispatch({
      type: "ADD_SOURCES",
      sources
    });

    for (const source of filteredSources) {
      dispatch(loadSourceMap(source));
      checkSelectedSource(getState(), dispatch, source);
      checkPendingBreakpoints(getState(), dispatch, source.id);
    }
  };
}
```

#### Next steps

* I'll push this work to our branch and pick it up on monday. I think there are some holistic fixes that can be made so that we delay work intelligently with requestIdleCallback and are appropriately queing 
* Also the site has base64 encoded inline data source map URLs which our launchpad cries w/ we should update it to be happier: this would do the charm if we know it's inline `window.atob(source.sourceMapURL.slice(29,))`

**Comment by codehag** [comment]
is there another example page that we can check? i tried the existing one and it comes as a 404

**Comment by jasonLaster** [comment]
strange worked for me

**Comment by juliandescottes** [comment]
The server was probably down temporarily?

Would be nice to isolate this as a dedicated test case now that there is a better understanding of what is causing the performance issue.

**Comment by codehag** [comment]
is this still open?

**Comment by codehag** [comment]
Also, how can i get in touch with jovan, i would like to ask if i can use his example as a starting point for a regression test

**Comment by TitanNano** [comment]
@codehag you can reach me here or on slack.

**Comment by jasonLaster** [comment]
I think this is closed for now. @TitanNano please keep the demo app up it's really helpful :)

**Comment by TitanNano** [comment]
@jasonLaster no problem. I would just have one request. Can I give you a password which is ony shared Mozilla internally and not made public? We don't really want this shop to be accessible for unauthorized users.

**Comment by jasonLaster** [comment]
sure
