### ISSUE TITLE
[SourceTree] show angular icon as a domain

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4733]
We currently show the webpack logo when the domain is webpack, we should do the same for angular :)

- the path might be slightly off - easy to check in `addToTree.js`
- the icon will need styling w/ light and dark themes

```diff
diff --git a/src/components/PrimaryPanes/SourcesTree.js b/src/components/PrimaryPanes/SourcesTree.js
index e2d6981..3f8adf8 100644
--- a/src/components/PrimaryPanes/SourcesTree.js
+++ b/src/components/PrimaryPanes/SourcesTree.js
@@ -232,6 +232,10 @@ class SourcesTree extends Component<Props, State> {
       return <Svg name="webpack" />;
     }
 
+    if (item.path === "/ng:") {
+      return <Svg name="angular" />;
+    }
+
     if (depth === 0) {
       return (
         <img
```

<img src='https://shipusercontent.com/3fc075cf7a02d2004ce2aef195e2e3b3/Screen%20Shot%202017-11-18%20at%204.54.41%20PM.png' title='Screen Shot 2017-11-18 at 4.54.41 PM.png' width=319>

**Comment by borian** [comment]
Hey Jason,
https://github.com/borian/debugger.html/commit/762f7ced050930db5086a066a9a800a28a66540f
The `angular.svg` was already there so I only added the path check and styling.

Because the icon is already used in the call stack view, I needed to add specific styling for the source pane

`.managed-tree .tree-node .angular svg {`

![light](https://user-images.githubusercontent.com/1525694/32992085-ae98ed28-cd46-11e7-9322-6a17fd220d74.png)
![dark](https://user-images.githubusercontent.com/1525694/32992086-b12a40c8-cd46-11e7-82f5-9c6db84bd648.png)

If this is ok, I will do a PR

**Comment by zaggy** [comment]
Maybe a good thing is to write `Angular (ng://)` instead of just plain `ng://` or like we do with Webpack, to ditch the address part altogether.

**Comment by jasonLaster** [comment]
Yep, I'd just show Angular. Most users don't care

**Comment by borian** [comment]
updated the PR https://github.com/devtools-html/debugger.html/pull/4738
Now it just showes Angular


![ng-light](https://user-images.githubusercontent.com/1525694/33102301-69ee4ed4-cf1c-11e7-9363-2663085d53e7.png)
![ng-dark](https://user-images.githubusercontent.com/1525694/33102294-60f8054a-cf1c-11e7-8425-f179022023bc.png)
