### ISSUE TITLE
Feature - Add an option to change devtools font size (or zoom) with a mousewheel

### ISSUE THREAD

**Issue by eladcandroid** [devtools-html/debugger.html#4736]

**Comment by jasonLaster** [comment]
Hi, thanks for the feature request. I'm closing this issue and moving to the [enhancements](http://github.com/devtools-html/debugger.html/projects/5) board. 

* We will hopefully be able to prioritize it in the near future. 
* The issue is closed temporarily, but feel free to continue discussing here
