### ISSUE TITLE
[Breakpoint] variable is not defined at breakpoint

### ISSUE THREAD

**Issue by AnshulMalik** [devtools-html/debugger.html#4772]
Debugger tells it is `undefined` but it's not.

![prefs-undefined](https://user-images.githubusercontent.com/7821757/33156649-ccddcdb6-d021-11e7-8080-f4919f1b5da9.gif)

Steps to reproduce:
- `yarn run firefox` and go to http://firefox-dev.tools/debugger-examples/examples/todomvc/
- Do `yarn start`, open the debugger `localhost:8000`
- Open developer tools (F12) and set a breakpoint at line 211 in `src/actions/sources.js`
- In sources tree, open `js/views/app-view.js`

**Comment by jasonLaster** [comment]
So a couple of things:

1. prefs is undefined because it is a webpack module. so preview would need to know what the generated expression is. We don't do that yet. @jbhoosreddy is working on it :)
2. autoPrettyPrint shows true for me now. not sure what's up w/ that

---
![](http://g.recordit.co/9mz2JZFpz4.gif)
---
![](http://g.recordit.co/xLogEDE9LA.gif)
