### ISSUE TITLE
fix jest warnings

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#4828]
we have a number of jest warnings that it would be good to take care of.

warnings:
```
 PASS  src/components/Editor/tests/Editor.spec.js
  ● Console

    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

 PASS  src/components/SecondaryPanes/tests/Expressions.spec.js
  ● Console

      Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class


 PASS  src/components/ProjectSearch/tests/TextSearch.js
  ● Console

      Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
```

**Comment by jasonLaster** [comment]
someone mentioned this was coming from devtools-core packages

**Comment by Zacqary** [comment]
Tried to fix this for a while, here's what I found out:

Upgrading some of the `devtools-core` Yarn packages seemed to show me more warnings about calling `createClass`, not less, for some reason, even though their latest versions appear to have silenced all React-related warnings. Upgrading all of them makes it impossible for the debugger to compile; it seems like the Babel configuration doesn't recognize `static get() propTypes` in `Draggable`, which was one of `devtools-splitter`'s warning silencing fixes.

One difficult culprit I tracked down is that `svg-inline-react` silenced its warnings in 1.0.3, so that also probably needs to be upgraded to fix this bug.

**Comment by lukaszsobek** [comment]
Warnings by order of appearance with source:

test file:
`src/components/Editor/tests/Editor.spec.js`
Warning source:
`import Reps from "devtools-reps";`

test file:
`src/components/ProjectSearch/tests/TextSearch.js`
Warning source:
`import { Tree } from "devtools-components";`

test file:
`src/components/SecondaryPanes/tests/Expressions.spec.js`
Warning source:
`import { ObjectInspector } from "devtools-reps";`

**Comment by lukaszsobek** [comment]
Related: https://github.com/devtools-html/debugger.html/issues/4848 for why update to 0.15 breaks

**Comment by jasonLaster** [comment]
Ahh, i think we're upgrading them soon as we go to React 16! So this could fix itself
