### ISSUE TITLE
Bump devtools-reps and devtools-splitters to the latest version

### ISSUE THREAD

**Issue by MikeRatcliffe** [devtools-html/debugger.html#4848]
I have a new blocker getting React 16.2.0 running inside Firefox DevTools...

If you look [here](https://searchfox.org/mozilla-central/source/devtools/client/debugger/new/debugger.js#33543) you can see that the debugger is still using React.DOM and React.PropTypes, which are not compatible with React 16.2.0.

This is confusing because on Nov 6 I committed changes throughout devtools-core to prepare for the React 16 update and the last time we merged debugger.js was a week later on Nov 13.

Anyhow, it seems like although debugger.js was updated we used an older version of devtools-splitter.

I might regret asking, but is there anything I can do to help fix this quickly? I think we only need to update the devtools-splitter to from 0.0.5 to 0.0.6.

**Comment by nchevobbe** [comment]
We also need to update devtools-reps to 0.0.15 (or 16 if we publish it meanwhile).
This is blocked due to the ObjectInspector not persisting its state in new reps package, which is an issue when the debugger switch from horizontal to vertical layout (or the other way around).
Switching the debugger to be CSS Grid-driven would solve this issue (no need to unmount to change the layout).
This is investigated in https://github.com/devtools-html/debugger.html/issues/4839

**Comment by jasonLaster** [comment]
This should be fixed
