### ISSUE TITLE
[Editor] Adding a breakpoint should not cause the editor to scroll

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#4852]
**Steps to reproduce:**
1. Launch the latest Nightly
2. Go to about:home
3. Open Debugger
4. Open resource://activity-stream/data/content/activity-stream.bundle.js
5. Scroll down about one or two page <- _This is an important step for reproducing_
6. Add breakpoint (e.g. Click line number 104) <- _This step works_
7. Remove breakpoint
8. Switch DevTools tab, then go back Debugger
9. Add breakpoint in line 104 <- _No response (or make a breakpoint in other line)_
10. Click in code view -> cursor will be jump to other line

**Actual Results:**
Add breakpoint is no response (or make a breakpoint in other line) after switching DevTools tab. If you click in code view, cursor will be jump to other line.

**Expected Results:**
Add breakpoint works even if after switching DevTools tab.
Cursor does not jump to other line.

**Comment by juliandescottes** [comment]
Note that this behavior seems to depend on your toolbox height. I was about to log a different bug, but I think it would be a duplicate so I'll just add my STRs here.

STRs:
- make sure to use a rather small toolbox height (you can set devtools.toolbox.footer.height to 250 in about:config for instance, assuming toolbox docked to the bottom)
- go to http://firefox-dev.tools/debugger-examples/examples/todomvc/
- set a breakpoint in app-view.js, render() method, line 52
- add to todo to break on your breakpoint
- switch to console, switch back to debugger
- click on your breakpoint in the gutter to delete it

AR: Breakpoint is added at line 15
ER: Breakpoint is deleted 

Note that the behavior really changes depending on the toolbox height. With 300px instead of 250px, clicking on the breakpoint does nothing. With 400px, the buggy breakpoint gets added on line 24 instead of 15.

![debugger_breakpoint_wrong_location](https://user-images.githubusercontent.com/1141550/33583050-a83ecdbc-d958-11e7-94c6-5d49bf6ad5bc.gif)

**Comment by jasonLaster** [comment]
Oh yeah, this is certainly an interesting codemirror bug. I think it will likely turn out that codemirror needs to be forced to update when we re-display the document or make the UI visible.

Great catch!

by the way, I reproduced by going to todomvc and todo-view.js:104
http://firefox-dev.tools/debugger-examples/examples/todomvc/

![bp-codemirror](https://user-images.githubusercontent.com/254562/36548013-2c8965d0-17bd-11e8-9d8f-bd6652b5e1df.gif)

**Comment by jasonLaster** [comment]
@mcote is working on it

**Comment by jasonLaster** [comment]
so this is still an issue because we no longer use the visibility handler

**Comment by darkwing** [comment]
I recall being able to reproduce this in the past but I cannot reproduce with a fresh build off of master.

**Comment by juliandescottes** [comment]
Can't reproduce either on the latest Nightly, this seems fixed. Maybe a codemirror update?
