### ISSUE TITLE
[Performance] Debugger in background causes hangs

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4896]
STR
- Opened https://alpha.giveth.io/ with Debugger set to `Pause on uncaught exception`
- Paused on `value` or similar, showing a non-pretty minified JS file
- Switch to a different tab (I opened https://github.com/devtools-html/debugger.html/issues/new to file a bug about that the `js` file doesn't have a prettify option)

AR:
- Debugger in background causes massive hangs on the main process, even with tab and devtools in the background

ER:
- Debugger in background behaves nicely

https://perfht.ml/2iGWuuc - Rendering a lot of React, with the typical expensive updates on source editor

**Comment by jasonLaster** [comment]
The first half of the time is spent in `setText` the second half is spent in `getCallSites`. I opened a PR, which fixes the callsite feature flag. We'll have to look into setText separately.


<img width="801" alt="screen shot 2017-12-09 at 11 31 25 am" src="https://user-images.githubusercontent.com/254562/33797387-d0082e2c-dcd4-11e7-9fc3-087e5bd0c706.png">

We'll want to look into speeding up `setText` as well.

<img width="1552" alt="screen shot 2017-12-09 at 11 30 01 am" src="https://user-images.githubusercontent.com/254562/33797395-f240096a-dcd4-11e7-8924-31bf4f856b45.png">
<img width="1552" alt="screen shot 2017-12-09 at 11 29 50 am" src="https://user-images.githubusercontent.com/254562/33797396-f24a8868-dcd4-11e7-84a0-3213b7e5351e.png">

**Comment by digitarald** [comment]
We we have mechanisms to not do heavy UI updates when in background?

**Comment by jasonLaster** [comment]
I believe @ochameau has a patch for this.

**Comment by ochameau** [comment]
I did the work for the console as an example here:
  https://bugzilla.mozilla.org/show_bug.cgi?id=1399242
But work is still needed all other panels, to use the VisibilityHandler React component:
  https://searchfox.org/mozilla-central/source/devtools/client/shared/components/VisibilityHandler.js
I filled a bug to do that for the debugger here:
  https://bugzilla.mozilla.org/show_bug.cgi?id=1419352
  I filled on bugzilla as it would require some tweaks to DAMP test.

**Comment by jasonLaster** [comment]
Thanks. Maybe we can give this a try when we're together this week

**Comment by ochameau** [comment]
I won't be joining Austin all hands, but I can join you on vidyo during Austin mornings if that helps anything.

**Comment by jasonLaster** [comment]
Okay, sounds good

**Comment by jasonLaster** [comment]
CC

Console started doing that in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1399242) and more recently Netmonitor applied the same strategy in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1419350).
Console and Netmonitor converged into one shared helper module, via [this patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1443121). This helper is located in [devtools/client/shared/redux/visibility-handler-connect.js](https://hg.mozilla.org/integration/autoland/file/55b683e679b0/devtools/client/shared/redux/visibility-handler-connect.js).
In order to stop react rendering, you "just" have to replace your regular `connect` from redux, with the one provided by this module.

Now it is unclear to me how debugger.html can/should use such new m-c module.
This module may not be that useful when we run the debugger on launchpad. So using a mock, or using directly redux original `connect` method is an option.

**Comment by jasonLaster** [comment]
@mcote is looking into this

**Comment by jasonLaster** [comment]
adding this example from #5087 as well

Related to #4896, but looks like different bottlenecks in the profile.

STR:

- Set a breakpoints on http://firefox-dev.tools/debugger-examples/examples/wasm/fib/fib.index.html and hit refresh to hit the breakpoint and pause
- Open Wikipedia in a new tab (keep debugger open in background) and scroll down

AR: 150ms+ hangs during scrolling

https://perfht.ml/2CScodv

- Profile renders a ton of react after receiving new data; which doesn't make sense as it it in the background and should do unnecessary work

**Comment by digitarald** [comment]
Is this still an issue after #6774? The STR page seems down and I tried reproducing by pausing in other heavy apps.

**Comment by jasonLaster** [comment]
I think it is okay now. we've fixed a bunch of the underlying issues

**Comment by jasonLaster** [comment]
either way, we can always open a new more specific bug
