### ISSUE TITLE
[Welcome] Hide content for narrow widths

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4928]
When you open the debugger when it's docked to the right, the welcome content is wrapped like crazy.

Perhaps we want to hide the content after a certain min-width.

<img src='https://shipusercontent.com/3e74c5310afdf23f35618cbc3d89ee97/Screen%20Shot%202017-12-15%20at%2010.06.26%20AM.png' title='Screen Shot 2017-12-15 at 10.06.26 AM.png' width=589>

CC @violasong?

**Comment by pradeepgangwar** [comment]
@jasonLaster May I try fixing this one if available. :)

**Comment by violasong** [comment]
Oof, yeah, "fix vertical mode" is a general todo item on my list since it suffers from not enough dogfooding - lots of issues including can't get narrow enough, imo. 

Interesting to see it looks like this when you switch from bottom-dock to side. 

<img width="462" alt="image" src="https://user-images.githubusercontent.com/55994/34281344-21644466-e68c-11e7-8cf3-446796240f48.png">

The above actually looks fine if the breakpoints part is just a lot shorter, and the source tree is narrower as well, perhaps something like this: 

<img width="463" alt="image" src="https://user-images.githubusercontent.com/55994/34281424-9fa21420-e68c-11e7-9e3e-c42d2a9a78f3.png">

(as a bonus you can see the buggy sourcemap message which needs truncation). It doesn't seem to save my sidebar adjustments when I switch to bottom dock and back.

If we stick with a three-column idea, the content area is fine if we make the sidebars smaller by default. This still doesn't seem very usable however, so I think I'd prefer the solution above, "breakpoints below, but shorter, and narrow source tree."

<img width="462" alt="image" src="https://user-images.githubusercontent.com/55994/34281525-50419120-e68d-11e7-9034-e1239488fdc3.png">

**Comment by pradeepgangwar** [comment]
I found that currently we use https://github.com/devtools-html/debugger.html/blob/master/src/components/WelcomeBox.css#L69 to maintain welcome box text, but recently i figured out that @media property is concerned about screen size but here width of welcome box also depends on sidebars widths. 
This can be handled by writing proper JS, so i want to ask where should i write such JS code as most JS files contain react code. If there is another workaround then please let me know.

**Comment by jasonLaster** [comment]
Maybe the welcomeBox component? Not sure...

**Comment by violasong** [comment]
I'm not sure if I understand the question, but my hope here was that we change the layout defaults (to #2 of my images) which would remove the problem with a too-narrow welcome content area.

**Comment by wldcordeiro** [comment]
@violasong I understand what you're getting at here. We should have the "vertical" layout enabled at smaller widths even when not docked to the side and we should adjust the division of the splitbox to give more space to the editor+sources/outline

**Comment by jasonLaster** [comment]
Just spoke with @violasong and have some takeaways

1. we should hide the welcome box content when the box becomes too small
2. vertical mode should have a narrower default primary pane
3. vertical mode should have a shorter default secondary pane
4. when users narrow the width of the devtools while in horizontal mode we should try to narrow the widths of the panes before switching to vertical mode. (extra credit)

**Comment by jasonLaster** [comment]
Here is a screenshot w/ a narrow devtools

<img src='https://shipusercontent.com/79b4f05887891706fd8c039f177498f7/Screen%20Shot%202018-01-18%20at%2011.27.49%20AM.png' title='Screen Shot 2018-01-18 at 11.27.49 AM.png' width=690>

**Comment by jasonLaster** [comment]
Hey @pradeepgangwar, still interested?

**Comment by pradeepgangwar** [comment]
@jasonLaster I got busy with other things. I think I will not be able to work on this currently. I am unclaiming it to allow others work on this. 
/uncliam

**Comment by ericawright** [comment]
@jasonLaster 
When in vertical mode, it should always show up as @violasong 's first image. I figured out why it's not, and I wanted to get a suggestion on a preferred way to solve it.
When on the bottom, if you toggle away from the debugger, it triggers the matchMedia listener to switch from true to false, but, because the component is not visible, it does not set the props nor re-render. Then on a toggle to the top, since the listener does not trigger (it's already set to false), it remains as if in horizontal mode.
If you view the debugger tab and toggle from top to bottom, it will re-render as expected between the two modes. In all other cases, since the width is 0, it thinks it's already in vertical mode.

So, some solutions:
* Set to `visibility: hidden` instead of `width: 0` - possibly problematic for the first open, since dev tools itself is `width: 0`. 
* have two match media listeners
* listen for an event from the dev tools when the toggle is pressed - is there such an event?
* listen for props.orientation change and force `this.props.setOrientation(orientation);` to run every time the orientation changes - this one I think is best, though I may not have explained it well.

**Comment by jasonLaster** [comment]
all suggestions seem fine. here are some notes:

> Set to visibility: hidden instead of width: 0 - possibly problematic for the first open, since dev tools itself is width: 0.
have two match media listeners

seems nice

> listen for an event from the dev tools when the toggle is pressed - is there such an event?

take a look at ToggleButton.js or something like that 

> listen for props.orientation change and force this.props.setOrientation(orientation); to run every time the orientation changes - this one I think is best, though I may not have explained it well.

take a look at App.js
