### ISSUE TITLE
[Sources] Use Immutable records

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4935]
It would be great to explore immutable [records][r1] with the Source I.Map. 

Benefits:
+ we can do `source.id` instead of `source.get("id")`
+ we can potentially drop the `SourceRecord` Flow type from a lot of places
+ Our utils don't have to worry if they're getting an Immutable object or PoJo

I've learned so far that Records are a bit different:
+ They always have all the fields (with a default). this is a good thing
+ Not sure if they destructure well i.e. `const newSource = {...source, {url: "foo"}}`
+ Not sure if they will serialize automatically passed to a worker.task call
+ Not sure if we should pass Records to reducers, e.g. when updating a source... Perhaps the substitute here is that we just pass the source id and new fields

Here's a [branch][b] i created for hacking on it. Already lots of passing tests :confetti_ball: 

https://medium.com/azendoo-team/immutable-record-react-redux-99f389ed676

[r1]: https://gist.github.com/jareware/5f492d47fae45d577e922c431c267c67
[b]:https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:immutable-records?expand=1

**Comment by DavideDeCenzo** [comment]
I've read the articles https://medium.com/azendoo-team/immutable-record-react-redux-99f389ed676 and  https://gist.github.com/jareware/5f492d47fae45d577e922c431c267c67  . From what I read records should destructure well also  on https://facebook.github.io/immutable-js/docs/#/Record They said Records use a custom internal rapresentation for serialization But I think it's not very exhaustive.  I've looked in your branch and I've seen the SourceRecordClass and source.id instead of source.get("id") I guess. Now what should I do? @jasonLaster

**Comment by jasonLaster** [comment]
Thanks @DavideDeCenzo. haha - make it work :)

I didnt spend too much time on it, so i'm sure it's broken in a couple of ways, but hopefully it's not too bad

Also, it could use a rebase!
