### ISSUE TITLE
[Selectors] Move selectors to the selectors folder

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#4985]
Currently some of the reselect selectors reside in various reducers, whereas other selectors already reside in the src/selectors folder. It would be nice if all the selectors were moved to the already existing src/selectors folder so we can:
1.) shorten the length of reducers files
2.) have code in a designated place 
3.) separate the functionality of reducers from selectors
4.) make import statements clearer
5.) reduce tracing of components

**Comment by jasonLaster** [comment]
@codehag and i have discussed this and think it would help.

It would nice if many of the selectors were in the selectors directory and were exported via `selectors/index`

**Comment by jasonLaster** [comment]
at the moment the selectors in the `src/selectors` dir pull state from different reducers, which is why they cant be in one reducers dir. I'm not sure how i feel about moving the selectors in the reducer files into their own module... 

The major reason not to do it is that currently the selectors are easier to follow because they're next to the reducer and the state type.

I'm not necessarily opposed either because moving the selectors out will make space for the reducer update helper methods...

@codehag

**Comment by lukaszsobek** [comment]
Ok, I'll keep working on it. Then we can take a look at the finished thing. If it looks good we can use it, if not we don't. I like having the selector in a separate file as it makes the reducer much cleaner + there is only one import.

**Comment by codehag** [comment]
do we have a candidate reducer for this? something we can play around with and see how it looks?

**Comment by lukaszsobek** [comment]
Rescoping in another issue. Closing this one.
