### ISSUE TITLE
Proposal - reorganizing the redux code.

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#5002]
One thing I think can be complicated for a new contributor to wrap their mind around is the organization of the codebase.

We have something like this

```
src/
  actions/
  components/
  reducers/
  selectors/
```

The problem here to me is that you're rarely working just in actions or just in reducers when you're dealing with Redux code. And additionally you want to be thinking about the things you're manipulating (sources, tabs, etc) So I propose something more like this.

```
src/
  components/
  store/
    config.js // location of store configuration code
    breakpoints/
        actions.js
        reducer.js
        selectors.js
    sources/
        ...
    selectors.js // re-exported per "branch" selectors (note A)
```

Note A:

Say you had a Redux tree like so

```
{
    tabs: {
        status: 'loaded',
        ...
    },
    ...
}
```

in `src/store/tabs/selectors.js` you'd have something like

```js
function getTabStatus({ tabs }) {
  return tabs.status;
}
```

and in `src/store/selectors.js` you would export a bound copy of the internal one (using reselect here would be nice for memoization too)

```js
import * as tabSelectors from 'store/tabs/selectors';

function getTabStatus(state) {
  return tabSelectors.getTabStatus(state);
}
```

Also a really nice thing about this would be adding a module resolver alias to babel like this so you can avoid long import statements like `import { Foo } from '../../../../some/path/file'`

```json
{
  "plugins" : [
    [
      "module-resolver",
      {
        "alias": {
          "store": "./src/store"
        }
      }
    ]
  ]
}
```

**Comment by jasonLaster** [comment]
Two quick points:

1. I think it might be nice to plan for sub-apps / plugins that would have their own directory. Maybe one of our features would make sense with this design? 

2. I'm concerned about module resolvers because it is an extra dependency for every new tool we add. I've found in the past it could make it difficult to add new testing, linting, intellisense tools...

**Comment by wldcordeiro** [comment]
@jasonLaster I didn't notice issues using the module resolver alias in projects where I have Jest, ESLint, Prettier, etc. But that's a good point and worth investigating. It's just a nice "quality of life" thing for developing.

Could you elaborate a bit on sub-apps/plugins? How do you see that happening in the debugger for example?

**Comment by jasonLaster** [comment]
re: module resolvers, heh - maybe tools are better now :) not sure...
re: sub-apps/plugins, i'll try and write something up in the future... it's a tough problem. the goal is to be able to continue to grow without making the project more complicated...

**Comment by wldcordeiro** [comment]
@jasonLaster agreed that the goal is avoiding complication and modularization is key. While they're really closely related the redux code (what would be `store` in my proposal) could itself be modularized into sub-apps/plugins separate from the components and reused elsewhere too. There's a lot to think about here though. Not sure I've found a best solution yet heh.

**Comment by nyrosmith** [comment]
There is one thing I don't like about file names in the current codebase & in this proposal.
The AST reducer should always be named astReducer no matter in which folder it lives.
Now it lives inside the reducer folder and is named ast.
In future it lives inside a folder named ast and would be named reducer.
This conventions forces contributors to know the current folder structure instead oft just searching the thing they want to see.
I would never call things different just because they are in a different drawer...

**Comment by jasonLaster** [comment]
@wldcordeiro @nyrosmith @lukaszsobek where is this at?

**Comment by wldcordeiro** [comment]
@nyrosmith I normally name reducers after the branch they are in the Redux state tree. So the `astReducer` becomes `ast` because that's the tree name. If you had multiple reducers within `ast` then you might have `const ast = combineReducers({ symbols, identifiers })` for example

**Comment by jasonLaster** [comment]
I'm in favor of having a `store` directory with this structure:

```
src/
  components/
  store/
    config.js // location of store configuration code
    breakpoints/
        actions.js
        reducer.js
        selectors.js
    sources/
        ...
    selectors.js // re-exported per "branch" selectors (note A)
```

I'm not a fan of module aliasing because that will make it harder to share code and make the system less adaptable in the future. We have these issues with firefox's code-base where paths are strange/magical.

I'd like to revisit this topic in a couple months once we've finished doing the performance and stability work as this kind of refactoring can cause some confusion. For this reason, i'm moving the issue to the icebox
