### ISSUE TITLE
[Tabs] Sources without URLs should have a tab

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#5102]
STR:

- Open Console
- type Tdebugger`
- Hit Enter

AR: Broken UI state that doesn't show a tab for the source, scope or and pausing

![image](https://user-images.githubusercontent.com/8599/44860979-5e928800-ac2c-11e8-9950-f454d4603647.png)

**Comment by jasonLaster** [comment]
There isn't a tab here because there isn't a URL associated with the script. We likely want to indicate that with a tab title: `eval (5)` or something like that.

**Comment by digitarald** [comment]
Bug, UX polish or feature, @jasonLaster ?

**Comment by darkwing** [comment]
Hello @atwalg2 !  How is this going?

**Comment by atwalg2** [comment]
Hey @darkwing, I got pulled away from this to fix some mistakes I made on previous PR's. I hope to get back to it asap.

**Comment by darkwing** [comment]
I've seen lots of stuff going in from you @atwalg2  -- awesome!  Is this still on your radar or should we unclaim it?

**Comment by atwalg2** [comment]
Yea I could probably just unclaim it now

**Comment by digitarald** [comment]
I just saw something similar on https://angular-quickstart.glitch.me/ . does the `ngfactory` file fall into the same issue, @jasonLaster ?

![screenflow](https://user-images.githubusercontent.com/8599/40452945-692d6424-5e98-11e8-9227-968839080ab1.gif)

**Comment by jasonLaster** [comment]
looks more like this one #5663

**Comment by jasonLaster** [comment]
STR:
1. in the console, evaluate `debugger`

![image](https://user-images.githubusercontent.com/254562/44860927-63b00100-ac45-11e8-8d91-7b71c0d75c42.png)

**Comment by darkwing** [comment]
I've been looking into why eval`d cases weren't given a tab and I think I've found the root cause.  We're using the following selector for tabs:

```js
export const getSourceTabs = createSelector(
  getTabs,
  getSources,
  getUrls,
  (tabs, sources, urls) =>
    tabs.filter(tab =>
      getSourceByUrlInSources(sources, urls, tab.url, tab.isOriginal)
    )
);

export const getSourcesForTabs = createSelector(
  getSourceTabs,
  getSources,
  getUrls,
  (tabs, sources, urls) => {
    return tabs
      .map(tab =>
        getSourceByUrlInSources(sources, urls, tab.url, tab.isOriginal)
      )
      .filter(Boolean);
  }
);
```

The issue here is `tab.url` is `null` for eval'd sources in the store:

<img width="1279" alt="missingtab" src="https://user-images.githubusercontent.com/46655/44862365-2a28c700-ac40-11e8-9298-48093f5946c0.png">

And so despite having stored the tab, we never find it because we search by URL and filter out when none is found.

We might be able to experiment with setting the `tab.url` to `getFormattedSourceId(source.id)`for URL-less sources; we'd have to see what can of worms that opens.

**Comment by jasonLaster** [comment]
oh gosh...

**Comment by darkwing** [comment]
We may want to consider the idea of a "TemporaryTab" for eval'd sources; these temporary tabs would be "cleaned up" (removed) from the `prefs.tabs` upon a "NAVIGATE" event.

**Comment by darkwing** [comment]
Hello @Doomwyte!  At present we store tabs in both the redux store and prefs (localStorage).  @jasonLaster had the awesome idea to store the two a bit differently so that tabs without URLs can still be stored in redux but *not* in localStorage.  Check out this diff:

https://gist.github.com/jasonLaster/e64acadbb15d11dd1901179aba85af80

The advantage to making this change is that (1) we don't want URL-less tabs stored in preferences because we can't do anything with them in the future and (2) we can still give them a tab in the UI because, despite not having a URL, they are still a Source.

We can talk more about this in our next video chat, but it would be good to think about in the mean time. 👍
