### ISSUE TITLE
[Search] Sources do not include results from node_modules/

### ISSUE THREAD

**Issue by wkillerud** [devtools-html/debugger.html#5142]
I used the Debugger tool to try to set breakpoints in a module imported from node_modules/, but when I used the Search sources tool (Ctrl + P) that module was not found. The file is listed in the Sources pane, so I can find and open the file manually. 

The project in question was served with webpack-dev-server with source maps turned on.

To reproduce, debug a website with source maps which imports from node_modules/. Hit Ctrl+P and search for a file you expect to be there. You will get 0 results. Tested in Firefox 57 and Nightly with a new profile.

It would be nice if the sources search could include results from node_modules. I noticed #3987 when searching through the issues here that there was talk of excluding these results in Project Search. I couldn't find more details about it so I don't know if anything has been done in this area. [MDN](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Search) doesn't mention any UI to include results from node_modules if they have been excluded on purpose.

**Comment by jasonLaster** [comment]
Thanks @wkillerud, I agree. I think we would like to add an option for including 3rd party libraries. By default, it is pretty slow.

**Comment by wkillerud** [comment]
Opt-in makes sense - most of the time those results would be irrelevant, so better to get a more performant default search :)

**Comment by jasonLaster** [comment]
Looks like there are two places we want to potentially include 3rd party libs `cmd+p` and `cmd+shift+f` search sources & project text search.

**Comment by violasong** [comment]
Cool! While a single icon would look good, I'm not sure if there's a one that communicates this well enough on its own. I think a checkbox with "Include 3rd party libraries" label would be the most usable, though it's pretty long, and probably would need some separator lines:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/55994/35177734-a555d0bc-fd36-11e7-8c19-92f6e8d2eae3.png">

If there will be more search settings in the future, we could replace this with a dropdown menu with checkboxes for the different settings.

**Comment by jasonLaster** [comment]
Thanks, I feel like this could be take up a lot of horizontal space when the editor pane is often pretty narrow.

@AlexisDeschamps brought up an interesting question today. Do you think we should have a global setting for 3rd party libs?

I think @digitarald might have mentioned this too for content scripts as well. Perhaps we have a setting in the sources sidebar? Or a dropdown menu.

**Comment by violasong** [comment]
Ah good point, I always forget about vertical mode! Could put it under the search input instead. Could also do a gear icon that opens a dropdown menu.

**Comment by jasonLaster** [comment]
> gear icon that opens a dropdown menu

This could be awkward in the quick open modal.

---

In the past i was punting on this decision because i was hoping to move project search to the footer of the editor. Once we do that we could have an exclude files input...

https://github.com/devtools-html/debugger.html/issues/3178

---

I'm tempted to do this:

1. search sources always includes the 3rd party files. We can make that fast and fuzzy search is already pretty good

2. we prioritize editor style project search and include the exclude input, which is natural for editors.

**Comment by violasong** [comment]
Ah I see, I wasn't thinking this through enough.

The footer search really slick in Atom - I'm just worried that in DevTools it would be different from all the other panels' top-aligned searches. 

> 1. search sources always includes the 3rd party files. We can make that fast and fuzzy search is already pretty good

Cool, this sounds like a great way forward. Third party results could have some icon or something to show that they're different.

> 2. we prioritize editor style project search and include the exclude input, which is natural for editors.

Would it be weird to keep the top-aligned search UI, but add an exclude input under the search input?

**Comment by wldcordeiro** [comment]
@violasong The goal is to make the project search and in-file search look more like Atom/etc with the footer search. One of the things preventing that was that we wanted to share the search bar in the two so that you have access to the modifiers (case sensitivity, regex, whole word) in project or file search.

I like the idea of having the exclude pattern underneath in the footer style it's very useful in Atom to be able to limit my search to certain directories or exclude others.

**Comment by violasong** [comment]
I think I'm on the same page - I was suggesting we add the exclude pattern input under the search input, but keep both types of inputs near the top of the panel for now. Could be a good intermediate step, and keeps more consistent with the other panels. Some more design work could definitely be done here to make the inputs look better since it looks a little confusing with all the faint horizontal lines right now.
![image](https://user-images.githubusercontent.com/55994/35308701-b3ab2a5c-005d-11e8-936e-03cd4221a081.png)

**Comment by jasonLaster** [comment]
Thanks @violasong i think that makes sense for project text search. For source search, i think we can simplify the top search so it is just source input like atom + code and rely on fuzzy search.

**Comment by jasonLaster** [comment]
cmd+p will soon include node module sources :)
