### ISSUE TITLE
[Sources] Navigation via arrow keys loses focus and resets to last element

### ISSUE THREAD

**Issue by kootoopas** [devtools-html/debugger.html#5270]
So this happened: 🤔 

![sources-tree-focus-last-bug](https://user-images.githubusercontent.com/601001/35641136-ff528ee4-06c7-11e8-81c0-4b9db4606574.gif)

env: high sierra 10.13.1

**Comment by kootoopas** [comment]
tried to replicate on other tabs and it's exactly the same

**Comment by jasonLaster** [comment]
Thanks @kootoopas. What version of firefox are you using?

**Comment by kootoopas** [comment]
No probs. Dev edition 59.0b5 (64-bit).

**Comment by jasonLaster** [comment]
thanks. i think it is actually a case where we show empty files, which have a 0 height. Anyways, i've seen it too. it's rare! but we've got to find a public STR.

**Comment by kootoopas** [comment]
Hah! Probably an extension with an empty file causes this, since I get it on every tab.

**Comment by jasonLaster** [comment]
ooh interesting

try turning off extensions

**Comment by kootoopas** [comment]
aaand it's fixed now

wo/ plugins:
![sources-tree-wo-plugins](https://user-images.githubusercontent.com/601001/35642216-20f6295e-06cb-11e8-86a3-a6b57faf9b7b.gif)

**Comment by kootoopas** [comment]
i suspect that an adblock or privacy extension causes this

**Comment by kootoopas** [comment]
turned off all the plugins :)

**Comment by kootoopas** [comment]
and now enabled'em all again and it's back 🙃

**Comment by jasonLaster** [comment]
haha - can you find which one is doing it?

**Comment by darkwing** [comment]
Steps to repeat:

1.  Start the debugger *but do not open any sources*; click on a folder
2.  Navigate around with keys, all keys work great; focus is never lost, folders open and close appropriately, etc.
3.  Click any source `.js` file
4.  The `left` arrow key starts behaving funny, losing focus *anywhere* until another key is pressed

Notes:

* The problem is introduced when a pretty-printed source is opened, regardless of `devtools.debugger.auto-pretty-print` value

* `$('.sources-list .focused')` returns `null` when the highlight disappears (by pressing the left key), so it's not like a highlighted item is hidden in a folded folder
