### ISSUE TITLE
[SourceTree] The directory root should be saved

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5288]
We should save the root in prefs so that once the user sets it, it will be saved when they close the debugger and re-open it.

**Comment by darkwing** [comment]
Do we have an example of where we're doing this now?  I'd love to see it!

**Comment by AnshulMalik** [comment]
A similar change can be found here https://github.com/devtools-html/debugger.html/pull/2977

**Comment by darkwing** [comment]
Preliminary findings:

1.  We've already tried saving the new root: https://github.com/devtools-html/debugger.html/blob/master/src/reducers/ui.js#L115

2.  One problem I've found is that you need to set the root *twice* before it's actually in `prefs.projectDirectoryRoot` when you reload the page.

3.  Adding the `projectRoot` prop does nothing:

``` js
return <SourcesTree projectRoot={prefs.projectDirectoryRoot} sources={sources} selectLocation={selectLocation} />;
```

The `SourcesTree` component `constructor` gets an empty string instead of that root, even when it's there.  I have no idea why that prop isn't coming through.  Additionally, if I erase all of the props in SourceTree's JSX, everything still "works" -- the tree is rendered -- so any props there seem useless.

4.  Changing the `state` in SourceTree's constructor to this makes the projectRoot finally be respected:

```js
this.state = createTree({
      projectRoot: prefs.projectDirectoryRoot,
      debuggeeUrl,
      sources
    });
```

... but the SourceTree thinks that folder is the main root, so you can right-click and select "Set directory root again", and this time, since the full source address isn't there (because it started as root), you see a "No Sources" message.

There's a lot of work to do with this.
