### ISSUE TITLE
[ProjectSearch] makes tab unresponsive

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#5328]
STR:
- go to http://todomvc.com/
- open debugger
- open project search `ctrl+shift+f`
- type `a`
- press `enter`
- wait for the search to finish (about 40k results)

ER: 
- browser tab is responsive

AR:
- browser tab / browser crashes

**Comment by codehag** [comment]
thanks for reporting this! it sounds pretty bad, we will need to look into it

**Comment by Fischer-L** [comment]
There are 2 bottlenecks here:
1. In `searchSources` action: it would block if searched on multiple large files [1].
2. In `renderResults` in `ProjectSearch` component: it would block as well if rendered a huge amount of matched results [2].

Probably we have to divide search operations, such as if there were 30 files, and we got 300 matched results from the first 5 files, we should pause searching, then went rendering. To search then render over 1000+ matched results is slow as well as a bit overwhelming for people.

[1] [https://github.com/devtools-html/debugger.html/blob/a986a9b1ddba05db0e52a0ca0fff34772ed1e8ad/src/actions/project-text-search.js#L59](https://github.com/devtools-html/debugger.html/blob/a986a9b1ddba05db0e52a0ca0fff34772ed1e8ad/src/actions/project-text-search.js#L59)

[2] [https://github.com/devtools-html/debugger.html/blob/7c0deaaf4cf030f7e9027d10bb4eacb2f5ceda98/src/components/ProjectSearch.js#L255](https://github.com/devtools-html/debugger.html/blob/7c0deaaf4cf030f7e9027d10bb4eacb2f5ceda98/src/components/ProjectSearch.js#L255)

**Comment by jasonLaster** [comment]
- we can exclude 3rd party searching by default
- if it is react we can show 1000 results at a time
- we can limit search so you have to have atleast 3 chars

**Comment by AnshulMalik** [comment]
Here are my findings, I searched for `ab` on http://todomvc.com/ 

<img width="1680" alt="screen shot 2018-05-21 at 12 34 52 pm" src="https://user-images.githubusercontent.com/7821757/40294596-e9d6fd02-5cf3-11e8-88ce-cf87c11c54ad.png">

The profile capture took around 150 sec.
Here are major culprits:
Layout: 130000 ms
Tree Component: 433ms

It's probably because the search results contain very long lines.
<img width="769" alt="screen shot 2018-05-21 at 1 02 40 pm" src="https://user-images.githubusercontent.com/7821757/40295549-5549f816-5cf7-11e8-970f-10c57fbde1ea.png">


I also checked if the data transfer between main thread and worker is taking lot of time. But it's not the case, worker interaction is pretty fast.

**Comment by jasonLaster** [comment]
@AnshulMalik I'd like to see how long it would take to search for `ab` if we just rendered 10 results :)

I think we could get by with showing the top 100 or so and then a show more button...

**Comment by lukaszsobek** [comment]
Maybe we could load the first 20 or so and then infinity scroll?

**Comment by jasonLaster** [comment]
yeah - for sure. We currently dont have infinite scroll and we could do that next.

I believe firefox apz might make that hard... https://hacks.mozilla.org/2017/11/async-panzoom-apz-lands-in-firefox-quantum/

**Comment by jasonLaster** [comment]
actually, i don't know... react virtualized looks pretty great in Firefox. Want to try that in project search? 

https://bvaughn.github.io/react-virtualized/#/components/List

**Comment by darkwing** [comment]
@AnshulMalik's work has vastly improved performance!
