### ISSUE TITLE
Typing filename:linenumber in the File search should navigate me to the file at given line

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5428]
**Steps to reproduce:**
1. Go to http://firefox-dev.tools/debugger-examples/examples/todomvc/
2. Open the debugger
3. Open the File search (<kbd>Cmd</kbd>+<kbd>P</kbd>)
4. Type `todo-view.js:62`

**Expected results:**

The debugger show me the todo-view.js file as a potential result.
And when I press <kbd>Enter</kbd>, I'm taken to todo-view.js, at line 62.
Eventually, it would be nice if `todo-view.js:62:100` would take me to line 62 and column 100.

**Actual results:**
I get a sad red face : 

<img width="172" alt="image" src="https://user-images.githubusercontent.com/578107/36248122-a86ba064-1236-11e8-966e-6574fb3f9296.png">

---

This can be very useful when copying a stacktrace frame. vscode does this quite well.

**Comment by jasonLaster** [comment]
so... it should support line/column jumping. The sad face shouldn't be there :)

**Comment by lukaszsobek** [comment]
A little more insight:
Typing the query does actually seem to produce the desired results. The thing that does not work is pasting the line - it doesn't trigger the onChange event which in turn does not update the query type from `sources` to `gotoSource` and that gives us a modal trying to look for a file that is literally named `test.js:60` instead of trying to go to `test.js` on line "60".
