### ISSUE TITLE
[SourceTree] it should be easy to clear the root

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5448]
At the moment it can be easy to forget that there is a root set. It is also difficult to figure out how to clear the root.

We should solve that problem by showing something in the UI for clearing the root. We've also discussed breadcrumbs, but because the path can be deep i don't know if there is a good way of showing it...

**Comment by lukaszsobek** [comment]
Maybe an icon with a tooltip next to the set root item and the setting available to be cleared via a rightclick menu - the same way it was set.

**Comment by jasonLaster** [comment]
yeah - i think that's right. @violasong thoughts?

**Comment by violasong** [comment]
Oh interesting, I didn't realize this feature existed! It's nice that you can already right-click to clear it, although instead of "Remove directory root" it should probably say something like "Unset as root".  Instead of an icon (since there's already an icon in the row), maybe it could say "(branch)" next to the name of the item, or something more accurate than that? 

...I feel like there may be an existing pattern for this somewhere out there that could help, but can't think of anything at the moment

or .../loading/

**Comment by violasong** [comment]
Or maybe it could be displayed as:
▷ .../directoryname

**Comment by darkwing** [comment]
I love the `▷ .../directoryname` idea!  `..` is a well known symbol that people would recognize and saves us from needing to add a button and/or message somewhere.  Nice @violasong !
