### ISSUE TITLE
[Panes] Arrows in right pane lack spacing

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#5457]
We use arrows to indicate important points in the panes. The indicators in the right panel seem to have lost a bit of spacing. It would be nice to make the spacing uniform with how it looks in the sources pane.

Vid:
![arrows-no-spacing](https://user-images.githubusercontent.com/23530054/36339486-79149b9e-13c7-11e8-81c5-16d064c9cf47.gif)

**Comment by darkwing** [comment]
Appears to only be a Chrome issue.  Firefox on master is ballin':

<img width="298" alt="firefoxmaster" src="https://user-images.githubusercontent.com/46655/36342028-826803f2-13bd-11e8-80a5-b00e7dead005.png">

**Comment by darkwing** [comment]
So the issue here is Firefox supports `margin-line-end` but Chrome doesn't, thus there's 5px spacing that's missing:

<img width="1405" alt="chromearrowsvg" src="https://user-images.githubusercontent.com/46655/36342079-945c0a30-13be-11e8-81d7-e5b0d2390732.png">

Adding `-webkit-margin-end: 5px;` to `.arrow svg` will fix the problem!

**Comment by tomodwyer** [comment]
I've opened a PR in the `devtools-core` repo where this style is set: https://github.com/devtools-html/devtools-core/pull/935

**Comment by darkwing** [comment]
This appears to be fixed in Chrome.
