### ISSUE TITLE
[Breakpoints] 'remove all breakpoints' button on breakpoints AccordionPaneItem

### ISSUE THREAD

**Issue by kootoopas** [devtools-html/debugger.html#5461]
[***EDIT***: I just found out that there's a context menu option to `Remove all` but I still think this is useful to have since it makes its existence obvious]

Proposal
---------

Although it could be dangerous to lose all breakpoints by misclick, say if the button were to be placed really close to the 'toggle all' checkbox on the pane's header, it kind of sucks to manually have to delete each breakpoint when you just want to clear 'em all.

<img width="303" alt="screen shot 2018-02-18 at 2 09 50 pm" src="https://user-images.githubusercontent.com/601001/36351620-9c722f40-14b5-11e8-91b0-59e5080f84d1.png">

Implementation
---------------

Starting points in code:
* add button to breakpoints `AccordionPaneItem`: https://github.com/devtools-html/debugger.html/blob/fa77e0bb471a82fa36e4e144a3a4e97ff4a24e88/src/components/SecondaryPanes/index.js#L195
* `connect()` button with action: https://github.com/devtools-html/debugger.html/blob/fa77e0bb471a82fa36e4e144a3a4e97ff4a24e88/src/actions/breakpoints.js#L227-L234

**Comment by kootoopas** [comment]
It would be a good chance to add a `REMOVE_ALL_BREAKPOINTS` action to the breakpoints reducer too, to make the removal effect in the UI reflect instantly.

As it is now, we have an action that fires `REMOVE_BREAKPOINT` for each breakpoint and we get this serial effect:

![remove-all-breakpoints-delayed](https://user-images.githubusercontent.com/601001/36384219-2fc1f302-1597-11e8-92b5-03c48eed56f4.gif)

**Comment by jasonLaster** [comment]
`REMOVE_ALL_BREAKPOINTS` love this idea

**Comment by jasonLaster** [comment]
yeah... i'm hoping to re-think this pane's ux and add that button then

**Comment by jnachtigall** [comment]
Came here to ask for this feature, nice to see it already open :)

This has bugged for quite some time. When working the breakpoints really fill up (sometimes even over sessions...) 

I always find myself right-clicking on the `Breakpoints` title because I seem to associate the "Remove all" to the title panel and not an individual breakpoint menu item.

I think a consistent way would be to add the trash icon next to the activate/deactivate toggle:

![image](https://user-images.githubusercontent.com/3307404/36475704-cbd37724-16fb-11e8-9b62-4590ee754a64.png)

The trash icon should only be visible if there's is at least one breakpoint set. (I am not using `Watch expressions` a lot, but it might be nice feature there too)

**Comment by jasonLaster** [comment]
Yeah - ideally the checkbox for toggling would be above the other checkboxes. I think we would also have a cog somewhere so you could make it easy to disable or toggle all bps as well... The UX for breakpoints will likely be done in one pass.

**Comment by jasonLaster** [comment]
We're exploring a new breakpoints UI. We're weighing the benefits of a remove all and disable all button

![image.png](https://shipusercontent.com/a8c70ac9a10de67695d9555e74cf7a7a/image.png)

**Comment by jasonLaster** [comment]
closing as this will be tracked as part of the breakpoint ux work

https://docs.google.com/document/d/1DXzoa7cUZJ_z41_QK1I1nPtyexkgGxup7C_at1SCcQs/edit
