### ISSUE TITLE
Extend pretty printing to the html source as well

### ISSUE THREAD

**Issue by yoshimo** [devtools-html/debugger.html#5615]
The html source of a website can become quite hard to read sometimes if the creator uses whitespace excessively and prefer extremely long lines that don't wrap early.
Also comments sometimes are in the middle of source code and interrupt the reading flow. Sometimes that happens on purpose.

Therefore i would suggest to pretty print not only minified JS/Css code but html too.
Remove whitespace and unnecessary line breaks, wrap them to the available screen space and give is an option to hide comments. Maybe move the comment if it is set into a code block on purpose to make it hard to read

**Comment by jasonLaster** [comment]
Thanks for the suggestions @yoshimo. 

I think this is difficult because the debugger is not really oriented around HTML. The reason we show the document is because it has inline scripts. In the future we might just show the individual inline scripts without the document.

I think a better place to see a formatted version of an html file would be the network monitor which shows the resources.
