### ISSUE TITLE
Allow to close a debugger tab with a middle click

### ISSUE THREAD

**Issue by nicofrand** [devtools-html/debugger.html#5640]
Hi,

I am used to close my tabs in my browsers with a middle click on it: it's efficient and does not need me to perfectly target the close button with the mouse.

It would be great if I could close tabs inside the debugger in the same way.

**Comment by lukaszsobek** [comment]
This feature has been implemented in: https://github.com/devtools-html/debugger.html/pull/5402 and is working as intended for me (vid below). The reason we get different results may be because for quality assurance reasons the debugger in firefox itself is a bit behnd the version we have as standalone. So my question would be where you used the debugger - in firefox (prssing ctrl+shift+i) or by cloning the repo and launching it directly. 

Vid:
![close middle](https://user-images.githubusercontent.com/23530054/37195297-7e7f46dc-2372-11e8-9566-0f92cc2df376.gif)

**Comment by nicofrand** [comment]
Hi !

Sorry I did not found this PR nor associated issue. I am indeed using the debugger in firefox, which is probably outdated then.

Thanks for the feature and the answer!
