### ISSUE TITLE
[Scopes] Arrays should be displayed in a less compact way in scopes

### ISSUE THREAD

**Issue by julienw** [devtools-html/debugger.html#5727]
STR:
1. Add a breakpoint in some code where an array is in scope
2. Run the code that stops at this breakpoint
3. Look at this array in the "scope" part of the debugger

=> We always see `[...]` which means we have to unfold it to see its content. We should be able to see more things: the first elements, the length, etc.

Probably we can have a similar display for objects.
See attachment:
![Screenshot](https://user-images.githubusercontent.com/454175/37649627-a4d32f42-2c32-11e8-8c3f-bad018bcbd42.png)

**Comment by jasonLaster** [comment]
Hey @nchevobbe how do you feel about this?

My opinion is that summaries can quickly take up a lot of space. When we add saved expanded state, objects and arrays will stay open as you step which will help.

Also, in the future, I hope to do a better job of letting users choose how to see the variables in their local state.

1. users can have watch expressions pinned to a function so every time they pause they see those expressions
2. we can make it easier to format objects

**Comment by nchevobbe** [comment]
For the arrays, we do have the length displayed: `▶︎ subPath: (2) [ …]`, but yeah, I understand this is not ideal.
We can try the `SHORT` mode, but it's hard to predict how much place it will take, and since we are in a sidebar we don't have much space. What we could try is to only have nodes on a single line with an ellipsis overflow ? At least for all expandable items, so you can still expand them to see the full object.
Would that help @julienw ?

**Comment by julienw** [comment]
I guess it does :)

**Comment by jasonLaster** [comment]
> What we could try is to only have nodes on a single line with an ellipsis overflow

what do you mean?

**Comment by nchevobbe** [comment]
So, instead of using `TINY` modes and having 
`▶︎ subPath: (2) [ … ]`

We'd use `SHORT` mode, but restricted to only a single line to have : 
 `▶︎ subPath:  [ "root", "root/child-1" ]``

Now let's say the properties are really long / the scopes panel really narrow, it would get a bit wild:
 `▶︎ subPath:  [ "this is a very long property name", "yeah I know, i'm even longer than you" ]`

It could wrapped and look weird
 ```
▶︎ subPath:  [ 
"this is a very 
long property 
name", "yeah 
I know, i'm even 
longer than you
" ]
```

To prevent that the nodes will be restricted to a single line when they are expandable: 
 `▶︎ subPath:  [ "this …`

which you can expand: 

```
▼ subPath:  (2) [ … ] 
    0: "this is a very 
long property 
name" 
    1: "yeah 
I know, i'm even 
longer than you" 
```

Is it more clear ?

**Comment by jasonLaster** [comment]
Oh thanks. Wasn't sure.

I'm not really a fan of this:

- it doesn't really give the user more information than they had before
- it clutters the UI quite a bit

Perhaps we could do something on hover where we show a better preview tooltip...

- this would give users quicker feedback
- it might make hovering a bit weird in some cases

I think we should start with keeping the expand state, which will take some of the pressure off of this use case. Then we can come back to scopes/variables ui at a later point.

**Comment by julienw** [comment]
Maybe when displaying arrays in "SHORT" mode, we shouldn't display the full items. The first 5 or 6 characters would be enough. So in your example:

```
 ▶︎ subPath: [ "this is a ve…" ]
```

How does a normal string display in SHORT mode?

We don't need the full string, what we need is having an overview of what's in the array or in the items. If the item is too long, it's fine to cut it, just like we'd do for an array. _But_ I strongly believe it's important to show a part of the first items, like the 3 first items. The goal is to get a feel of what the variables contain.

> Perhaps we could do something on hover where we show a better preview tooltip...

I'm not a fan of this. What I want is having a quick idea of what variables I have here, with a glance to the values. Tooltips don't fit this requirement.

**Comment by jasonLaster** [comment]
what are some examples of objects or arrays you are not sure about that you would like summaries of? I think some real world examples might help.

**Comment by julienw** [comment]
> what are some examples of objects or arrays you are not sure about that you would like summaries of? I think some real world examples might help.

In my case that's arrays of integers. Like `[1, 35, 3953, 4819, 256, ...]`, from 1 to ~100 items depending on the cases.

In my previous comment, I just wanted to give another (and better, I think) solution to the issue @nchevobbe outlined.

**Comment by julienw** [comment]
More exactly, my variable holds an array of arrays of integers.

**Comment by julienw** [comment]
More exactly, my variable holds an array of arrays of integers.

**Comment by jasonLaster** [comment]
moving this to the icebox so we can work on it when we do more pause UX
