### ISSUE TITLE
[QuickOpen] Escape no longer closes the modal

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5800]
STR:

1. open QO via `cmd+p`
2. press `<escape>`

ER: Modal should close
AR: Modal is unaffected

**Comment by darkwing** [comment]
Oddly enough I could make this happen once but then it worked every other time, whether there was a source open or not.

**Comment by jasonLaster** [comment]
nope... not sure how either

**Comment by dimitardanailov** [comment]
Greetings, 

We should discuss this Boolean flag: 

```javascript
if (quickOpenEnabled === true) {
  closeQuickOpen();
}
```

If @wldcordeiro share with us why the Boolean flag is required we could discuss how to restructure the source code.

I was able to reproduce the issue but I can't share which steps are required. 
The issue is very hard for reproduce.

Demo with my success: https://www.youtube.com/watch?v=ew80SQx77CA&feature=youtu.be

**Comment by jasonLaster** [comment]
can we get rid of that block if `closeActiveSearch` does the same thing?

**Comment by darkwing** [comment]
I suggested the same :)

**Comment by dimitardanailov** [comment]
I'll have time on Thursday to play with source code.

> can we get rid of that block if closeActiveSearch does the same thing?
I agree with you.
