### ISSUE TITLE
Scopes - replace Object formatting with Object text

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#594]
We currently format object properties in the scope pane, but it would be nice to just show the text "Object". This is an improvement because formatting the object in the scope pane clutters the pane and does not provide a lot of value when the user can easily expand it on click.

The improvement will likely go [here](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/ObjectInspector.js#L132-L137). 

#### Before
![screen shot 2016-08-26 at 11 07 32 am](https://cloud.githubusercontent.com/assets/254562/18010114/2bd987e8-6b7d-11e6-8f85-4984e90948f7.png)

#### After
![screen shot 2016-08-26 at 11 08 11 am](https://cloud.githubusercontent.com/assets/254562/18010113/2bd9316c-6b7d-11e6-961e-744bd139ffdb.png)

**Comment by wldcordeiro** [comment]
✋

**Comment by jasonLaster** [comment]
go for it

**Comment by wldcordeiro** [comment]
@jasonLaster I noticed that this is the line that does the rendering, but I'm wondering how to inspect the `objectValue` because I can't log it in a way that is useful.

https://github.com/devtools-html/debugger.html/blob/master/public/js/components/ObjectInspector.js#L154

It seems like a pretty straightforward change but I thought I'd need make sure I don't break the view for other item types.

**Comment by jlongster** [comment]
Reps already supports this with a "short" mode, so I would investigate that before doing anything else. I don't have the info off-hand to help right now, but we shouldn't need to this manually.

**Comment by linclark** [comment]
I think you actually want `tiny` mode for this. You can see an example in the [tests](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/components/test/mochitest/test_reps_object.html#83).

**Comment by wldcordeiro** [comment]
Should be closeable.
