### ISSUE TITLE
[failing test] should download a sourcemap and create sources

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#614]
On the `master` branch use `npm run mocha-server`.  Noted this from discussion https://github.com/devtools-html/debugger.html/pull/611#issuecomment-243152669

I'm seeing two intermittent errors

1 for a timeout:

> Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test

2 for an error

> Error: TypeError: sourceMap is undefined (http://localhost:8003/public/build/source-map-worker.js:2700)@:19:5

Looks to be the `actions/tests/sources.js` around 170:
https://github.com/devtools-html/debugger.html/blob/master/public/js/actions/tests/sources.js#L170

In the logs I'm seeing a stack trace that indicates the `createOriginalSources` function in the `source-map-worker.js` file is passing an `undefined` `sourceMap` parameter.  https://github.com/devtools-html/debugger.html/blob/master/public/js/utils/source-map-worker.js#L108-L111  But that is getting that value via the `postMessage` to the worker.  

Also seeing a 404 for the `bundle.js.map` file.  `[log] failed to request http://example.com/test/bundle.js.map`

**Comment by jasonLaster** [comment]
@clarkbw funny that you should report this :)

I'm looking into it as well. I'd like to fix this for a couple of reasons. 

1. it'd be great to run our unit tests locally this way.
2. it's nice to run our unit tests in firefox on CI.

**Comment by clarkbw** [comment]
I believe this issue has gone stale, `npm run mocha-server` no longer seems to run any tests.

**Comment by jasonLaster** [comment]
Hmm, i agree that this test has gone stale as we haven't had time to work on it.

I ran `npm run mocha-server` recently and found it really helpful to run other tests.

There *are* lots of failing UI unit tests too, which we haven't kept up to date. My theory is when this test failed, instead of turning it off in the web context we turned off the web unit tests, which is much worse :) because now we have other stale tests
