### ISSUE TITLE
Unclear cursors on breakpoint panel should be pointers

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6268]
Filename shows a default cursor. Breakpoint code preview has a text cursor.

Both are actually clickable for file navigation and should have a pointer cursor.

**Comment by darkwing** [comment]
Thanks for filing this @digitarald; I'm of the school that anything clickable should have the "pointer" cursor, but that doesn't appear to be the standard for DevTools as a whole.  For example, seemingly the only thing in the debugger with a pointer cursor is the SourcesTree; everything else, clickable or not, has the default cursor, including:

- Editor Tabs
- Functions that appear in the Outline tab
- Close buttons, everywhere
- Accordion headers
- Watch expressions
- Breapoints
- Gutter buttons

When I look at other DevTools, like Performance, Memory, and even the DevTools heading bar itself, clickable buttons and "symbols" have the default cursor.

I think we as a larger DevTools team need to have a standard rather than picking out individual places where our opinion is that it should be pointer.  Or maybe I'm out of the loop as to what that standard is.  Thoughts?

**Comment by wldcordeiro** [comment]
I remember at some point we started putting the clickable cursor and then that was undone for leaving defaults. I think we should go further than just that one type of cursor and think about where we could use the various context sensitive cursors for disabled elements, etc.

**Comment by digitarald** [comment]
> I think we as a larger DevTools team need to have a standard rather than picking out individual places where our opinion is that it should be pointer.

Luckily designers and a11y experts but a lot of thought into this already. We should not block this on not having a consistent pointer rule across devtools.

The rule of thumb that I'd propose, partially based on [MS's weak affordance](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742466(v=vs.85).aspx) model:

1. UI that looks interactive don't need a pointer.
2. Interactive elements with weak affordance benefit from pointers and hover states as well.

fyi @violasong
