### ISSUE TITLE
breaking [mochitests]

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#636]
Sub task of the All the mochitests! #634 issue

DXR search for many of the files:
[dxr.mozilla.org: path:devtools/client/debugger/test/mochitest/ file:dbg_break-](https://dxr.mozilla.org/mozilla-central/search?q=path%3Adevtools%2Fclient%2Fdebugger%2Ftest%2Fmochitest%2F+file%3A*dbg_break*&redirect=true)

All the files that matter to this issue:

browser_dbg_break-in-anon.js
browser_dbg_break-on-next-console.js
browser_dbg_break-on-next.js
browser_dbg_break-unselected.js
browser_dbg_console-eval.js
browser_dbg_console-named-eval.js
browser_dbg_debugger-statement.js
browser_dbg_breakpoints-break-on-last-line-of-script-on-reload.js
browser_dbg_breakpoints-button-01.js
browser_dbg_breakpoints-button-02.js
browser_dbg_breakpoints-condition-thrown-message.js
browser_dbg_breakpoints-contextmenu-add.js
browser_dbg_breakpoints-contextmenu.js
browser_dbg_breakpoints-disabled-reload.js
browser_dbg_breakpoints-editor.js
browser_dbg_breakpoints-eval.js
browser_dbg_breakpoints-highlight.js
browser_dbg_breakpoints-new-script.js
browser_dbg_breakpoints-other-tabs.js
browser_dbg_breakpoints-pane.js
browser_dbg_breakpoints-reload.js
browser_dbg_bug-896139.js

**Comment by jlongster** [comment]
I think we have enough tests to cover most of these cases. There are still ones we don't cover but the point of these bugs was to make sure we weren't missing anything crucial. Closing this because I've looked through these tests and all the ones we don't have are pretty straight-forward and mostly related to features we don't have.
