### ISSUE TITLE
source maps [mochitests]

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#647]
Sub task of the All the mochitests! #634 issue

browser_dbg_source-maps-01.js
browser_dbg_source-maps-02.js
browser_dbg_source-maps-03.js
browser_dbg_source-maps-04.js

[DXR search](https://dxr.mozilla.org/mozilla-central/search?q=path%3Adevtools%2Fclient%2Fdebugger%2Ftest%2Fmochitest%2F+file%3A*dbg_source-maps*&redirect=true)

**Comment by jlongster** [comment]
I spent a couple hours with souremaps today, and I don't think we can realistically land with sourcemaps by the end of this weeks. It doesn't work reliably enough and it takes some work to get it working with the native panel's network request. I bet we can turn it on soon, but I'd say let's focus on other stuff for now.

In that light, let's close this issue. When we finalize sourcemaps, that PR should include the relevant mochitests.

**Comment by jasonLaster** [comment]
I think this makes sense, it's better to focus on a smaller subset. I'm re-opening the issue though and moving to the next sprint as we'll want to pick it up again soon.

**Comment by jlongster** [comment]
We can't write mochitests for sourcemaps until we turn them on. I have written a mochitest for sourcemaps (which isn't running because in testing sourcemaps are disabled), but we will write more when we enable them, which I'm hoping is later this week.

I think it's OK to move this to the next sprint, as the above tests do handle a few cases we need to make sure to test.
