### ISSUE TITLE
Wasm: TypeError: binary is undefined

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6493]
In the `src/utils/source.js` file's `getSourceLineCount` function, `source.text` is an `I.Map` and so `const { binary } = (source.text: any);` errors; it needs to be `source.text.get("binary")`

**Comment by darkwing** [comment]
Another side effect is breakpoints not displaying:

<img width="1043" alt="wasmbreakpoints" src="https://user-images.githubusercontent.com/46655/41178121-efeaafe0-6b2b-11e8-8670-943490331f4d.png">

**Comment by jasonLaster** [comment]
hmm, i wonder why Text is a Map? 

perhaps we need to extend the Record class. Also if this the case we should update the Source flow type so it is clear this is a valid type

**Comment by janodvarko** [comment]
@darkwing I can't reproduce the issue. I don't see the TypeError and the `source.text` is always an object with `binary` prop for me (in WASM). Any special STR appart from just hitting a breakpoint in WASM module?

I see another bug that might be related, though. Stepping in WASM is broken for me due to an error on this line:
https://github.com/devtools-html/debugger.html/blob/master/src/actions/pause/commands.js#L157

const lineText = source.text.split("\n")[line - 1];

`source.text` can be an object. 
(btw. I thought that `source.text.toString().split("\n")[line - 1];` would fix it, but it doesn't)

Is it related?
It was working recently, no?

Honza

**Comment by darkwing** [comment]
I believe that some of @jasonLaster's removing-immutable-from-sources may have remedied this issue.

**Comment by jasonLaster** [comment]
also @yurydelendik might have fixed this when adding the test

**Comment by janodvarko** [comment]
I see, ok. 

The stepping in WASM issue is still there (see my comment). Should I file a new bug for it or keep this one opened?

Honza

**Comment by janodvarko** [comment]
I am closing this issue since the original report `Wasm: TypeError: binary is undefined` has been fixed.

But, I have created two follow ups:
* Stepping broken in WASM module #6569
* Breakpoints in WASM module are not visible in Breakpoints panel #6570

Honza
