### ISSUE TITLE
[Editor] syntax highlighting flashes when stepping

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6507]
STR: 
1. go to https://dbg-class-prop-this.glitch.me/
2. set a breakpoint in onSortClick
2. add a breakpoint in `utils/pause/mapScopes/index.js#309`
3. click "cycle" button and pause

Notice how syntax highlighting is broken on pause and then flashes when stepping

![](http://g.recordit.co/XZbRvAqzod.gif)

**Comment by janodvarko** [comment]
More information for anyone interested in fixing this bug:

More precise STR:

1. Load https://dbg-class-prop-this.glitch.me/
2. Open Debugger in a new tab (http://localhost:8000) and attach it to the page created in step 1
3. Create a breakpoint in HelloWorld.onSortClick (app/components/HelloWorld.jsx)
4. Open DevTools Toolbox in the tab with the Debugger.
5. Create a breakpoint in src/utils/pause/mapScopes/index.js#309
6. Click `cycle` button in the page created in step 1
7. The breakpoint created in step 2 should hit
8. The breakpoint created in step 5 should hit
9. Now step over in DevTools Toolbox 

There are two issues:
- Notice how syntax highlighting is broken on pause 
- Syntax highlighting flashes when stepping over

The syntax highlighting issue seems to be related to CodeMirror. You can load the index.js file separately, use the Network panel to lookup the corresponding request and see the Response side panel. It also uses CodeMirror and it's also broken.

![image](https://user-images.githubusercontent.com/37785/41958826-7efc905e-79eb-11e8-89f7-2358556a3c22.png)

The second issue is related to the way how code mirror mode is set in `showSourceText` see the [source](https://github.com/devtools-html/debugger.html/blob/master/src/utils/editor/source-documents.js#L132)

When the document is created for the first time the `mode.name` is `javascript`. There are no `symbols` at this point and mode name is calculated according to the [content type](https://github.com/devtools-html/debugger.html/blob/master/src/utils/source.js#L316). Later when stepping happens and the location is updated `showSourceText` is executed again (with `symbols` argument present) and `getMode` returns `text/typescript` since `symbols.hasTypes` is [true](https://github.com/devtools-html/debugger.html/blob/master/src/utils/source.js#L267) 

Since the Code Mirror mode name changes the parsing happens again and its content flashes.

Remembering the new mode name in the cached source doc after setting the new mode fixes the issue. But, perhaps there is different and related hidden problem.

```js
editor.setMode(mode);
doc.mode.name = mode.name;
```

Honza

**Comment by janodvarko** [comment]
Fixing this issue might have positive impact on stepping performance since it avoid updating syntax highlighting when stepping.

Honza

**Comment by jasonLaster** [comment]
Thanks, it would be nice if we updated the mode when symbols were populated and then, we didn't update it after that :)
