### ISSUE TITLE
[breakpoints] shift clicking a breakpoint should not highlight the line

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6554]
STR:
1. open the debugger
2. select a file
3. click a line in the gutter to add a bp
4. shift click the bp 

The editor should not highlight that line

![](http://g.recordit.co/Qey5jbQZhE.gif)

I think this should fix it, but it needs testing

```diff
diff --git a/src/components/Editor/index.js b/src/components/Editor/index.js
index 225a560..ae1fbf0 100644
--- a/src/components/Editor/index.js
+++ b/src/components/Editor/index.js
@@ -349,6 +349,9 @@ class Editor extends PureComponent<Props, State> {

     const sourceLine = toSourceLine(selectedSource.get("id"), line);

+    ev.preventDefault();
+    ev.stopPropagation();
+
     if (ev.altKey) {
       return continueToHere(sourceLine);
     }
(END)

```

**Comment by sharathnarayanph** [comment]
@jasonLaster I tried reproducing this in the latest code base and it seems to work fine. Though this issue exists in the browser debugger, in the web app it looks intact. Am I missing something?

![shiftbp](https://user-images.githubusercontent.com/16179366/42125338-6f3c0ef2-7c92-11e8-8c70-090bce79bf84.gif)

**Comment by jasonLaster** [comment]
maybe not... take a look at the code in master and let me know if you see the logic to prevent it.

**Comment by jasonLaster** [comment]
hmm, it looks like it is still happening in Nightly with the latest code.

**Comment by darkwing** [comment]
@jasonLaster Your suggested event fix at the top of the ticket doesn't prevent the issue in panel, so we need to look elsewhere :(

**Comment by jasonLaster** [comment]
Thanks

**Comment by yogmel** [comment]
Hi people!
Can I work on this issue? I'll read through the documents, but if you have any good starting point (.js file to look at or tip) that would be great!
Thanks!

**Comment by yogmel** [comment]
Hi @jasonLaster , thanks for the advice!
I have been working on it today and the bug probably lives in the Breakpoint.js file.

I've compared both the web app and the build codes and this line is different from each other:
- Firefox build:68
```javascript
const line = (0, _editor.toEditorLine)(sourceId, breakpoint.location.line); 
```

- Launchpad:54
```javascript
const line = toEditorLine(sourceId, breakpoint.location.line);
```

I'll keep on investigating and if I find something I'll let you know!

**Comment by jasonLaster** [comment]
@yogmel that difference is due to the fact that we compile it with babel before it lands. it shouldnt make a big difference.

**Comment by yogmel** [comment]
Hi all,

I'm so sorry for the delay.
I realized that Breakpoint.js was fine and the problem was happening in the **codemirror.bundle.js**.
There is a custom .js file that is inserted there, that is **editor.js**.

On line 429 I found a very well-commented code:
![image](https://user-images.githubusercontent.com/3901809/47099700-3b3b9080-d20c-11e8-8772-d04616790356.png)
I have commented 430 - 433 lines. I built Firefox again and that seems to have solved the problem!

I just don't know to record a gif to show you. But I can tell the instructions here:
The path to the file is:
**mozilla-central > devtools > client > sourceeditor > editor.js**

On line 429, you should see a comment:
```javascript
// Shift-click on a gutter selects the whole line.
```

After that, there is an if statement that is causing this behavior.
