### ISSUE TITLE
Should the center pane header also be visible?

### ISSUE THREAD

**Issue by jlongster** [devtools-html/debugger.html#662]
Currently the header in the middle section goes away if you don't have any tabs open. I feel like it should always stay visible and the welcome screen should exist below it. That way it's always consistent.

Don't feel strongly about it though, if we don't want to do it now we can close this issue and punt for later.

**Comment by clarkbw** [comment]
I agree it should always be visible and then we could use it to hold the collapse buttons for the sidebars.

**Comment by wldcordeiro** [comment]
I think always visible makes sense and as @clarkbw mentioned we can house the collapse buttons there, I'll be updating #623 this week to do so (weekend has been busy with family birthdays and weddings of friends eating all my time.)

**Comment by helenvholmes** [comment]
Added the header pane back in PR #663, seems like a solid idea (particularly because of the collapse/expand buttons).

Should we discuss entry states a bit? Originally the empty state was about education. Now that we're moving the key command label into the top of sources in #622, should the empty, no-files-open state be the Cmd+P state, instead of two separate states?

Empty state:
https://cl.ly/443837143A24

Cmd+P state:
https://cl.ly/2a0v1I233A3C

If so, should we consider a tab, like Sublime Text does?
https://cl.ly/14083S1f003l

(In that last screenshot: wording needs to be finessed quite a bit. I'm not sure what the greek text should be.)

**Comment by jasonLaster** [comment]
Hmm, I'm hesitant to do too much work on the center pane at the moment as we haven't flushed out the search / discovery story yet.

We'd like to have project text and symbol search added soon.

I also think we could use this space in an interesting / different way after we have done some exploration into user flows in Q4. My hope is that we can provide more of a birds eye view or jumping off point. Also, I think our UI has a lot of assumptions built in on how we want to use the left and right sidebar which might be something we experiment with.

If we do adopt a more plugin oriented architecture in Q4 with some of these partnerships, that will inform how we use this space as it might be valuable or very different in other contexts.
