### ISSUE TITLE
Scroll position of the next tab opened depends on the first

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#674]
STR:
- make sure you just opened the debugger and there are no files opened yet in it,
- open one file (a new tab should appear),
- scroll down to the bottom,
- now open a second file (a new tab should appear too),
- notice how this second file is scrolled down to the bottom.

![tabs](https://cloud.githubusercontent.com/assets/1152698/18304534/265bb48e-74e3-11e6-9d99-e43a7585919b.gif)

**Comment by jasonLaster** [comment]
Great find. 

We're re-using the same document and resetting the text, so it makes sense that we would run into this problem. In the short-term we should scroll to the top in `Editor.setText`. In the long term we should implement one document per source tab, so that we can quickly toggle between sources and maintain scroll position.
