### ISSUE TITLE
stepping bug: debugger skips to the end of the function

### ISSUE THREAD

**Issue by jbhoosreddy** [devtools-html/debugger.html#6761]
AR: The debugger skips to the end of the function
ER: The debugger pauses on line 51
![](http://g.recordit.co/Hgs4kRg2Ge.gif)

**Comment by jasonLaster** [comment]
Okay, so this bug is pretty wild:

1. we get the pause points for the original code
2. we do not get the pause points for the generated code (bundle)
3. we pause here via the server `const /*here*/breakpoints`
4. the client sees that this is an original location with an empty pause point and says, i dont want to pause there
5. the server continues to the next line

```js
export function getVisibleBreakpoints(state: State) {
  const selectedSource = getSelectedSource(state);
  if (!selectedSource) {
    return null;
  }

  const breakpoints = getBreakpoints(state);
  const visibleBps = breakpoints.filter(bp => isVisible(bp, selectedSource));
  return visibleBps.map(bp => formatBreakpoint(bp, selectedSource));
}
````

There are two options:

1. parse the bundle
2. make  `const /*here*/breakpoints` a step point

**Comment by jbhoosreddy** [comment]
@jasonLaster I legit spent a day trying to figure out what was going on here.

**Comment by jasonLaster** [comment]
Yea - this is a wild one. I'll be talking to Jim about it tomorrow at 11:30am ifyou're free
