### ISSUE TITLE
[Editor] highlights  selected line on reload

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6789]
STR:

1. pause somewhere
2. refresh

ER: see the source
AR: see the source and see the old pause location highlighted

![](http://g.recordit.co/qYa0mYmi6m.gif)

**Comment by darkwing** [comment]
This is happening because of `HighlightLine.js`'s `setHighlightLine` function; the conditionals in `setHighlightLine` and `shouldSetHighlightLine` aren't preventing this from happening on initial load.  A few notes:

## setHighlightLine

* `selectedLocation` does have a value: 
```js
column: 0
line: 4
sourceId: "server1.conn0.child1/source25"
url: "https://d2zah9y47r7bi2.cloudfront.net/releases/current/tracker.js"
<prototype>: {…}
```
* `selectedFrame` has a value:

```js
id: "server1.conn0.child1/frame164"
location: {…}

column: 21856
line: 1
sourceId: "server1.conn0.child1/source34"
```
* `selectedSource` is the source of the opened tab

Upon load, if there's no breakpoint, there shouldn't be a selectedFrame, should there?

**Comment by kenjiO** [comment]
I think this is happening because [paused.js](https://github.com/devtools-html/debugger.html/blob/020dbd9af2bad4a5f683256c5d5606184ce4e256/src/actions/pause/paused.js#L75) calls [selectLocation](https://github.com/devtools-html/debugger.html/blob/020dbd9af2bad4a5f683256c5d5606184ce4e256/src/actions/sources/select.js#L95) which dispatches `SET_SELECT_LOCATION` with the paused location including the line number.  Then in the [reducer](https://github.com/devtools-html/debugger.html/blob/020dbd9af2bad4a5f683256c5d5606184ce4e256/src/reducers/sources.js#L88) it sets `prefs.pendingSelectedLocation` to the currently paused file and line number.  When the page is refreshed it retrieves `prefs.pendingSelectedLocation` and gets the file with line number which it highlights.

Is there a need to save the line number in `prefs.pendingSelectedLocation`?   A simple fix would be to not save the line and column numbers in `prefs.pendingSelectedLocation`.
