### ISSUE TITLE
Add ability to turn on/off sourcemaps in the UI

### ISSUE THREAD

**Issue by jlongster** [devtools-html/debugger.html#685]
We need to work on how to manage settings for the debugger. The most crucial setting is sourcemaps: it's very common to turn off sourcemaps when they are just not working (could be the sourcemap's fault, not our implementation). Adding a way to toggle them would be great. Maybe we don't even need to make a whole settings panel, but turning on/off sourcemaps could be first-class as a button somewhere, I don't know.

**Comment by clarkbw** [comment]
Maybe for now, we could add a toolbar that matches the editor to the bottom of the sources panel with the option to turn off source maps.  

__yellow for emphasis__

![screen shot 2016-09-07 at 12 55 54](https://cloud.githubusercontent.com/assets/2134/18326419/7f9ec1fa-74fa-11e6-8f18-db4eb716642a.png)

But this is for @helenvholmes to figure out.

**Comment by jlongster** [comment]
That's a neat idea. I like the idea of embracing the fact the sourcemaps are easily faulty and making it easy for the user to flip them on/off. It's worth trying something like that and see what user think about it.

**Comment by helenvholmes** [comment]
I actually think it might fit better here, since there's a) already a bar b) that sources sidebar normall is half that height and has a lot of things in it:

<img width="727" alt="screen shot 2016-09-07 at 4 20 23 pm" src="https://cloud.githubusercontent.com/assets/1720093/18327118/02c907ea-7517-11e6-9ed5-4b84061f364d.png">

I should stress I think this is more of a temporary fix, though. As features to the debugger get added I imagine we're going to need this submenu again:

<img width="349" alt="screen shot 2016-09-07 at 4 22 07 pm" src="https://cloud.githubusercontent.com/assets/1720093/18327166/3fe5e49a-7517-11e6-843a-90c3a34545ee.png">

I'm working on some more holistic designs for Settings, but I don't think they will make that submenu go away.

Debugger submenu: relatively quick actions that don't need UI, "Edit List" as last item
Settings: hitting "Edit List" deeplinks to Debugger section of Settings

**Comment by jlongster** [comment]
It might be worth going ahead and bringing back back that three-dot menu with a single item under it, not sure. That's still a pretty accessible place to toggle them.

**Comment by jasonLaster** [comment]
I think the submenu is probably the best place to add some quick settings:

I see the source footer as a place for a single source's actions: pretty print, black box, maybe search...

I think the sources sidebar could work for source maps, but i agree that it could get busy

**Comment by clarkbw** [comment]
If we want more than a temporary fix I'd suggest we focus on the intent of usage.  If we don't feel that a user should need to toggle this during a session but we want the option available just in case I think we want this hidden, like in a submenu.  If we feel a user should need to toggle this regularly we might want to make the option more visible in the UI, like in a toolbar.

**Comment by helenvholmes** [comment]
I second what @clarkbw says; I brought this up to @jlongster yesterday as well. Without knowing use cases/the way people are toggling and using source maps, I don't know where they best belong. I hesitate to put them somewhere when we ultimately might move them.

James made sourcemaps and turning them on and off was an action people do with some regularity, which surprised me. (I thought they were infrequent actions.)

We could potentially also introduce a key command for it, and not have the UI for it front and center.

**Comment by jlongster** [comment]
Having key commands for the settings in the menu sounds like a cool idea, if there are keys available.

I'm not exactly sure how frequent it is, maybe others don't use it like I do. But sourcemaps have enough problems that we should make it easy to turn off, but I'm fine with a submenu. Might be good to get feedback from others on this.

**Comment by jasonLaster** [comment]
> I'm not exactly sure how frequent it is

I think this is tough to estimate because the old debugger would force you to choose. The new debugger, which is like chrome's allows you to see both the bundle and the original sources. 

Assume I want to view line 1234 in the bundle, that is still possible with source maps on. Another example is adding breakpoints. It is still possible to add a breakpoint to line 1234 in the bundle with source maps on.

I think it's useful to be able to toggle the modes, but I don't think it's so common that it deserves a key command or a more prominent location.

One cool feature would be a context menu option to view the original location or view the generated location. This would make it easy for people to understand the mapping that is going on and if they're transpiling, set more granular breapoints in the generated source.

**Comment by jlongster** [comment]
That's true, we will make it easier to use even when sourcemapping goes wrong. We need to figure out all these workflows. I suspect we'll still want the ability to globally turn it off, because we'll always prioritize sourcemapped code, i.e. if stepping into a function we'll pull up the sourcemapped version first. Sometimes you just want to step through the generated code. Also, this affects other tools; turning sourcemaps off will disable sourcemaps everywhere, so console isn't sourcemapped and clicking on locations takes you to generated locations.

I hadn't thought about it being a toolbox-level feature before, and maybe that does impact the UX of this feature. Maybe it does just need to be a global setting in the toolbox settings menu, and we won't have to turn them on/off as much because we can provide better interacts between original/generated now.

**Comment by jasonLaster** [comment]
> toolbox-level feature

I hadn't made that leap either, but that makes a lot of sense

**Comment by clarkbw** [comment]
> Maybe it does just need to be a global setting in the toolbox settings menu,

This makes a lot of sense to me now that we're talking about the sources view separation and this as a toolbox level feature.  We should coordinate with the console on this when we come back around to source mapping.  I suspect they might want an option inline to at least toggle views given that they don't currently have an easy way to show both values like the debugger does.  Perhaps that could just be a local option vs a more global toggle in toolbox settings.

**Comment by clarkbw** [comment]
Are we still doing this?  I feel like the consensus was that we didn't need it anymore; except possibly as a toolbox level setting.  Even then I'm unsure if its necessary.

**Comment by jasonLaster** [comment]
@helenvholmes? do you feel like the settings can handle this?

**Comment by clarkbw** [comment]
This issue is a bit confusing, I believe we landed on doing something like this

<img width="919" alt="screen shot 2016-09-27 at 11 45 06 am" src="https://cloud.githubusercontent.com/assets/2134/19392676/abcda2ec-91e6-11e6-82eb-daef5aa64d28.png">

Which requires some small design work and a bugzilla bug opened.

**Comment by jlongster** [comment]
Yep, Jason has a bug in bugzilla to do that but I can't find it right now.

**Comment by clarkbw** [comment]
@jasonLaster what's the bug number for this work?

**Comment by clarkbw** [comment]
> what's the bug number for this work?

The bugzilla bug for this has already landed and the rest of the work is being tracked in #879

**Comment by clarkbw** [comment]
@jasonLaster is this issue finished now?  #879 was merged in

**Comment by jasonLaster** [comment]
Yup
