### ISSUE TITLE
[sources] source tree loses focuses when new items are added

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6864]
STR:

1. go to https://www.cnn.com/
2. reload
3. click on items in the source tree

ER: it stays focused
AR: it loses its focus

![](http://g.recordit.co/5p3dz8Sdk5.gif)

**Comment by jasonLaster** [comment]
so this looks related...

```diff
diff --git a/src/utils/sources-tree/updateTree.js b/src/utils/sources-tree/updateTree.js
index 14a1036..040e8a6 100644
--- a/src/utils/sources-tree/updateTree.js
+++ b/src/utils/sources-tree/updateTree.js
@@ -51,7 +51,7 @@ export function updateTree({
   return {
     uncollapsedTree,
     sourceTree: newSourceTree,
-    parentMap: createParentMap(newSourceTree),
-    focusedItem: null
+    parentMap: createParentMap(newSourceTree)
+    // focusedItem: null
   };
 }
```

**Comment by WenInCode** [comment]
I'm going to start looking into this one after work :)
/claim

**Comment by WenInCode** [comment]
I just wanted to give an update on where I am at with this. I didn't get a chance to do much work on it last week, but I've been a bit more active this week. 

As @jasonLaster pointed out the issue is that when the tree is updated we return the state with `focusedItem` set to `null`. However, if we were to remove that setting altogether, and leave `focusedItem` as it were before updating the tree it would still lose focus. That's because when the tree is adding nodes, it checks [if the current node is focused](https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-components/src/tree.js#L778) by doing a `focused === item` comparison. I'm no expert on coercion, but I _think_ that equation doesn't return `true` with objects unless they are a reference to the same object.

If I were to change the check to just compare paths, and not the entire object, you could just leave `focusedItem` as unchanged in the state. This seems to perform fine in the case where new sources are being loaded on the same page. However, I don't think it would make sense if you were loading a new page and the previous `focusedItem` would no longer be in the tree.

This is leading me towards keeping the equality check the same, but searching for the `focuseditem` in the new source tree after or during the `updateTree` call. I think I would have to use something similar to [traverseTree](https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-components/src/tree.js#L778) to search for the node given the path. Of course, without creating a new node.

Anywho, just wanted to give an update on my thoughts. This has been a great opportunity for learning how the `SourcesTree`, `ManagedTree`, `Tree`, and `TreeNode` components work.

**Comment by jasonLaster** [comment]
@WenInCode i think you've got a good idea of what's going on.

CC @AnshulMalik curious what you think. Please go deeper than I did and give some suggestions on how you'd approach this :)

**Comment by WenInCode** [comment]
> However, I don't think it would make sense if you were loading a new page and the previous focusedItem would no longer be in the tree.

I was incorrect about this wrt new pages. If the new `debuggeeUrl`is not the same as the current one, we create a new tree altogether, which returns the `focusedItem` as `null`. I'm curious if we can get away with changing the equality check and skipping searching through the tree altogether. Going to play around with it.

**Comment by AnshulMalik** [comment]
Hey @WenInCode you are knocking at the right door. :)

The issue is I think in https://github.com/devtools-html/debugger.html/blob/master/src/utils/sources-tree/collapseTree.js#L14. So when new sources arrive, we take the previous `uncollapsed` tree and create a new `collapsed` one. In the process we are not using the existing nodes, rather we create new ones. That's why the `===` check on focusedItem reference does't return true.

I have two workarounds in mind, 
1. We can reuse the nodes from previous collapsed tree.
2. You have mentioned it in your comment, that use path of currently focused item, to find the new node that we should focus. We can directly jump directories if we split the path of currently focused item, so probably won't need to traverse the whole tree.

Let me know what you think @WenInCode @jasonLaster

**Comment by WenInCode** [comment]
@AnshulMalik Thanks for the information 😄. I have some good progress on the 2nd option. I'm hoping to have a PR up soon.
