### ISSUE TITLE
Preview tooltip shows undefined for XMLHttpRequest

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/debugger.html#6871]
STR:

1) Load http://janodvarko.cz/firebug/tests/601/Issue601.htm
2) Open issue601.htm file and create a breakpoint on line 50
3) Click the POST button on the page
4) After the breakpoint hits, move mouse over `XMLHttpRequest` (line 49) - the tooltip says `undefined()` -> BUG

It could at least say `XMLHttpRequest()`.

Honza

**Comment by jasonLaster** [comment]
It looks like that the issue is in the server grip side with `XMLHttpRequest` it should have a displayName or name field. It is also missing a parameter names field as well. 

We could paper over this by showing the expression in the tooltip, but I'd prefer to fix the root cause and report the proper values for native classes.

<img width="651" alt="screen shot 2018-08-23 at 10 06 18 am" src="https://user-images.githubusercontent.com/254562/44530391-3c44bb80-a6bc-11e8-924d-b5b8489c7878.png">
<img width="653" alt="screen shot 2018-08-23 at 10 06 04 am" src="https://user-images.githubusercontent.com/254562/44530392-3c44bb80-a6bc-11e8-9414-c7455bd54c6e.png">

**Comment by janodvarko** [comment]
Bugzilla bug reported:
https://bugzilla.mozilla.org/show_bug.cgi?id=1485941
Honza
