### ISSUE TITLE
Enable resizable column headers in the Network tab

### ISSUE THREAD

**Issue by dangdennis** [devtools-html/debugger.html#7120]
Is it within the realm of product direction to have the column headers within the Network tab and alike be resizable on the x-axis? 

I like to quickly review the file names and assets.
<img width="515" alt="screen shot 2018-10-20 at 2 54 45 pm" src="https://user-images.githubusercontent.com/22418429/47260866-47c42100-d478-11e8-823e-3ed3117936e2.png">

Example: `File` tab's left and right edge can be dragged to resize.

**Comment by janodvarko** [comment]
This repo is dedicated to Debugger, so I am closing this report since it belongs to Network monitor component. 

Any further reports related to the Network monitor panel should be done here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Netmonitor

Good new is that there is already a bug report for resizeable columns and we are planning to work on it in Q1/2019

https://bugzilla.mozilla.org/show_bug.cgi?id=1463423

Honza
