### ISSUE TITLE
[Console] keyshortcuts like stepIn should work when the console is focused

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#717]
STR:
- pause
- open the console
- focus on the terminal
- hit F10 (step over)

nothing happens

The old keyboard shortcuts are in the toolbar view - https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/views/toolbar-view.js#55-60

new shortcuts are in the RightSidebar https://github.com/devtools-html/debugger.html/blob/master/public/js/components/RightSidebar.js#L91-L95

It's likely a question of event bubbling which might be stopped here or somewhere like this

https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#689-711

**Comment by juliandescottes** [comment]
The split console and the debugger live in separate iframes. If you use the key-shortcut API, you would need to set the shortcuts on a parent window that contains both the debugger and the console.

In the old debugger, we are using a toolbox API (useKeysWithSplitConsole) to forward some debugger shortcuts to the toolbox window when the splitconsole is focused:
- https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/panel.js#57
- https://dxr.mozilla.org/mozilla-central/source/devtools/client/framework/toolbox.js#570

useKeysWithSplitConsole takes care of attaching the shortcuts to the topmost devtools window, but calls the handlers only if the splitconsole is opened and the selected tool is the one for which the shortcut was registered. 

In https://bugzilla.mozilla.org/show_bug.cgi?id=1297113 , I am migrating this API to use key-shortcuts.js instead of XUL <key> elements. At the moment, the plan is to keep this useKeysWithShortcut API, but since the old debugger is the only user of this API, that could change if you have another implementation in mind here.

@jasonLaster thoughts?

**Comment by jasonLaster** [comment]
Thanks @juliandescottes. I think the `useKeysWithShortcut` makes sense, we want to be able to handle these shortcuts in the debugger and will need a way to proxy them over.

**Comment by clarkbw** [comment]
[bug 1297113](https://bugzilla.mozilla.org/show_bug.cgi?id=1297113) landed, is this still an issue @jasonLaster @juliandescottes ?

**Comment by juliandescottes** [comment]
@clarkbw I think this is still needed. 

The new debugger frontend needs to use `toolbox::useKeyWithSplitConsole` in order to forward some key shortcuts to the split console.

**Comment by jasonLaster** [comment]
@julienw i added you this issue for when you get back. Let me know if you are interested.

**Comment by julienw** [comment]
I'm not working on the debugger these days so unassigning :)

**Comment by codehag** [comment]
closing and adding to the feature backlog
