### ISSUE TITLE
[breakpoints] text overflows when you hover on it

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#7184]
When the line number is 3 or 4 digits, the close button is narrow enough to change the overflow of the breakpoint text.

![](http://g.recordit.co/I835qGxgnJ.gif)

**Comment by akashs09** [comment]
I am thinking of something like changing the max-width to a smaller value for the label element under the breakpoint class. Since it is a calc() property and upon resizing when you hover over it will recalculate the max-width value lowering it from 100% to 95% it does not affect the width (~0 px added) but still similar to the box model layout of 100%.

Supposed Change:
`max-width: calc(95% - var(--breakpoint-expression-right-clear-space));`

![max-width 95](https://user-images.githubusercontent.com/11323463/48036181-36943900-e135-11e8-9715-294790713640.gif)

**Comment by jasonLaster** [comment]
How's it going @codingnninja?

**Comment by codingnninja** [comment]
@jasonLaster I thought I would need to downgrade my node which I also use for other things that may break, so I just started working on it today after I have finished others things that could break due to node downgrade. This holiday is dedicated to the bug and I will be asking questions as per the bug starting today in the slack group. Thanks for reaching out.
