### ISSUE TITLE
testing - make it easier to navigate

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#727]
There are two ways that we navigate in the tests `initDebugger` and `navigate`.

```js
  const dbg = yield initDebugger(
    "doc-script-switching.html",
    "script-switching-01.js"
  );
```

```js
  yield navigate(dbg,
    "doc-scripts.html",
    "simple1.js",
    "simple2.js",
    "long.js"
  );
```

They both require the html file you want to navigate to and a list of the sources. We include the list of sources because we don't know when the debugger is done starting until that point.

This makes it frustrating anytime a test wants to navigate because it requires a lot of copy pasting and could change if we add a source to an example.

I propose two improvements:

* Head should have a dictionary of debuggable pages like what we do for selectors and key shortcuts
* Instead of listing the sources, we just include the number of sources

```js
const pages = {
  scripts: { url: "doc-scripts.html", sourceCount: 4 },
  scriptSwitching: { url:"doc-script-switching.html", sourceCount: 2 },
  iframes: { url: "doc-iframes.html", sourceCount: 0 },
  debuggerStatements: { url: "doc-debugger-statements.html", sourceCount: 0 },
  aboutBlank: {url:  "about:blank", sourceCount: 0 }
}

function navigate(dbg, example) {
  if (!pages[example]) {
    throw new Error(`Could not find page ${example}`);
  }

  const {url, sourceCount} = pages[example];
  dbg.client.navigate(url);
  return waitForSourcesToLoad(dbg, sourceCount)
}
```

**Comment by jbhoosreddy** [comment]
I like the first idea but I'm a bit vary of the second one (source count). It doesn't seem intuitive, especially for new people. Personally I'm fine with being explicit about the additional sources I am looking for in the debugger.

**Comment by jlongster** [comment]
You don't need to list all of the sources in the example - only the ones that you are interested in. If we added a source to an example you don't need to change any of the tests. If you do, it's because you are wanting to change how that test actually works, so you're rewriting the test or adding a lot to it anyway.

Doing this gives you control over what happens (only wait for 1 source because that's what you test, don't care about the rest), and makes it very explicit about what that action needs. I have to say I'm actually really happy about how it currently works after spending time on the old tests. Compared the the whole test file this is a tiny amount boilerplate and it makes things very explicit.

**Comment by jlongster** [comment]
Another navigation is `reload`, and for example here I just wait for a single source to be available: https://github.com/devtools-html/debugger.html/blob/highlight-line/public/js/test/mochitest/browser_dbg-editor-select.js#L76. I always only list the exact sources that I'm about to use, and it's only 1-3 sources. We can keep discussing it for sure though.

**Comment by jlongster** [comment]
(One last note...) If you are navigating frequently in a single test (usually tests just have a single `initDebugger` at the top) you can keep the array of sources you are interested in at the top and just do `navigate(dbg, url, ...sources)`. But I think it's rare for tests to be doing this, and most tests just have a single `initDebugger`.

**Comment by jasonLaster** [comment]
> reload is another navigation

good point. I suppose back/forward are as well.

> It doesn't seem intuitive to know source count

agreed, that's why it would be  in the dictionary

> You don't need to list all of the sources in the example

I think it's likely that if we do this we'll find racey tests where they work most of the time, but occasionally fail. I like the rule of thumb that *most* tests should assume the debugger is navigated and then do the test. If we are explicitly testing a partial loading state we can write that test to wait for only a certain source.

**Comment by jlongster** [comment]
Actually, I might know of the real solution (yeah, I just keep talking to myself here, sorry...).

There's a problem where other tools try to link to a source in the debugger, but the source might not exist. This happens in weird cases where a URL gets printed somewhere to a source that isn't in the page we're debugging or something. In this case, the toolbox should open up a `view-source:` URL as a new tab.

The problem is the toolbox needs a way to know if the source exists in the debugger or not. And if the debugger is not initialized, it has no way of knowing "when" to check, because the debugger has no concept of sources being "done loading" because they are never technically finished loading. Right now, it just assumes the source will exist in the debugger.

The Right Thing is to somehow allow users to tap into the initial `threadClient.getSources()` call. That promise will resolve when all of the current sources are retrieved from the server. When it resolves, all of the current sources should exist in the state. If we let the console wait on that promise, it can check the current state and decide whether or not to open a source in the debugger or a new `view-source:` tab.

So how do we expose it? I don't want to create an arbitrary event or something like that. What we can do is make the `bootstrap` function return a promise that is resolved when `initPage` is resolved, which will be the `getSources` promise. The panel's `open` function can then block on `bootstrap` and the toolbox will wait to tell anyone that the debugger is opened until that finished initializing.

Theoretically, if we do that, and wait for the `jsdebugger` tool to finish opening, we can assume that all of the sources exist in the current state, so we don't need any of this. The only thing we need to wait on is loading source texts, which is obvious and natural anyway.

**Comment by jlongster** [comment]
> I think it's likely that if we do this we'll find racey tests where they work most of the time, but occasionally fail.

If you're not waiting for a source that you expect to be there, you'll find it failing very quickly and often. I would blame the author for writing a racy test ;) because you are using state that you didn't wait for.

I think you're feeling the pain of this more with the navigation tests, but most other ones only need to wait on sources once at the top of the test, that's all. For the navigation ones, you might want to create an array of tests that you wait on.

But regardless, if there's a way for this to be handled automatically 100% without boilerplate, I think it would be better. And I think we can make that happen by blocking the tool initialization on the initial source loading. So all of this might go away.

**Comment by jasonLaster** [comment]
Will be resolved here https://github.com/devtools-html/debugger.html/pull/733
