### ISSUE TITLE
"Invalid Expression" text and style should go away when blurred

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#7464]
When we blur from the expressions element, we should clear its state so that the error styling and message does not persist.

<img width="1276" alt="invalidexpression" src="https://user-images.githubusercontent.com/46655/49704195-91f29480-fbd5-11e8-83a6-d26eb4f4e72d.png">

**Comment by AnshulMalik** [comment]
I think we should try to add the text currently in state on blur, since some people use tabs instead of enter. 
And I just looked it on chrome, chrome also tries to add whatever use typed as watch expression.

**Comment by notjaril** [comment]
I've modified #7467 to the original spec laid out by @darkwing.

As for adding the text in state on blur, similar to how Chrome handles it, I'm not sure it's ideal. I'm hesitant to infer that the user meant to add the current input just because onBlur was triggered. 

If there were enough people using Tab instead of Enter it could make sense to have them behave the same, but I wouldn't infer that from onBlur. I don't use Tabs that way, so feel free to weigh in here. 

Personally, if the input box had focus, my expected Tab behavior would be for multiple subsequent inputs (e.g. add the current input and open another input box)
