### ISSUE TITLE
Tab Context Menu Doesn't Take Into Account Pretty URLs

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#7473]
The "Close Other Tabs" and "Close Tabs to the Right" items don't take into account that the URLs are the same *but the other tab(s) is pretty printed*:

<img width="442" alt="tabbz" src="https://user-images.githubusercontent.com/46655/49708336-df322e80-fbf4-11e8-84e5-8b555564b468.png">

Obviously those items should be enabled since there's more than one tab.

**Comment by jasonLaster** [comment]
Hey @darkwing, would you mind adding a small test case and str?

**Comment by jasonLaster** [comment]
By the way, you can find more information on using context menus, check out our [doc][menu] .


[menu]: https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#context-menus

**Comment by WenInCode** [comment]
I'd like to take this on :)

**Comment by WenInCode** [comment]
@darkwing I opened up the todo mvc example and pretty printed source and the context menu seems to be showing up as desired.

<img width="1255" alt="screen shot 2019-01-14 at 9 07 00 pm" src="https://user-images.githubusercontent.com/5448834/51158176-7e73c280-1840-11e9-852e-16760bb4b294.png">

I think this was fixed in https://github.com/devtools-html/debugger.html/pull/7420/files

I'm going to close off this issue :) Feel free to re-open it if you have an existing STR
