### ISSUE TITLE
PrettyPrint: uncaught exception: Error: Line numbers must be >= 1

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#7477]
STR:

1.  Open any JS tab
2.  Click pretty print button
3.  (Everything works)
4.  Close pretty tab
5.  Click pretty print button again
6.  No pretty tab opens, see error:  `uncaught exception: Error: Line numbers must be >= 1`

**Comment by jasonLaster** [comment]
@jainsneha23 how's it going?

**Comment by jainsneha23** [comment]
Hi @jasonLaster  I am able to figure out the issue. Its because of commit 4a43e9a, where the line is set as 0 in utils/location.js
And packages/devtools-source-map/node_modules/source-map/lib/source-map-consumer.js 
if (needle.generatedLine < 1) {
      throw new Error("Line numbers must be >= 1");
    }
As generatedLine was undefined before, it used to work, now that its 0, it throws error.
Raising a PR to send line as is. Not sure if its right though.

**Comment by jasonLaster** [comment]
Cool, will review the PR soon!
