### ISSUE TITLE
Restyle Tabs

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#7494]
Idea from @jainsneha23:

> Let's remove the right border to this toggle button. And let it be independent of any line marker width. And the tabs bottom border should always be there. Also, we can change the hover CSS of the tabs, so that they doesn't highlight the border of the toggle button. We can have just the top borders, rather than the grey overlay in the tabs, while hover.

**Comment by jainsneha23** [comment]
Something like this?

<img width="453" alt="screenshot 2018-12-13 at 11 08 08 am" src="https://user-images.githubusercontent.com/8366397/49917993-7209ec00-fec7-11e8-8a6d-792e473d49d5.png">

**Comment by fvsch** [comment]
Playing around in the Browser Toolbox, this is what I get:

<img width="1213" alt="screenshot" src="https://user-images.githubusercontent.com/243601/49924846-8cd46480-feb7-11e8-9f53-53c79843347f.png">

1. Align style with the toolbox tabs
2. Add a `devtools-separator` between the "show/hide sidebar" button and the tabs (forgot to add one on the right too). This separator can be made to align cleanly with the line number's border when we have 3 digits (and we can probably add a min-width to keep that width when we have only 2 digits). For 4 or 5 digits, borders won't align but that's okay IMO.
3. The close button's cross should use the tab's text color (blue when active, gray otherwise). I think we can also remove its `transition: all ...;` which is mostly noise.
4. I tried making the close button always available but take space only for the active tab. This may be too jarring when switching tabs, so maybe we should let the close button take up space on all tabs, as in @jainsneha23's screenshot.

You can see my test in action in this screen recording (30MB):
https://www.dropbox.com/s/xd93ct97th4int9/debugger-file-tabs-style.mov?dl=1

**Comment by fvsch** [comment]
We should also remove this code which was probably made for the old toolbar style (30px height instead of 28px and tabs aligned to the bottom rather than centered):

```css
.toggle-button .togglePanes {
  vertical-align: -2px;
}
```

**Comment by carlosangon** [comment]
I'd like to take care of this task if possible.

**Comment by darkwing** [comment]
Awesome @carlosangon !  Go for it!  👍
