### ISSUE TITLE
StartPage shortcuts and their description font proportions are reversed on Windows vs Linux

### ISSUE THREAD

**Issue by gerdneuman** [devtools-html/debugger.html#7498]
(Sorry, for nitpicking but I always notice such very small inconsistency with half an eye, which makes the product look less polished than it could be)

On Linux the font of the shortcut is bigger than its description. Compare letter `P` (of `Ctrl P`) with letter `G` (of `Go to file`) on first line:

![image](https://user-images.githubusercontent.com/12525563/49928609-cb225180-fec0-11e8-8ffd-38fcd70192b5.png)

On Windows 10 it is reversed, that is, `P` is smaller than `G`:
![image](https://user-images.githubusercontent.com/12525563/49928744-1ccadc00-fec1-11e8-960b-8d83bc95f99d.png)

Same for letter `F` in second line as part of shortcut and the word `Find`. 

In any way it should be consistent.

In my opinion the Linux version (Shortcuts a bit bigger than their description) is better. Windows should be the same. Not sure what it looks like on MacOS.

Though for consistency probably better to ping a Designer here, maybe @fvsch has some idea.

**Comment by fvsch** [comment]
Yes, this situation could be improved somewhat.

Though we are never going to have the exact same look here because we use system fonts. That means different fonts on each platform, and on Linux there are dozens of possible results depending on the distribution, distribution version, packages installed, etc.

Anyway, I would advise:

1. Using the `var(--monospace-font-family)` variable for the shortcuts, instead of `font-family: Courier` (which can mean Courier on macOS, the very different Courier New on Windows, and some random font on Linux). This is also the only place where we're not using the same monospace font as everywhere else, so we should probably fix that.

2. Setting the font-size more precisely; Maybe `font-size: 14px; line-height: 18px;` for both, which will result in the monospace text appearing bigger (with most monospace fonts we end up using), or maybe keep the same line-height but bring the monospace font-size down to 13px.

**Comment by fvsch** [comment]
Just noticed that on your Linux screenshot, `font-family: Courier` results in a variable-width, serif font being picked. This is why one should _always_ specify the generic font family, e.g. `font-family: Courier, monospace;`. :)

**Comment by fvsch** [comment]
Would be nice to make the text a bit more contrasted. E.g. using `color: var(--theme-body-color)`
 for the keyboard shortcut. And we can probably use Flexbox to visually center content.

![screen shot](https://user-images.githubusercontent.com/243601/49934416-97e6bf00-fece-11e8-9a17-e261626bb280.png)

**Comment by nagpalm7** [comment]
Can I work on this issue if available! @fvsch
