### ISSUE TITLE
Error while entered 'npm start'

### ISSUE THREAD

**Issue by Kelotixy** [devtools-html/debugger.html#763]
Here is screenshot - https://gyazo.com/d2e0db8926cbee6b5e05f95ab3888a7b

**Comment by jlongster** [comment]
Does this happen when you just run `webpack`? If you are on windows (which seems like it), you might need to do `node .\node_modules\.bin\webpack`. 

I can't think of anything off the top of my head. I'm pretty sure other people on windows have been able to run it.

**Comment by wldcordeiro** [comment]
@jlongster could be problems with their `NODE_PATH`? http://stackoverflow.com/a/9588052

**Comment by Kelotixy** [comment]
When I write `node .\node_modules\.bin\webpack`, - error - https://gyazo.com/c460631678bf9ae894819f328610eba7
Can you give me ready project with coplied files? Because webpack can't compile them.

**Comment by jlongster** [comment]
That's very confusing because that is not what I have in `node_modules/.bin/webpack`. This is mine: https://gist.github.com/jlongster/f5fb0614a810eed719b470ba7c15fdbc

It looks like it's trying to run linux commands on windows, but for me webpack is all written in JS.

What version of node are you using? It's hard to debug this, and I think other people on windows have had no trouble.

I don't think it will help much to give you compiled files; you wouldn't be able to productively change anything or open PRs back into the project.
