### ISSUE TITLE
Blackbox icon appears too big on hover

### ISSUE THREAD

**Issue by jaril** [devtools-html/debugger.html#7842]
The blackbox icon's highlighted grey square on hover is larger than the pretty print icon's beside it. I would have expected that it wouldn't go up past the footer.

It's possible both the blackbox and the pretty print icon are oversized for the footer, and it just so happens that the breakpoint gutter overlaps and hides the excess coming from the pretty print icon, which hides it and makes it look correctly-sized. 

Behavior below:

![jan-29-2019 21-00-08](https://user-images.githubusercontent.com/15959269/51957321-372d2a80-2419-11e9-9271-3be08d74532b.gif)

**Comment by fvsch** [comment]
Both icons are reported with the same size for me: 28 by 28px.
The size is due to the button's 6px padding and 16px icon (6*2+16=28).

One issue is that the content area of the footer is 23px-tall.
The `--editor-footer-height` variable is set to 24px, and we're using a 1px border, leaving 23px for the content.

Solutions:
1. Change `--editor-footer-height` to 29px (28px for content), same as the top toolbar.
2. Change `--editor-footer-height` to 25px (24px for content), and the button's padding to `4px 6px`.
