### ISSUE TITLE
Ignore exceptions button tooltip is incorrect and icon doesn't change state to indicate its status

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#803]
STR:
- Open any page, like data:text/html,test
- In my case I tested this in Firefox devtools in the console
- Try to execute a non-existing function in the console like `foo()`

The debugger panel gets selected and pauses on this line.
But:

- If I hover over the ignore exceptions button, its tooltip says: "Pause on uncaught exceptions". Since it already paused, I would expect it to say the opposite: "Ignore exceptions" so that I know that if I click it, then it's going to ignore exceptions in the future and not automatically pause.
- If I resume, click on the button and execute `foo()` again, then the debugger doesn't pause, which is good, but the tooltip now says "Ignore exceptions", which is the state I'm already in, it should say "Pause on uncaught exceptions".

Also, the icon itself is always the same, same color, same drawing, so there's no visual way for me to tell which mode I'm in:

![capture](https://cloud.githubusercontent.com/assets/1152698/18741595/516b0d9a-80b0-11e6-9ec5-a272c9e65492.PNG)

**Comment by jasonLaster** [comment]
Thanks for the feedback @captainbrosset.

This is somewhat addressed by #680. Unfortunately, I don't think it's intuitive what the language in the tooltip should be. Is it the current state, or is it what you will get if you click on it. Most of the time, it's the latter, but in this case the icon is not discriptive because all three states are the same :/

**Comment by jlongster** [comment]
Closed by #816
