### ISSUE TITLE
Handle 'debugger' statements like breakpoints

### ISSUE THREAD

**Issue by SebastianZ** [devtools-html/debugger.html#828]
As mentioned in [comment 8 of Bugzilla bug 1300934](https://bugzilla.mozilla.org/show_bug.cgi?id=1300934#c8) `debugger` statements should be treated like normal breakpoints, i.e. they should be shown within the _Breakpoints_ panel and within the breakpoint column inside the source view.

Besides other advantages, this provides a consistent UI and allows to disable them individually.

Sebastian

PS: I already [suggested that (besides other Debugger UI improvements) for Firebug a long time ago](https://github.com/firebug/firebug/issues/2923#issuecomment-103408235).

**Comment by wldcordeiro** [comment]
I agree this would be a great feature to add, thanks for the suggestion.

> PS: I already suggested that (besides other Debugger UI improvements) for Firebug a long time ago.

This isn't that project and their issues aren't this project's issues.

**Comment by jlongster** [comment]
Yeah, we should do something like this. Not sure what the UX is like yet. debugger statements are weird because everything is different about them: how to remove/disable/etc. When you remove a breakpoint, it does not come back on refresh, but a debugger statement would.

Anyway, yes, we want to figure this out but there's lots of UX and technical issues to figure out. We will need to add something to the debugger server to give us this information, because we don't even have the source text available client-side until you view a source.

**Comment by SebastianZ** [comment]
>> PS: I already suggested that (besides other Debugger UI improvements) for Firebug a long time ago.
> 
> This isn't that project and their issues aren't this project's issues.

I know. Note that I am a former Firebug developer. I just mentioned it, because it contains some more useful information.

> When you remove a breakpoint, it does not come back on refresh, but a debugger statement would.

Because the code can't be changed by the debugger, debugger statement breakpoints wouldn't have an option to remove them.

> Anyway, yes, we want to figure this out but there's lots of UX and technical issues to figure out.

Yes, for sure, UX will be hard to get right.

Sebastian

**Comment by wldcordeiro** [comment]
Thanks for the clarification @SebastianZ I think UX wise we'll definitely want to make it clear that a breakpoint set by a debugger statement is one and non-removable. 

![screenshot_20160927_094937](https://cloud.githubusercontent.com/assets/580982/18881205/b93533ac-8497-11e6-9683-d6270ef40aa3.png)

Like having a `[debugger statement]` text added to the left of the breakpoint detail or something else to clarify its difference.

**Comment by clarkbw** [comment]
I did a little work on this previously in #422

**Comment by SoonDead** [comment]
I would like to be able to disable debugger statements while having my own breakpoints.

It's a pain if you debug code you don't own and the code author decided to protect the code with debugger statements. Give me a break (pun intended).

**Comment by DerpMcDerp** [comment]
I came here from bugzilla bug 1300934 because there is an annoying media player website which does something akin to:

```
setInterval(function() { try { debugger; } catch {} }, 500);
```

To make people who use the inspector tools suffer and I was looking if firefox had an easy way to disable the debugger statement globally.

The ability to put "debugger;" statements in the breakpoint list is a good idea but it would be even better if there was a way to make "debugger;" statements opt-in rather than opt-out. i.e. "debugger;" are off by default until you explicitly tick them in the breakpoint list.

**Comment by jasonLaster** [comment]
I did a little research here and noticed that if you add a conditional breakpoint - false on a debugger statement, then the debugger does not pause.

I agree wih @DerpMcDerp, the main problem we're trying to solve is preventing debugger bottlenecks, basically anytime it keeps pausing and is annoying.

Given that, I think a good solution would be to provide the user with an easy way to disable debugger statements when they're paused there. Under the hood we'd be adding a conditional bp set to false.

Perhaps a disable prompt:
* in the breakpoints pane
* next to the statement
* next to a place where we state the reason for the pause (similar to chrome's top right treatment)

Notes:
* This solution would avoid doing an expensive parse of the project source in search for debugger statements
* We'd also want an easy way to re-enable debugger statements.

**Comment by jasonLaster** [comment]
closing as we'll be able to discuss this as one of many enhancements

feel free to add to the discussion even though it's closed

**Comment by SebastianZ** [comment]
> closing as we'll be able to discuss this as one of many enhancements

Where will this discussion take place?

Sebastian

**Comment by jasonLaster** [comment]
Good question:

Here are the other [enhancements](https://github.com/devtools-html/debugger.html/projects/5).

The conversation can continue here and perhaps subsequent feature issues. 

Sorry that this process is not that clear, I think we might adopt an RFC style repo process at some point so we can have open issues to discuss and plan. and perhaps roadmap issues as well where we can openly prioritize.

**Comment by SebastianZ** [comment]
There's a related [use case for this on Stack Overflow](http://stackoverflow.com/q/41801175/432681).

Sebastian

**Comment by clarkbw** [comment]
I wanted to write down my thoughts about a UX to handle this.  By adding debugger statements into the breakpoint list we create this intersection of items that aren't actually compatible.  Debugger statements would only appear in the list as they are encountered when paused, so unlike breakpoints they will disappear on refresh.  We could probably hide the complexity of the enable / disable with decent amount of engineering but I think for now we could offer a simple working solution.  In a future where we have a way to scan / search sources for debugger statements or have some reliable cache / storage of the source files I think we could more easily move to treating these like breakpoints.  This concept is taken mostly from what @jasonLaster wrote in https://github.com/devtools-html/debugger.html/issues/828#issuecomment-258638533 above.

When a debugger statement is encountered we explain this to users in the `WhyPaused` component.  I think we should add a method, in the `WhyPaused` component to disable the debugger statement. (that text / button is just placeholder)

<img width="306" alt="screen shot 2017-01-23 at 6 29 39 am" src="https://cloud.githubusercontent.com/assets/2134/22208005/28c8b950-e136-11e6-9cf5-9f30d38c16cf.png">

This method would simply create the conditional breakpoint `false` for this line which skips the debugger statement.  And actually the conditional breakpoint is almost self explanatory when it appears. We should likely explain how the disable system works because I'm not sure it will be clear to users that the condition breakpoint created is what does the disabling. 

<img width="306" alt="screen shot 2017-01-23 at 6 30 01 am" src="https://cloud.githubusercontent.com/assets/2134/22208148/b06513b8-e136-11e6-8eb4-74df13b59d19.png">

But this solution keeps the systems all fairly simple and allows for users to disable debugger statements as they encounter them. Users can also then enable / disable the conditional breakpoint so they have control over when the debugger statement is reached.  The only wonky part will be if the conditional breakpoint is disabled the `WhyPaused` component would appear and offer to disable the breakpoint again.  Not sure how that would play out.

**Comment by rulatir** [comment]
DON'T

This request, if implemented, will provide a half-feature that doesn't solve most of the problem, but will likely prevent the real problem for being considered for years to come, because "hey, we implemented this, now stop complaining".

"Most of the problem" is that some websites defeat devtools with a `debugger` statement **in an eval()** executed repeatedly with `setInterva()`. Each of those `debugger` statements is distinct, therefore **no** counter-measures that boil down to only disabling **existing** debugger statements will defeat this technique. We also **do need** a way to disable **all future debugger statements**.

**Comment by SebastianZ** [comment]
Stopping websites from defeating the debugger by generating dynamic `debugger` statements is a different use case (already [mentioned](https://github.com/firefox-devtools/debugger/issues/828#issuecomment-258226174) by @DerpMcDerp earlier), nonetheless a very important one.

So, as he or she already noted, there should be an option to completely disable halting on `debugger` statements.

As both features do not exclude each other, I've now created #8228 to discuss this separately.

Sebastian
