### ISSUE TITLE
paused indicator line in editor isn't respecting editor state

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#873]
![pause line issue](https://cloud.githubusercontent.com/assets/2134/19079970/571716e0-8a0a-11e6-9bb9-783484085abb.gif)

When I paused in the editor and then looked at other sources the pause line remained.  Further, when you continue or step the original pause line remains and a new one is drawn. 😞

**Comment by jlongster** [comment]
This was introduced when we started using CodeMirror's documents because they keep track of line classes and our current logic for clearing them doesn't properly clear them on the previous document.

I saw this as well a little while ago and could have sworn I had a fix... but I don't know what happened. Sorry, I'll take this and make sure it gets fixed.

**Comment by jlongster** [comment]
Fixed in https://github.com/devtools-html/debugger.html/pull/900
