### ISSUE TITLE
Tabs - New tab button

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#951]
It would be great to have a new tab button that opens the file search UI.

The relevant files are:

1) [SourcesTab](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/SourceTabs.js). We likely can add the plus button in the render method
2) [App.js](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/App.js#L76-L79) - handles showing file search.

How do we show file search? The App currently listens for cmd+p events on the window. I think the easiest way to implement this feature would be to emit the cmd+p event on the window.

![](https://cloud.githubusercontent.com/assets/1720093/19536699/084d65a6-961b-11e6-807a-b84d2149c31c.png)

**Comment by helenvholmes** [comment]
I think what @nt1m's designed is really natural—this is exactly what I would have designed since it's the pattern browsers have set up for spinning up new tabs.

To answer @clarkbw's concerns: We don't currently have anywhere else where we've set up UX patterns for this particular use case anywhere in the tools, so what we do here sets up the precent. This is the pattern set up by te browser itself, so I think it's safe to continue copying.

[This](https://cl.ly/0g0X3B2g402I) is the icon I'd use for it. I'd also use ```var(--theme-splitter-color)``` for its fill, with ```var(--theme-comment)``` as its hover state.

**Comment by clarkbw** [comment]
@helenvholmes what would you like to do when the tabs overflow? Always keep space for the + icon at the right of the last tab?

I think the overflow icon is broken currently but we should take that into account.

**Comment by wldcordeiro** [comment]
Taking this since @helenvholmes seems to have put it up for grabs. 😄

**Comment by helenvholmes** [comment]
> @helenvholmes what would you like to do when the tabs overflow? Always keep space for the + icon at the right of the last tab?
> 
> I think the overflow icon is broken currently but we should take that into account.

I think once the tabs overflow we should make room for the tab overflow icon, and the "+" icon should disappear. Just added info for you, @wldcordeiro!

**Comment by wldcordeiro** [comment]
@helenvholmes I had it so the new tab button is always present even with the overflow menu. That seems like more expected behavior to me as in browsers like Chrome/Firefox the new tab button is always present (though they reduce tab sizes to just icons and scroll the tab bar).

![screenshot_20161026_090148](https://cloud.githubusercontent.com/assets/580982/19731532/f3c1ca7e-9b5a-11e6-8861-d69ca98c0cbe.png)

**Comment by helenvholmes** [comment]
Is our overflow menu those three dots?

**Comment by jasonLaster** [comment]
> Is our overflow menu those three dots?

@helenvholmes yep, but that could certainly be improved.

**Comment by helenvholmes** [comment]
I have this spec for overflow panels, if it's helpful: [spec](https://invis.io/F68A5KHKY#/179720580_Sidebar_Tabs)

I think the main thing is that we're using guillemets (») for side panels—the rest is probably what you'd expect, hopefully 🙂

**Comment by wldcordeiro** [comment]
I like the guillemet for the tab overflow @helenvholmes especially because that's just a fun word to say 🙂 Would that make sense in a different PR? I can change it in the new tab one too.

**Comment by helenvholmes** [comment]
@wldcordeiro However you'd like to handle it! Making sure overflow is working is important enough I'd like to see it solidly in, know that we can throw up changing the icon in an up-for-grabs easy bug.

**Comment by wldcordeiro** [comment]
@helenvholmes I believe @jasonLaster fixed overflow so it's working, only thing left is the icon.

**Comment by jasonLaster** [comment]
Just created a button issue https://github.com/devtools-html/debugger.html/issues/1015 to simplify this PR.
